import type { Example } from './schema';

/** Code challenge Build examples for L3, L6–L12. */
export const BUILD_EXTRAS: Record<string, Example[]> = {
  lesson03: [
    {
      id: 'l3-build-1',
      type: 'codeChallenge',
      stage: 'build',
      tags: ['truthiness'],
      prompt: 'Write is_positive(n) returning True if n > 0 else False.',
      starterCode: 'def is_positive(n):\n    pass',
      tests: ['assert is_positive(1) == True', 'assert is_positive(0) == False', 'assert is_positive(-3) == False'],
      explanation: 'Return n > 0 — a boolean expression.',
    },
  ],
  lesson06: [
    {
      id: 'l6-build-1',
      type: 'codeChallenge',
      stage: 'build',
      tags: [],
      prompt: 'Write reverse(s) that returns the string s reversed.',
      starterCode: 'def reverse(s):\n    pass',
      tests: ['assert reverse("abc") == "cba"', 'assert reverse("") == ""', 'assert reverse("a") == "a"'],
      explanation: 'Slice with [::-1] or build a reversed string in a loop.',
    },
    {
      id: 'l6-build-2',
      type: 'codeChallenge',
      stage: 'build',
      tags: [],
      prompt: 'Write count_vowels(s) returning the number of a,e,i,o,u (case insensitive).',
      starterCode: 'def count_vowels(s):\n    pass',
      tests: ['assert count_vowels("hello") == 2', 'assert count_vowels("xyz") == 0'],
      explanation: 'Loop characters and check membership in "aeiouAEIOU".',
    },
  ],
  lesson07: [
    {
      id: 'l7-build-1',
      type: 'codeChallenge',
      stage: 'build',
      tags: ['mutation'],
      prompt: 'Write append_all(lst, x) that appends x to lst and returns lst.',
      starterCode: 'def append_all(lst, x):\n    pass\n    return lst',
      tests: ['a=[1]; append_all(a,2); assert a==[1,2]', 'b=[]; append_all(b,0); assert b==[0]'],
      explanation: 'Use lst.append(x) — mutates the list in place.',
    },
    {
      id: 'l7-build-2',
      type: 'codeChallenge',
      stage: 'build',
      tags: [],
      prompt: 'Write first_last(t) returning (t[0], t[-1]) or (None, None) if empty.',
      starterCode: 'def first_last(t):\n    pass',
      tests: ['assert first_last((1,2,3)) == (1, 3)', 'assert first_last(()) == (None, None)'],
      explanation: 'Check len(t) == 0 first, else return tuple indexing.',
    },
  ],
  lesson08: [
    {
      id: 'l8-build-1',
      type: 'codeChallenge',
      stage: 'build',
      tags: ['dictKeys'],
      prompt: 'Write word_count(words) returning a dict mapping each word to its count.',
      starterCode: 'def word_count(words):\n    pass',
      tests: ['assert word_count(["a","b","a"]) == {"a":2,"b":1}', 'assert word_count([]) == {}'],
      explanation: 'Increment counts in a dict as you loop.',
    },
    {
      id: 'l8-build-2',
      type: 'codeChallenge',
      stage: 'build',
      tags: [],
      prompt: 'Write unique_sorted(lst) returning sorted list of unique values.',
      starterCode: 'def unique_sorted(lst):\n    pass',
      tests: ['assert unique_sorted([3,1,2,1]) == [1,2,3]', 'assert unique_sorted([]) == []'],
      explanation: 'sorted(set(lst)) works for hashable items.',
    },
  ],
  lesson09: [
    {
      id: 'l9-build-1',
      type: 'codeChallenge',
      stage: 'build',
      tags: ['comprehension'],
      prompt: 'Write evens(n) returning list of even numbers from 0 up to n-1.',
      starterCode: 'def evens(n):\n    pass',
      tests: ['assert evens(6) == [0,2,4]', 'assert evens(0) == []'],
      explanation: '[x for x in range(n) if x % 2 == 0]',
    },
    {
      id: 'l9-build-2',
      type: 'codeChallenge',
      stage: 'build',
      tags: [],
      prompt: 'Write double_all(nums) returning a new list with each element doubled.',
      starterCode: 'def double_all(nums):\n    pass',
      tests: ['assert double_all([1,2]) == [2,4]', 'assert double_all([]) == []'],
      explanation: 'List comprehension [x*2 for x in nums].',
    },
  ],
  lesson10: [
    {
      id: 'l10-build-1',
      type: 'codeChallenge',
      stage: 'build',
      tags: ['exceptionType'],
      prompt: 'Write safe_int(s) that returns int(s) or None if ValueError.',
      starterCode: 'def safe_int(s):\n    pass',
      tests: ['assert safe_int("42") == 42', 'assert safe_int("x") is None'],
      explanation: 'try/except ValueError around int(s).',
    },
    {
      id: 'l10-build-2',
      type: 'codeChallenge',
      stage: 'build',
      tags: [],
      prompt: 'Write lines(text) returning the number of lines in text (split by newline).',
      starterCode: 'def lines(text):\n    pass',
      tests: ['assert lines("a\\nb") == 2', 'assert lines("") == 1'],
      explanation: 'text.split("\\n") then len; empty string is one line in split semantics or use max(1,...).',
    },
  ],
  lesson11: [
    {
      id: 'l11-build-1',
      type: 'codeChallenge',
      stage: 'build',
      tags: ['oopAttrs'],
      prompt: 'Write a function make_point(x,y) returning an object with .x and .y attributes.',
      starterCode: 'def make_point(x, y):\n    class Point:\n        pass\n    p = Point()\n    # set attributes\n    return p',
      tests: ['p=make_point(1,2); assert p.x==1 and p.y==2'],
      explanation: 'Set p.x and p.y on a simple class instance.',
    },
    {
      id: 'l11-build-2',
      type: 'codeChallenge',
      stage: 'build',
      tags: [],
      prompt: 'Write greet(person) where person has .name; return "Hi, {name}".',
      starterCode: 'def greet(person):\n    pass',
      tests: ['class P:\n    name="Ada"\nassert greet(P()) == "Hi, Ada"'],
      explanation: 'Use person.name in an f-string.',
    },
  ],
  lesson12: [
    {
      id: 'l12-build-1',
      type: 'codeChallenge',
      stage: 'build',
      tags: ['recursion'],
      prompt: 'Write factorial(n) recursively for n >= 0.',
      starterCode: 'def factorial(n):\n    pass',
      tests: ['assert factorial(0) == 1', 'assert factorial(5) == 120'],
      explanation: 'Base n==0 return 1; else n * factorial(n-1).',
    },
    {
      id: 'l12-build-2',
      type: 'codeChallenge',
      stage: 'build',
      tags: [],
      prompt: 'Write sum_list(nums) recursively (empty list returns 0).',
      starterCode: 'def sum_list(nums):\n    pass',
      tests: ['assert sum_list([1,2,3]) == 6', 'assert sum_list([]) == 0'],
      explanation: 'Return 0 if empty else nums[0] + sum_list(nums[1:]).',
    },
  ],
  lesson13: [
    {
      id: 'l13-build-1',
      type: 'codeChallenge',
      stage: 'build',
      tags: ['assertLogic', 'identity'],
      prompt: 'Write first_or_none(items) — return items[0] if non-empty else None.',
      starterCode: 'def first_or_none(items):\n    pass',
      tests: [
        'assert first_or_none([1, 2]) == 1',
        'assert first_or_none([]) is None',
        'assert first_or_none(["a"]) == "a"',
      ],
      explanation: 'if not items: return None else return items[0]. Use `is None` in tests.',
    },
  ],
  lesson14: [
    {
      id: 'l14-build-1',
      type: 'codeChallenge',
      stage: 'build',
      tags: ['loopLogic'],
      prompt: 'Write index_of(items, target) using enumerate — return index or -1 if missing.',
      starterCode: 'def index_of(items, target):\n    pass',
      tests: [
        'assert index_of(["a", "b"], "b") == 1',
        'assert index_of([1, 2], 3) == -1',
        'assert index_of([], 0) == -1',
      ],
      explanation: 'for i, x in enumerate(items): if x == target: return i; return -1',
    },
  ],
  lesson15: [
    {
      id: 'l15-build-1',
      type: 'codeChallenge',
      stage: 'build',
      tags: ['jsonCsv'],
      prompt: 'Write parse_age(json_str) — json.loads then return data["age"] as int.',
      starterCode: 'import json\n\ndef parse_age(json_str):\n    pass',
      tests: [
        'assert parse_age(\'{"age": 20}\') == 20',
        'assert parse_age(\'{"age": "30"}\') == 30',
        'assert parse_age(\'{"age": 0}\') == 0',
      ],
      explanation: 'loads → dict → int(data["age"]) handles numeric or string age.',
    },
  ],
  lesson16: [
    {
      id: 'l16-build-1',
      type: 'codeChallenge',
      stage: 'build',
      tags: ['generators'],
      prompt: 'Write count_up(n) generator yielding 1, 2, ..., n (use yield in a loop).',
      starterCode: 'def count_up(n):\n    pass',
      tests: [
        'assert list(count_up(3)) == [1, 2, 3]',
        'assert list(count_up(0)) == []',
        'assert list(count_up(1)) == [1]',
      ],
      explanation: 'for i in range(1, n+1): yield i',
    },
  ],
};
