import type { Example } from './schema';

/** Interactive example types (orderLines, matchPairs, dragBlank) — ~20+ across L1–L12. */
export const INTERACTIVE_EXTRAS: Record<string, Example[]> = {
  lesson01: [
    {
      id: 'l1-int-1',
      type: 'orderLines',
      stage: 'try',
      tags: [],
      prompt: 'Order these lines so the program asks for a name and prints a greeting.',
      lines: ['name = input("Name? ")', 'print(f"Hello, {name}!")'],
      correctOrder: [0, 1],
      explanation: 'Read input first, then use name in the print.',
    },
    {
      id: 'l1-int-2',
      type: 'dragBlank',
      stage: 'try',
      tags: [],
      prompt: 'Complete the print statement with an f-string.',
      code: 'age = 20\nprint(f"I am {{age}} years old")',
      blanks: [{ id: 'age', answer: '{age}' }],
      distractors: ['age', '$age', '{Age}'],
      explanation: 'Inside an f-string, use {age} to interpolate the variable.',
    },
    {
      id: 'l1-int-3',
      type: 'matchPairs',
      stage: 'try',
      tags: ['typeCoercion'],
      prompt: 'Match type name to example value.',
      leftItems: ['int', 'float', 'str', 'bool'],
      rightItems: ['3.14', '"hi"', 'True', '42'],
      pairs: [[0, 3], [1, 0], [2, 1], [3, 2]],
      explanation: 'int 42, float 3.14, str "hi", bool True.',
    },
  ],
  lesson02: [
    {
      id: 'l2-int-1',
      type: 'orderLines',
      stage: 'try',
      tags: ['typeCoercion'],
      prompt: 'Put these lines in the order Python executes them to compute a result.',
      lines: ['result = a + b', 'a = 3', 'b = 5', 'print(result)'],
      correctOrder: [1, 2, 0, 3],
      explanation: 'Variables must be assigned before use in result = a + b.',
    },
    {
      id: 'l2-int-2',
      type: 'matchPairs',
      stage: 'try',
      tags: ['truthiness'],
      prompt: 'Match each expression to its value.',
      leftItems: ['3 // 2', '3 / 2', '3 ** 2', '3 % 2'],
      rightItems: ['1.5', '1', '9', '1'],
      pairs: [[0, 1], [1, 0], [2, 2], [3, 1]],
      explanation: '// is floor division; / is float division; ** is power; % is remainder.',
    },
  ],
  lesson03: [
    {
      id: 'l3-int-1',
      type: 'orderLines',
      stage: 'debug',
      tags: ['truthiness'],
      prompt: 'Order lines so the program prints "yes" when x is positive.',
      lines: ['    print("yes")', 'if x > 0:', 'x = 5'],
      correctOrder: [2, 1, 0],
      explanation: 'Assign x, test condition with colon, then indented body.',
    },
    {
      id: 'l3-int-2',
      type: 'dragBlank',
      stage: 'try',
      tags: ['truthiness'],
      prompt: 'Complete the elif chain.',
      code: 'n = 0\nif n > 0:\n    print("pos")\nelif {{cond}}:\n    print("zero")',
      blanks: [{ id: 'cond', answer: 'n == 0' }],
      distractors: ['n = 0', 'n != 0', 'n > 0'],
      explanation: 'Use n == 0 to catch zero after ruling out positive.',
    },
  ],
  lesson04: [
    {
      id: 'l4-int-1',
      type: 'orderLines',
      stage: 'try',
      tags: ['loopLogic', 'offByOne'],
      prompt: 'Order lines to print 0, 1, 2 using a for loop.',
      lines: ['for i in range(3):', '    print(i)'],
      correctOrder: [0, 1],
      explanation: 'Header first, then indented loop body.',
    },
    {
      id: 'l4-int-2',
      type: 'dragBlank',
      stage: 'try',
      tags: ['offByOne'],
      prompt: 'Fill in the range for printing 1 through 5 inclusive.',
      code: 'for i in range({{start}}, {{stop}}):\n    print(i)',
      blanks: [
        { id: 'start', answer: '1' },
        { id: 'stop', answer: '6' },
      ],
      distractors: ['0', '5', 'range(5)'],
      explanation: 'range(1, 6) yields 1,2,3,4,5 — stop is exclusive.',
    },
  ],
  lesson05: [
    {
      id: 'l5-int-1',
      type: 'matchPairs',
      stage: 'try',
      tags: ['scope'],
      prompt: 'Match function terminology.',
      leftItems: ['def f(x):', 'return x * 2', 'f(3)', 'parameter'],
      rightItems: ['call site', 'function header', 'name for argument in header', 'sends value back'],
      pairs: [[0, 1], [1, 3], [2, 0], [3, 2]],
      explanation: 'def introduces header; return exits with value; f(3) calls; parameter is x in header.',
    },
    {
      id: 'l5-int-2',
      type: 'dragBlank',
      stage: 'build',
      tags: ['scope'],
      prompt: 'Complete a function that doubles its argument.',
      code: 'def double(n):\n    {{body}}\n    return result',
      blanks: [{ id: 'body', answer: 'result = n * 2' }],
      distractors: ['n * 2', 'return n', 'print(n)'],
      explanation: 'Store n * 2 in result before returning.',
    },
  ],
  lesson06: [
    {
      id: 'l6-int-1',
      type: 'matchPairs',
      stage: 'stretch',
      tags: [],
      prompt: 'Match string method to its result on s = "hello".',
      leftItems: ['s.upper()', 's[1:4]', 'len(s)', 's.replace("l", "L")'],
      rightItems: ['5', '"HELLO"', '"ell"', '"heLLo"'],
      pairs: [[0, 1], [1, 2], [2, 0], [3, 3]],
      explanation: 'upper capitalizes; slice [1:4] is ell; len is 5; replace swaps chars.',
    },
  ],
  lesson07: [
    {
      id: 'l7-int-1',
      type: 'orderLines',
      stage: 'debug',
      tags: ['mutation', 'aliasing'],
      prompt: 'Order lines showing aliasing then mutation.',
      lines: ['b.append(99)', 'b = a', 'a = [1, 2]', 'print(a, b)'],
      correctOrder: [2, 1, 0, 3],
      explanation: 'Create a, alias b to a, mutate through b, then print both.',
    },
    {
      id: 'l7-int-2',
      type: 'matchPairs',
      stage: 'stretch',
      tags: ['aliasing', 'mutation'],
      prompt: 'Match code snippet to side effect.',
      leftItems: ['a = [1]; b = a; b.append(2)', 'a = [1]; b = a + [2]', 'a = (1,); b = a'],
      rightItems: ['a and b share one list', 'a unchanged, b is new list', 'tuples are immutable'],
      pairs: [[0, 0], [1, 1], [2, 2]],
      explanation: 'Append via alias mutates shared list; + creates new list; tuples cannot mutate.',
    },
  ],
  lesson08: [
    {
      id: 'l8-int-1',
      type: 'dragBlank',
      stage: 'try',
      tags: ['dictKeys'],
      prompt: 'Build a dict lookup with .get and default.',
      code: 'counts = {"a": 1}\nval = counts.{{method}}("b", {{default}})',
      blanks: [
        { id: 'method', answer: 'get' },
        { id: 'default', answer: '0' },
      ],
      distractors: ['keys', '1', 'None'],
      explanation: 'get returns default when key missing without KeyError.',
    },
    {
      id: 'l8-int-2',
      type: 'matchPairs',
      stage: 'try',
      tags: ['dictKeys'],
      prompt: 'Match collection to property.',
      leftItems: ['{1, 2, 2}', '{"a": 1}', '(1, 2)', '[1, 2]'],
      rightItems: ['duplicate keys rejected', 'ordered mutable', 'hashable keys in dict', 'immutable sequence'],
      pairs: [[0, 0], [1, 2], [2, 3], [3, 1]],
      explanation: 'Sets dedupe; dict keys must be hashable; tuple immutable; list mutable.',
    },
  ],
  lesson09: [
    {
      id: 'l9-int-1',
      type: 'dragBlank',
      stage: 'try',
      tags: ['comprehension'],
      prompt: 'Complete a list comprehension for squares.',
      code: 'squares = [{{expr}} for x in {{iter}}]',
      blanks: [
        { id: 'expr', answer: 'x ** 2' },
        { id: 'iter', answer: 'range(5)' },
      ],
      distractors: ['x * 2', 'range(4)', 'x'],
      explanation: 'Square each x for x in 0..4 via range(5).',
    },
  ],
  lesson10: [
    {
      id: 'l10-int-1',
      type: 'matchPairs',
      stage: 'try',
      tags: ['exceptionType', 'fileMode'],
      prompt: 'Match exception to typical cause.',
      leftItems: ['FileNotFoundError', 'ValueError', 'ZeroDivisionError', 'KeyError'],
      rightItems: ['missing dict key', 'invalid int conversion', 'open missing path', 'divide by zero'],
      pairs: [[0, 2], [1, 1], [2, 3], [3, 0]],
      explanation: 'Each builtin exception matches its common trigger.',
    },
    {
      id: 'l10-int-2',
      type: 'orderLines',
      stage: 'try',
      tags: ['fileMode'],
      prompt: 'Order lines for safe file read with context manager.',
      lines: ['    data = f.read()', 'with open("f.txt") as f:', 'print(data)'],
      correctOrder: [1, 0, 2],
      explanation: 'with opens file, read inside block, print after.',
    },
  ],
  lesson11: [
    {
      id: 'l11-int-1',
      type: 'dragBlank',
      stage: 'build',
      tags: ['oopAttrs'],
      prompt: 'Complete a minimal class with __init__.',
      code: 'class Dog:\n    def {{init}}(self, name):\n        self.name = name',
      blanks: [{ id: 'init', answer: '__init__' }],
      distractors: ['init', '__str__', 'constructor'],
      explanation: '__init__ is Python constructor method name.',
    },
    {
      id: 'l11-int-2',
      type: 'orderLines',
      stage: 'try',
      tags: ['oopAttrs'],
      prompt: 'Order lines to create and use an instance.',
      lines: ['d = Dog("Rex")', 'class Dog:\n    def __init__(self, n): self.n = n', 'print(d.n)'],
      correctOrder: [1, 0, 2],
      explanation: 'Define class before instantiation, then access attribute.',
    },
  ],
  lesson12: [
    {
      id: 'l12-int-1',
      type: 'matchPairs',
      stage: 'stretch',
      tags: ['recursion'],
      prompt: 'Match recursive pattern to base case role.',
      leftItems: ['if n == 0: return 1', 'return n * fact(n-1)', 'fact(5)', 'stack depth grows'],
      rightItems: ['stops recursion', 'recursive step', 'triggers full chain', 'risk without base case'],
      pairs: [[0, 0], [1, 1], [2, 2], [3, 3]],
      explanation: 'Base case halts; recursive step shrinks problem; call starts chain.',
    },
    {
      id: 'l12-int-2',
      type: 'orderLines',
      stage: 'try',
      tags: ['recursion'],
      prompt: 'Order lines for recursive countdown.',
      lines: ['    countdown(n - 1)', 'def countdown(n):', '    if n <= 0: return', '    print(n)'],
      correctOrder: [1, 2, 3, 0],
      explanation: 'Define function, base case, print, then recurse.',
    },
  ],
  lesson13: [
    {
      id: 'l13-int-1',
      type: 'dragBlank',
      stage: 'try',
      tags: ['identity'],
      prompt: 'Fill in the correct None test.',
      code: 'if result {{blank}} None:\n    print("missing")',
      blanks: [{ id: 'blank', answer: 'is' }],
      distractors: ['==', 'is not', '='],
      explanation: 'Use `is` to test identity with None.',
    },
    {
      id: 'l13-int-2',
      type: 'orderLines',
      stage: 'stretch',
      tags: ['traceback'],
      prompt: 'Order steps to debug from a traceback.',
      lines: [
        'Read exception type at the bottom',
        'Find your code in the stack frames',
        'Inspect the failing line',
        'Fix and re-run',
      ],
      correctOrder: [0, 1, 2, 3],
      explanation: 'Bottom-up reading leads you to the fix fastest.',
    },
  ],
  lesson14: [
    {
      id: 'l14-int-1',
      type: 'dragBlank',
      stage: 'try',
      tags: ['loopLogic'],
      prompt: 'Complete enumerate loop header.',
      code: 'for {{i}}, {{x}} in enumerate(items):\n    print(i, x)',
      blanks: [
        { id: 'i', answer: 'i' },
        { id: 'x', answer: 'x' },
      ],
      distractors: ['n', 'len', 'range', 'idx'],
      explanation: 'Any valid names work; pattern is for index, value in enumerate(...).',
    },
    {
      id: 'l14-int-2',
      type: 'matchPairs',
      stage: 'stretch',
      tags: ['sortedKey', 'comprehension'],
      prompt: 'Match pattern to tool.',
      leftItems: ['sorted(L, key=f)', 'list(map(f, L))', 'filter(pred, L)', '[f(x) for x in L]'],
      rightItems: ['Sort by key', 'Map function over L', 'Keep items where pred true', 'List comprehension'],
      pairs: [[0, 0], [1, 1], [2, 2], [3, 3]],
      explanation: 'Each idiom has a readable comprehension or builtin form.',
    },
  ],
  lesson15: [
    {
      id: 'l15-int-1',
      type: 'orderLines',
      stage: 'try',
      tags: ['jsonCsv'],
      prompt: 'Order lines to parse JSON from string s.',
      lines: ['import json', 'data = json.loads(s)', 'name = data["name"]'],
      correctOrder: [0, 1, 2],
      explanation: 'Import, parse string to Python object, then access keys.',
    },
    {
      id: 'l15-int-2',
      type: 'dragBlank',
      stage: 'stretch',
      tags: ['regex'],
      prompt: 'Complete regex import and search.',
      code: 'import {{re}}\nmatch = re.search(r"\\d+", text)',
      blanks: [{ id: 're', answer: 're' }],
      distractors: ['regex', 'rx', 'json'],
      explanation: 'Standard library module for regular expressions is re.',
    },
  ],
  lesson16: [
    {
      id: 'l16-int-1',
      type: 'orderLines',
      stage: 'try',
      tags: ['generators'],
      prompt: 'Order a simple generator function.',
      lines: ['    yield n', 'def gen(n):', '    yield n + 1'],
      correctOrder: [1, 0, 2],
      explanation: 'def header first, then yield statements in body.',
    },
    {
      id: 'l16-int-2',
      type: 'matchPairs',
      stage: 'stretch',
      tags: ['unpacking', 'generators'],
      prompt: 'Match syntax to meaning.',
      leftItems: ['*args', '**kwargs', 'yield', 'a, b = 1, 2'],
      rightItems: ['Positional varargs tuple', 'Keyword varargs dict', 'Produce generator value', 'Tuple unpacking assign'],
      pairs: [[0, 0], [1, 1], [2, 2], [3, 3]],
      explanation: 'Core modern intro syntax in one table.',
    },
  ],
};
