import type { Example } from './schema';

/** Supplemental stretch examples to reach ~240+ total course examples. */
export const LESSON_EXTRAS: Record<string, Example[]> = {
  lesson01: [
    {
      id: 'l1-extra-1',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['typeCoercion'],
      prompt: 'What is bool("")?',
      options: ['True', 'False', 'None', 'Error'],
      answerIndex: 1,
      explanation: 'Empty string is falsy; bool("") is False.',
    },
    {
      id: 'l1-extra-2',
      type: 'fillBlank',
      stage: 'try',
      tags: [],
      prompt: 'Read a name and greet: print(f"Hello, {____}!")',
      code: 'name = input("Name? ")\nprint(f"Hello, {____}!")',
      blankLabel: 'variable',
      options: ['name', 'namex', 'NAME', 'pass'],
          answerIndex: 0,
          explanation: 'Use the name variable inside the f-string braces.',
    },
  ],
  lesson02: [
    {
      id: 'l2-extra-1',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['truthiness'],
      prompt: 'What is `[] or [1]`?',
      options: ['[]', '[1]', 'True', 'False'],
      answerIndex: 1,
      explanation: 'or returns first truthy operand; [] is falsy so [1] is returned.',
    },
    {
      id: 'l2-extra-2',
      type: 'traceSteps',
      stage: 'see',
      tags: [],
      prompt: 'Trace chained comparison.',
      code: 'x = 5\nok = 1 < x < 10',
      steps: [
        { line: 1, vars: { x: '5' } },
        { line: 2, vars: { x: '5', ok: 'True' } },
      ],
      question: 'What is ok?',
      options: ['True', 'False', 'None', 'Error'],
          answerIndex: 0,
          explanation: '1 < 5 and 5 < 10 both hold.',
    },
  ],
  lesson03: [
    {
      id: 'l3-extra-1',
      type: 'fixTheLine',
      stage: 'debug',
      tags: ['truthiness'],
      prompt: 'Should print "big" for n=100 but prints nothing. Which line?',
      code: 'n = 100\nif n > 50\n    print("big")',
      lineOptions: [1, 2, 3],
      answerLine: 2,
      explanation: 'Missing colon after if condition.',
    },
    {
      id: 'l3-extra-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['truthiness'],
      prompt: 'Which is True?',
      options: ['bool(0)', 'bool("False")', 'bool([])', 'bool(None)'],
      answerIndex: 1,
      explanation: 'Non-empty strings are truthy, including "False".',
    },
  ],
  lesson04: [
    {
      id: 'l4-extra-1',
      type: 'codeChallenge',
      stage: 'build',
      tags: ['loopLogic'],
      prompt: 'Write repeat(s, n) that returns s repeated n times as a string.',
      starterCode: 'def repeat(s, n):\n    pass',
      tests: ['assert repeat("ab", 3) == "ababab"', 'assert repeat("x", 0) == ""'],
      explanation: 'Accumulate in a loop or use s * n.',
    },
    {
      id: 'l4-extra-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['offByOne'],
      prompt: 'len(range(5)) equals?',
      options: ['4', '5', '6', '0'],
      answerIndex: 1,
      explanation: 'range(5) yields 0,1,2,3,4 — five values.',
    },
  ],
  lesson05: [
    {
      id: 'l5-extra-1',
      type: 'codeChallenge',
      stage: 'build',
      tags: ['scope'],
      prompt: 'Write is_even(n) returning True if n is divisible by 2.',
      starterCode: 'def is_even(n):\n    pass',
      tests: ['assert is_even(4) == True', 'assert is_even(3) == False', 'assert is_even(0) == True'],
      explanation: 'Use modulo: n % 2 == 0.',
    },
    {
      id: 'l5-extra-2',
      type: 'fixTheLine',
      stage: 'debug',
      tags: ['mutation'],
      prompt: 'Default list arg grows forever. Which line is the trap?',
      code: 'def add_item(x, bucket=[]):\n    bucket.append(x)\n    return bucket',
      lineOptions: [1, 2, 3],
      answerLine: 1,
      explanation: 'Mutable default is created once at function definition.',
    },
  ],
  lesson06: [
    {
      id: 'l6-extra-1',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['mutation'],
      prompt: 'After s = "hi"; t = s; t = t + "!", what is s?',
      options: ['"hi!"', '"hi"', 'Error', 'None'],
      answerIndex: 1,
      explanation: 'Strings are immutable; s unchanged when t is rebound.',
    },
    {
      id: 'l6-extra-2',
      type: 'fillBlank',
      stage: 'try',
      tags: [],
      prompt: 'Slice first three chars of word.',
      code: 'word = "Python"\nfirst3 = word[____]',
      blankLabel: 'slice',
      options: [':3', '3:', ':2', '0:3'],
          answerIndex: 0,
      explanation: 'word[:3] or word[0:3] gives "Pyt".',
    },
  ],
  lesson07: [
    {
      id: 'l7-extra-1',
      type: 'traceSteps',
      stage: 'stretch',
      tags: ['aliasing', 'mutation'],
      prompt: 'Classic alias trap.',
      code: 'a = [1, 2]\nb = a\nb.append(3)',
      steps: [
        { line: 1, vars: { a: '[1, 2]' } },
        { line: 2, vars: { a: '[1, 2]', b: '[1, 2]' } },
        { line: 3, vars: { a: '[1, 2, 3]', b: '[1, 2, 3]' } },
      ],
      question: 'What is a after line 3?',
      options: ['[1, 2, 3]', '[1, 3, 3]', '[]', '{}'],
          answerIndex: 0,
          explanation: 'b and a reference the same list object.',
    },
    {
      id: 'l7-extra-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['mutation'],
      prompt: 'Which creates an independent copy of list L?',
      options: ['M = L', 'M = L[:]', 'M = L; M = []', 'M = L.append(0)'],
      answerIndex: 1,
      explanation: 'Slice copy L[:] is a shallow copy of L.',
    },
  ],
  lesson08: [
    {
      id: 'l8-extra-1',
      type: 'traceSteps',
      stage: 'see',
      tags: ['dictKeys'],
      prompt: 'Trace dict update.',
      code: 'd = {"a": 1}\nd["b"] = 2\nx = d.get("c", 0)',
      steps: [
        { line: 1, vars: { d: '{"a": 1}' } },
        { line: 2, vars: { d: '{"a": 1, "b": 2}' } },
        { line: 3, vars: { d: '{"a": 1, "b": 2}', x: '0' } },
      ],
      question: 'What is x?',
      options: ['0', '1', '-1', '2'],
          answerIndex: 0,
          explanation: 'get returns default when key missing.',
    },
    {
      id: 'l8-extra-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['dictKeys'],
      prompt: 'Can a list be a dict key?',
      options: ['Yes', 'No', 'Only if empty', 'Only in Python 2'],
      answerIndex: 1,
      explanation: 'Keys must be hashable; lists are not.',
    },
  ],
  lesson09: [
    {
      id: 'l9-extra-1',
      type: 'fillBlank',
      stage: 'try',
      tags: ['comprehension'],
      prompt: 'List comp for squares of evens in nums.',
      code: 'nums = [1,2,3,4]\nevens_sq = [____ for n in nums if n % 2 == 0]',
      blankLabel: 'expression',
      options: ['n * n', 'n * nx', 'N * N', 'pass'],
          answerIndex: 0,
      explanation: 'Square each n that passes the filter.',
    },
    {
      id: 'l9-extra-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['comprehension'],
      prompt: '[x for x in range(3)] equals?',
      options: ['[0,1,2]', '[1,2,3]', 'range(3)', '(0,1,2)'],
      answerIndex: 0,
      explanation: 'range(3) is 0, 1, 2.',
    },
  ],
  lesson10: [
    {
      id: 'l10-extra-1',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['exceptionType'],
      prompt: 'int("abc") raises?',
      options: ['ValueError', 'TypeError', 'KeyError', 'SyntaxError'],
      answerIndex: 0,
      explanation: 'Invalid literal for int() with base 10 → ValueError.',
    },
    {
      id: 'l10-extra-2',
      type: 'fixTheLine',
      stage: 'debug',
      tags: ['fileMode'],
      prompt: 'File never closes on error. Best fix line?',
      code: 'f = open("data.txt")\ndata = f.read()\nf.close()',
      lineOptions: [1, 2, 3],
      answerLine: 1,
      explanation: 'Use with open(...) as f: for automatic close.',
    },
  ],
  lesson11: [
    {
      id: 'l11-extra-1',
      type: 'traceSteps',
      stage: 'see',
      tags: ['oopAttrs'],
      prompt: 'Trace instance attribute.',
      code: 'class Dog:\n    def __init__(self, name):\n        self.name = name\n\nd = Dog("Rex")\nn = d.name',
      steps: [
        { line: 1, vars: {} },
        { line: 5, vars: { d: 'Dog("Rex")' } },
        { line: 6, vars: { d: 'Dog("Rex")', n: '"Rex"' } },
      ],
      question: 'What is n?',
      options: ['"Rex"', '"Re"', '"RexX"', '"REX"'],
          answerIndex: 0,
          explanation: 'self.name stores on the instance.',
    },
    {
      id: 'l11-extra-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['oopAttrs'],
      prompt: 'First parameter of instance method is conventionally?',
      options: ['self', 'cls', 'this', 'obj'],
      answerIndex: 0,
      explanation: 'Instance methods take self as first parameter.',
    },
  ],
  lesson12: [
    {
      id: 'l12-extra-1',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['recursion'],
      prompt: 'Recursive factorial missing base case causes?',
      options: ['RecursionError', 'SyntaxError', 'Returns 0', 'Infinite loop without error'],
      answerIndex: 0,
      explanation: 'Python limits recursion depth; unbounded recursion hits RecursionError.',
    },
    {
      id: 'l12-extra-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['loopLogic'],
      prompt: 'O(n²) means doubling input size roughly…',
      options: ['doubles runtime', 'quadruples runtime', 'same runtime', 'halves runtime'],
      answerIndex: 1,
      explanation: '(2n)² = 4n² — about 4× the work.',
    },
  ],
  lesson13: [
    {
      id: 'l13-extra-1',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['identity'],
      prompt: 'True is False is True — result?',
      options: ['False', 'True', 'None', 'Error'],
      answerIndex: 0,
      explanation: 'Chained comparisons: (True is False) and (False is True) → False and False → False.',
    },
    {
      id: 'l13-extra-2',
      type: 'traceSteps',
      stage: 'try',
      tags: ['shallowCopy', 'aliasing'],
      prompt: 'Copy vs alias on flat list.',
      code: 'a = [1, 2]\nb = list(a)\nb.append(3)',
      steps: [
        { line: 1, vars: { a: '[1, 2]' } },
        { line: 2, vars: { a: '[1, 2]', b: '[1, 2]' } },
        { line: 3, vars: { a: '[1, 2]', b: '[1, 2, 3]' } },
      ],
      question: 'What is a?',
      options: ['[1, 2]', '[1, 2, 3]', '[1]', 'Error'],
      answerIndex: 0,
      explanation: 'list(a) is shallow copy of flat list — append to b does not affect a.',
    },
  ],
  lesson14: [
    {
      id: 'l14-extra-1',
      type: 'multipleChoice',
      stage: 'try',
      tags: ['loopLogic'],
      prompt: 'Which skips to next iteration?',
      options: ['break', 'continue', 'pass', 'return'],
      answerIndex: 1,
      explanation: 'continue jumps to the next loop iteration.',
    },
    {
      id: 'l14-extra-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['moduleMain'],
      prompt: 'When you import a module, __name__ inside it is…',
      options: ['the module name', '"__main__"', 'always None', '"import"'],
      answerIndex: 0,
      explanation: 'Imported modules have __name__ set to their module path/name.',
    },
  ],
  lesson15: [
    {
      id: 'l15-extra-1',
      type: 'multipleChoice',
      stage: 'try',
      tags: ['regex'],
      prompt: 're.sub(r"\\d", "X", "a1b2") produces…',
      options: ['"aXbX"', '"a1b2"', '"XX"', 'Error'],
      answerIndex: 0,
      explanation: 'sub replaces each digit match with X.',
    },
    {
      id: 'l15-extra-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['jsonCsv'],
      prompt: 'True in JSON file becomes Python…',
      options: ['True (bool)', '1', '"true"', '1.0'],
      answerIndex: 0,
      explanation: 'JSON true/false → Python bool True/False.',
    },
  ],
  lesson16: [
    {
      id: 'l16-extra-1',
      type: 'multipleChoice',
      stage: 'try',
      tags: ['generators'],
      prompt: 'list(x * 2 for x in range(3)) equals…',
      options: ['[0, 2, 4]', '(0, 2, 4)', 'range(3)', 'Generator object'],
      answerIndex: 0,
      explanation: 'list() consumes the generator expression into a list.',
    },
    {
      id: 'l16-extra-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['unpacking'],
      prompt: 'dict(**{"a": 1, "b": 2}) in a call merges…',
      options: ['Keyword arguments', 'List elements', 'Global variables', 'File handles'],
      answerIndex: 0,
      explanation: '** unpacks dict into keyword args (Py 3.5+ call syntax).',
    },
  ],
};

const EXTRA_BATCH_B: Record<string, Example[]> = {
  lesson01: [
    { id: 'l1-extra-3', type: 'multipleChoice', stage: 'try', tags: [], prompt: 'Which is a valid variable name?', options: ['2x', 'my_var', 'class', 'for'], answerIndex: 1, explanation: 'Identifiers cannot start with a digit or be keywords.' },
    { id: 'l1-extra-4', type: 'traceSteps', stage: 'stretch', tags: ['typeCoercion'], prompt: 'Trace type of result.', code: 'a = 3\nb = 2\nr = a / b', steps: [{ line: 1, vars: { a: '3' } }, { line: 2, vars: { a: '3', b: '2' } }, { line: 3, vars: { a: '3', b: '2', r: '1.5' } }], question: 'Type of r?', options: ['float', 'int', 'str', 'bool'],
          answerIndex: 0,
          explanation: '/ produces float in Python 3.' },
  ],
  lesson02: [
    { id: 'l2-extra-3', type: 'fillBlank', stage: 'try', tags: [], prompt: 'Modulo operator for remainder.', code: 'rem = 17 ____ 5', blankLabel: 'operator', options: ['%', '//', '/', '**'],
          answerIndex: 0,
          explanation: '% is the remainder operator.' },
    { id: 'l2-extra-4', type: 'multipleChoice', stage: 'stretch', tags: [], prompt: 'not True and False equals?', options: ['True', 'False', 'None', 'Error'], answerIndex: 1, explanation: 'not True is False; False and False is False.' },
  ],
  lesson03: [
    { id: 'l3-extra-3', type: 'multipleChoice', stage: 'try', tags: ['truthiness'], prompt: 'elif runs when?', options: ['Always', 'Prior if/elif false', 'Only with else', 'Never'], answerIndex: 1, explanation: 'elif is checked only if previous branches failed.' },
    { id: 'l3-extra-4', type: 'traceSteps', stage: 'stretch', tags: ['truthiness'], prompt: 'Trace elif chain.', code: 'x = 5\nif x > 10:\n    s = "big"\nelif x > 3:\n    s = "mid"\nelse:\n    s = "small"', steps: [{ line: 1, vars: { x: '5' } }, { line: 4, vars: { x: '5', s: '"mid"' } }], question: 'What is s?', options: ['"mid"', '"mi"', '"midX"', '"MID"'],
          answerIndex: 0,
          explanation: '5 > 3 so elif branch runs.' },
  ],
  lesson04: [
    { id: 'l4-extra-3', type: 'fillBlank', stage: 'try', tags: ['loopLogic'], prompt: 'Infinite loop guard keyword.', code: 'while True:\n    if done:\n        ____', blankLabel: 'keyword', options: ['break', 'continue', 'return', 'pass'],
          answerIndex: 0,
          explanation: 'break exits the loop.' },
    { id: 'l4-extra-4', type: 'traceSteps', stage: 'stretch', tags: ['offByOne'], prompt: 'Count loop iterations.', code: 'c = 0\nfor i in range(2, 5):\n    c += 1', steps: [{ line: 1, vars: { c: '0' } }, { line: 2, vars: { c: '0', i: '2' } }, { line: 3, vars: { c: '1', i: '2' } }, { line: 2, vars: { c: '1', i: '3' } }, { line: 3, vars: { c: '2', i: '3' } }, { line: 2, vars: { c: '2', i: '4' } }, { line: 3, vars: { c: '3', i: '4' } }], question: 'What is c?', options: ['3', '4', '2', '6'],
          answerIndex: 0,
          explanation: 'i takes 2, 3, 4 — three iterations.' },
  ],
  lesson05: [
    { id: 'l5-extra-3', type: 'multipleChoice', stage: 'try', tags: ['scope'], prompt: 'Function without return gives?', options: ['0', 'False', 'None', 'Error'], answerIndex: 2, explanation: 'Implicit return is None.' },
    { id: 'l5-extra-4', type: 'fillBlank', stage: 'stretch', tags: ['scope'], prompt: 'Define a function.', code: '____ greet():\n    return "hi"', blankLabel: 'keyword', options: ['def', 'defx', 'DEF', 'pass'],
          answerIndex: 0,
          explanation: 'def starts a function definition.' },
  ],
  lesson06: [
    { id: 'l6-extra-3', type: 'multipleChoice', stage: 'try', tags: ['mutation'], prompt: '"abc".upper() returns?', options: ['abc', 'ABC', 'Abc', 'Error'], answerIndex: 1, explanation: 'upper() returns new uppercase string.' },
    { id: 'l6-extra-4', type: 'traceSteps', stage: 'stretch', tags: [], prompt: 'Slice step.', code: 's = "abcdef"\nt = s[1:5:2]', steps: [{ line: 1, vars: { s: '"abcdef"' } }, { line: 2, vars: { s: '"abcdef"', t: '"bdf"' } }], question: 'What is t?', options: ['"bdf"', '"bd"', '"bdfX"', '"BDF"'],
          answerIndex: 0,
          explanation: 'Indices 1,3,5 → b, d, f.' },
  ],
  lesson07: [
    { id: 'l7-extra-3', type: 'fillBlank', stage: 'try', tags: ['mutation'], prompt: 'Add to end of list.', code: 'L = [1, 2]\nL.____(3)', blankLabel: 'method', options: ['append', 'extend', 'insert', 'add'],
          answerIndex: 0,
          explanation: 'append adds one element to end.' },
    { id: 'l7-extra-4', type: 'fixTheLine', stage: 'debug', tags: ['aliasing'], prompt: 'Want copy but got alias. Which line?', code: 'a = [1, 2, 3]\nb = a\nb[0] = 99', lineOptions: [1, 2, 3], answerLine: 2, explanation: 'b = a aliases; use b = a[:] or list(a) to copy.' },
  ],
  lesson08: [
    { id: 'l8-extra-3', type: 'multipleChoice', stage: 'try', tags: ['dictKeys'], prompt: 'Set literal syntax?', options: ['{1, 2}', 'set(1, 2)', '[1, 2]', '{a: 1}'], answerIndex: 0, explanation: '{1, 2} is a set; {a:1} is dict.' },
    { id: 'l8-extra-4', type: 'fillBlank', stage: 'stretch', tags: ['dictKeys'], prompt: 'Get keys as list.', code: 'keys = list(d.____())', blankLabel: 'method', options: ['keys', 'keysx', 'KEYS', 'pass'],
          answerIndex: 0,
          explanation: 'd.keys() view converted to list.' },
  ],
  lesson09: [
    { id: 'l9-extra-3', type: 'multipleChoice', stage: 'try', tags: ['comprehension'], prompt: '{x: x*2 for x in [1,2]} type?', options: ['list', 'dict', 'set', 'tuple'], answerIndex: 1, explanation: 'Curly with key:value is dict comprehension.' },
    { id: 'l9-extra-4', type: 'traceSteps', stage: 'stretch', tags: ['scope'], prompt: 'Import math alias.', code: 'import math\nr = math.sqrt(9)', steps: [{ line: 1, vars: {} }, { line: 2, vars: { r: '3.0' } }], question: 'What is r?', options: ['3.0', '4', '2', '6'],
          answerIndex: 0,
          explanation: 'sqrt(9) is 3.0 as float.' },
  ],
  lesson10: [
    { id: 'l10-extra-3', type: 'fillBlank', stage: 'try', tags: ['exceptionType'], prompt: 'Catch any exception.', code: 'try:\n    risky()\n____ Exception as e:\n    pass', blankLabel: 'keyword', options: ['except', 'catch', 'try', 'finally'],
          answerIndex: 0,
          explanation: 'except handles exceptions.' },
    { id: 'l10-extra-4', type: 'multipleChoice', stage: 'stretch', tags: ['fileMode'], prompt: 'Write mode that creates/truncates?', options: ['"r"', '"w"', '"a"', '"rb"'], answerIndex: 1, explanation: '"w" truncates existing file or creates new.' },
  ],
  lesson11: [
    { id: 'l11-extra-3', type: 'multipleChoice', stage: 'try', tags: ['oopAttrs'], prompt: 'Class attribute shared by?', options: ['One instance', 'All instances', 'No instances', 'Only subclasses'], answerIndex: 1, explanation: 'Class attrs live on the class object.' },
    { id: 'l11-extra-4', type: 'fillBlank', stage: 'stretch', tags: ['oopAttrs'], prompt: 'Constructor method name.', code: 'def ____ (self, x):\n    self.x = x', blankLabel: 'method', options: ['__init__', '__init__x', '__INIT__', 'pass'],
          answerIndex: 0,
          explanation: '__init__ initializes new instances.' },
  ],
  lesson12: [
    { id: 'l12-extra-3', type: 'traceSteps', stage: 'see', tags: ['recursion'], prompt: 'Simple countdown recursion trace.', code: 'def cd(n):\n    if n == 0:\n        return 0\n    return cd(n - 1) + 1\n\nx = cd(3)', steps: [{ line: 1, vars: {} }, { line: 6, vars: {} }, { line: 6, vars: { x: '3' } }], question: 'What is x?', options: ['3', '4', '2', '6'],
          answerIndex: 0,
          explanation: 'Each call adds 1 until n hits 0.' },
    { id: 'l12-extra-4', type: 'multipleChoice', stage: 'stretch', tags: ['loopLogic'], prompt: 'Linear search on n items is O(?)', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], answerIndex: 2, explanation: 'Worst case scans all n elements.' },
  ],
  lesson13: [
    { id: 'l13-extra-3', type: 'multipleChoice', stage: 'try', tags: ['traceback'], prompt: 'KeyError in traceback usually means…', options: ['Missing dict key', 'Bad index', 'Wrong type', 'File not found'], answerIndex: 0, explanation: 'KeyError: key not present in dict (or similar mapping).' },
    { id: 'l13-extra-4', type: 'multipleChoice', stage: 'stretch', tags: ['assertLogic'], prompt: 'Running python -O (optimize) may…', options: ['Remove assert statements', 'Remove all errors', 'Disable imports', 'Make code slower'], answerIndex: 0, explanation: '-O strips assert bytecode in optimized mode — do not rely on assert for production security.' },
  ],
  lesson14: [
    { id: 'l14-extra-3', type: 'traceSteps', stage: 'stretch', tags: ['sortedKey'], prompt: 'Sort tuples by second element.', code: 'pairs = [("b", 2), ("a", 3)]\nout = sorted(pairs, key=lambda p: p[1])', steps: [{ line: 1, vars: { pairs: '[("b",2),("a",3)]' } }, { line: 2, vars: { pairs: '[("b",2),("a",3)]', out: '[("b",2),("a",3)]' } }], question: 'What is out?', options: ['[("b", 2), ("a", 3)]', '[("a", 3), ("b", 2)]', '[("a", 2), ("b", 3)]', '[]'], answerIndex: 0, explanation: 'Values 2 then 3 — already ascending by key p[1].' },
    { id: 'l14-extra-4', type: 'multipleChoice', stage: 'try', tags: ['dictKeys'], prompt: 'list(d.values()) returns…', options: ['All values as a list', 'All keys', 'Tuples of pairs', 'A set only'], answerIndex: 0, explanation: '.values() view wrapped in list() gives value list.' },
  ],
  lesson15: [
    { id: 'l15-extra-3', type: 'multipleChoice', stage: 'try', tags: ['jsonCsv'], prompt: 'json.dump(obj, f) writes to…', options: ['File object f', 'String only', 'CSV file only', 'Regex pattern'], answerIndex: 0, explanation: 'dump serializes to file-like; dumps returns string.' },
    { id: 'l15-extra-4', type: 'multipleChoice', stage: 'stretch', tags: ['regex'], prompt: 'Pattern r"[aeiou]" matches…', options: ['One vowel character', 'Whole word only', 'End of string', 'Any digit'], answerIndex: 0, explanation: 'Character class [aeiou] matches single vowel.' },
  ],
  lesson16: [
    { id: 'l16-extra-3', type: 'multipleChoice', stage: 'try', tags: ['typeHints'], prompt: 'Type hints at runtime are…', options: ['Ignored by default (not enforced)', 'Always enforced', 'Syntax errors if wrong', 'Only in Python 2'], answerIndex: 0, explanation: 'Annotations stored in __annotations__; use mypy for static checking.' },
    { id: 'l16-extra-4', type: 'multipleChoice', stage: 'stretch', tags: ['dictKeys'], prompt: 'Counter.most_common(1) on "aab" returns…', options: ['[("a", 2)]', '[("b", 1)]', '{"a": 2}', '2'], answerIndex: 0, explanation: 'most_common(n) returns n largest (element, count) pairs as list of tuples.' },
  ],
};

export function mergeLessonExtras<T extends { id: string; concepts: { examples: Example[] }[] }>(
  lesson: T,
): T {
  const extras = [
    ...(LESSON_EXTRAS[lesson.id] ?? []),
    ...(EXTRA_BATCH_B[lesson.id] ?? []),
  ];
  if (!extras?.length) return lesson;
  const concepts = [...lesson.concepts];
  const last = concepts[concepts.length - 1];
  if (last) {
    concepts[concepts.length - 1] = {
      ...last,
      examples: [...last.examples, ...extras],
    };
  }
  return { ...lesson, concepts };
}
