import type { Lesson } from '../schema';

export const lesson05: Lesson = {
  id: 'lesson05',
  title: 'Functions',
  subtitle: 'Defining, calling, scope, return, and default-arg traps',
  objectives: [
    'Define functions with def and call them with arguments',
    'Distinguish local vs global scope',
    'Use return values and predict None when omitted',
    'Avoid mutable default argument bugs',
  ],
  concepts: [
    {
      id: 'l5-c1',
      title: 'Defining & calling',
      objective: 'Write def name(params): and invoke with positional args.',
      examples: [
        {
          id: 'l5-c1-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['scope'],
          prompt: 'Step through a function call.',
          code: 'def double(x):\n    return x * 2\n\na = 3\nb = double(a)',
          steps: [
            { line: 1, vars: {} },
            { line: 4, vars: { a: '3' } },
            { line: 5, vars: { a: '3', x: '3' } },
            { line: 2, vars: { a: '3', x: '3' } },
            { line: 5, vars: { a: '3', b: '6' } },
          ],
          question: 'What is b after line 5?',
          options: ['6', '7', '5', '12'],
          answerIndex: 0,
          explanation: 'double(3) returns 3*2 = 6, assigned to b.',
        },
        {
          id: 'l5-c1-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['scope'],
          prompt: 'What keyword starts a function definition?',
          options: ['function', 'def', 'fn', 'define'],
          answerIndex: 1,
          explanation: 'Python uses def name(params): to define functions.',
        },
        {
          id: 'l5-c1-e3',
          type: 'fillBlank',
          stage: 'stretch',
          tags: ['scope'],
          prompt: 'Complete the function to return the larger of two numbers.',
          code: 'def bigger(a, b):\n    if a >= b:\n        ____\n    return b',
          blankLabel: 'return statement',
          options: ['return a', 'return ax', 'a', 'RETURN A'],
          answerIndex: 0,
          explanation: 'When a >= b, return a; otherwise fall through to return b.',
        },
        {
          id: 'l5-c1-e4',
          type: 'codeChallenge',
          stage: 'build',
          tags: ['scope'],
          prompt: 'Write square(x) that returns x * x.',
          starterCode: 'def square(x):\n    pass',
          tests: ['assert square(3) == 9', 'assert square(-2) == 4', 'assert square(0) == 0'],
          explanation: 'A one-line return of x * x is enough.',
        },
      ],
    },
    {
      id: 'l5-c2',
      title: 'Variable scope',
      objective: 'Know which names are local inside a function vs global outside.',
      miniNote: 'Assignment inside a function creates a local name unless declared global.',
      examples: [
        {
          id: 'l5-c2-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['scope'],
          prompt: 'Trace local vs global names.',
          code: 'x = 10\ndef f():\n    x = 99\n    return x\n\ny = f()\nz = x',
          steps: [
            { line: 1, vars: { x: '10' } },
            { line: 2, vars: { x: '10' } },
            { line: 5, vars: { x: '10' } },
            { line: 3, vars: { x: '10' } },
            { line: 4, vars: { x: '10' } },
            { line: 5, vars: { x: '10', y: '99' } },
            { line: 6, vars: { x: '10', y: '99', z: '10' } },
          ],
          question: 'What are y and z?',
          options: ['y=99, z=10', 'y=99, z=10x', 'Y=99, Z=10', 'pass'],
          answerIndex: 0,
          explanation: 'f\'s x=99 is local; global x stays 10, so z = 10.',
        },
        {
          id: 'l5-c2-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['scope'],
          prompt: 'Can a function read a global variable without global keyword?',
          options: ['Never', 'Yes, if not assigning to it', 'Only for ints', 'Only inside loops'],
          answerIndex: 1,
          explanation: 'Reading globals works; assignment makes a new local unless global is declared.',
        },
        {
          id: 'l5-c2-e3',
          type: 'fixTheLine',
          stage: 'stretch',
          tags: ['scope'],
          prompt: 'UnboundLocalError: local variable "count" referenced before assignment. Which line causes it?',
          code: 'count = 0\ndef inc():\n    print(count)\n    count = count + 1',
          lineOptions: [2, 3, 4],
          answerLine: 4,
          explanation: 'count = count + 1 makes count local for the whole function, so print(count) fails.',
        },
      ],
    },
    {
      id: 'l5-c3',
      title: 'Return values',
      objective: 'Use return to send a value back; functions without return give None.',
      examples: [
        {
          id: 'l5-c3-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['scope'],
          prompt: 'Trace return and implicit None.',
          code: 'def greet(name):\n    print("Hi", name)\n\ndef add(a, b):\n    return a + b\n\nr1 = greet("Ada")\nr2 = add(2, 3)',
          steps: [
            { line: 1, vars: {} },
            { line: 5, vars: {} },
            { line: 6, vars: {} },
            { line: 2, vars: {} },
            { line: 6, vars: { r1: 'None' } },
            { line: 4, vars: {} },
            { line: 7, vars: { r1: 'None', r2: '5' } },
          ],
          question: 'What are r1 and r2?',
          options: ['r1=None, r2=5', 'r1=None, r2=5x', 'R1=NONE, R2=5', 'pass'],
          answerIndex: 0,
          explanation: 'greet prints but returns nothing (None). add returns 5.',
        },
        {
          id: 'l5-c3-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['scope'],
          prompt: 'What does a bare `return` (no value) return?',
          options: ['0', 'False', 'None', 'Error'],
          answerIndex: 2,
          explanation: 'return with no expression returns None.',
        },
        {
          id: 'l5-c3-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['scope'],
          prompt: 'def f(): return 1; return 2 — what does f() return?',
          options: ['1', '2', '1 and 2', 'None'],
          answerIndex: 0,
          explanation: 'First return exits immediately; second return is unreachable.',
        },
      ],
    },
    {
      id: 'l5-c4',
      title: 'Default argument trap',
      objective: 'Never use mutable defaults like [] or {} — they persist across calls.',
      miniNote: 'Default values are evaluated once at def time, not per call.',
      examples: [
        {
          id: 'l5-c4-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['mutation', 'scope'],
          prompt: 'Watch the mutable default list grow.',
          code: 'def add_item(x, items=[]):\n    items.append(x)\n    return items\n\na = add_item(1)\nb = add_item(2)',
          steps: [
            { line: 1, vars: {} },
            { line: 5, vars: {} },
            { line: 2, vars: { items: '[1]' } },
            { line: 3, vars: { items: '[1]' } },
            { line: 5, vars: { a: '[1]' } },
            { line: 6, vars: { a: '[1]' } },
            { line: 2, vars: { items: '[1, 2]' } },
            { line: 3, vars: { items: '[1, 2]' } },
            { line: 6, vars: { a: '[1]', b: '[1, 2]' } },
          ],
          question: 'What is b?',
          options: ['[1, 2]', '[1, 3]', '[]', '{}'],
          answerIndex: 0,
          explanation: 'Same default list is reused; second call appends to the list from the first call.',
        },
        {
          id: 'l5-c4-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['mutation', 'scope'],
          prompt: 'Safe pattern for optional list parameter?',
          options: [
            'def f(items=[]):',
            'def f(items=None): items = items or []',
            'def f(items=None): if items is None: items = []',
            'Both B and C work; C is preferred',
          ],
          answerIndex: 3,
          explanation: 'Use None as default, then create a fresh list inside. `or []` fails if caller passes [].',
        },
        {
          id: 'l5-c4-e3',
          type: 'fixTheLine',
          stage: 'stretch',
          tags: ['mutation', 'scope'],
          prompt: 'Fix the mutable default: which line should change?',
          code: 'def collect(val, bucket={}):\n    bucket[val] = True\n    return bucket',
          lineOptions: [1, 2, 3],
          answerLine: 1,
          explanation: 'Change to bucket=None and create {} inside the function body each call.',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l5-check-1',
      type: 'traceSteps',
      stage: 'stretch',
      tags: ['scope'],
      prompt: 'Trace nested function call.',
      code: 'def sq(n):\n    return n * n\n\ndef sum_sq(a, b):\n    return sq(a) + sq(b)\n\nresult = sum_sq(3, 4)',
      steps: [
        { line: 5, vars: {} },
        { line: 2, vars: { n: '3' } },
        { line: 5, vars: {} },
        { line: 2, vars: { n: '4' } },
        { line: 5, vars: { result: '25' } },
      ],
      question: 'What is result?',
      options: ['25', '26', '24', '50'],
          answerIndex: 0,
          explanation: 'sq(3)=9, sq(4)=16, sum 9+16=25.',
    },
    {
      id: 'l5-check-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['scope'],
      prompt: 'def f(x, y=10): — how many arguments must the caller supply at minimum?',
      options: ['0', '1', '2', '3'],
      answerIndex: 1,
      explanation: 'x is required; y has a default.',
    },
    {
      id: 'l5-check-3',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['mutation', 'scope'],
      prompt: 'Two calls to def f(a=[]): f.append(1); return a — second call returns?',
      options: ['[1]', '[1, 1]', '[]', 'Error'],
      answerIndex: 1,
      explanation: 'Same list object accumulates: [1] then [1, 1].',
    },
    {
      id: 'l5-check-4',
      type: 'fillBlank',
      stage: 'stretch',
      tags: ['scope'],
      prompt: 'Fill in to return the absolute value of n (assume n is int).',
      code: 'def abs_val(n):\n    if n < 0:\n        return ____\n    return n',
      blankLabel: 'expression',
      options: ['-n', '-nx', '-N', 'pass'],
          answerIndex: 0,
      explanation: 'Negating a negative yields its positive counterpart.',
    },
  ],
};
