import type { Lesson } from '../schema';

export const lesson01: Lesson = {
  id: 'lesson01',
  title: 'Foundations',
  subtitle: 'Syntax, variables, types, and I/O',
  objectives: [
    'Assign values to variables and predict their types',
    'Use print and input for basic programs',
    'Convert between int, float, and str safely',
    'Format output with f-strings',
  ],
  concepts: [
    {
      id: 'l1-c1',
      title: 'Variables & types',
      objective: 'Assign values and recognize int, float, str, and bool.',
      miniNote: 'Python infers type from the value you assign. Names are case-sensitive.',
      examples: [
        {
          id: 'l1-c1-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['typeCoercion'],
          prompt: 'Step through and watch how variables bind to values.',
          code: 'x = 10\ny = 3.5\nname = "Ada"\nactive = True',
          steps: [
            { line: 1, vars: { x: '10' } },
            { line: 2, vars: { x: '10', y: '3.5' } },
            { line: 3, vars: { x: '10', y: '3.5', name: '"Ada"' } },
            { line: 4, vars: { x: '10', y: '3.5', name: '"Ada"', active: 'True' } },
          ],
          question: 'What is the type of y after all lines run?',
          options: ['float', 'int', 'str', 'bool'],
          answerIndex: 0,
          explanation: '3.5 is a floating-point literal, so y is a float.',
        },
        {
          id: 'l1-c1-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['typeCoercion'],
          prompt: 'What does this expression evaluate to?',
          options: ['14', '13', '"13"', 'Error'],
          answerIndex: 1,
          explanation: '10 + 3 is numeric addition → 13.',
          trapNote: 'Mixing str and int without conversion causes TypeError.',
        },
        {
          id: 'l1-c1-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['typeCoercion'],
          prompt: 'What is the result of type(10 / 2) in Python 3?',
          options: ['int', 'float', 'str', 'bool'],
          answerIndex: 1,
          explanation: 'The / operator always returns float in Python 3, even when evenly divisible.',
          trapNote: 'Use // for integer division.',
        },
      ],
    },
    {
      id: 'l1-c2',
      title: 'print & output',
      objective: 'Predict printed output including sep and end.',
      examples: [
        {
          id: 'l1-c2-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: [],
          prompt: 'Step through each print call.',
          code: 'a = 5\nb = 2\nprint(a + b)\nprint("sum:", a + b)',
          steps: [
            { line: 1, vars: { a: '5' } },
            { line: 2, vars: { a: '5', b: '2' } },
            { line: 3, vars: { a: '5', b: '2' } },
            { line: 4, vars: { a: '5', b: '2' } },
          ],
          question: 'What is the first line of output?',
          options: ['7', '8', '6', '14'],
          answerIndex: 0,
          explanation: 'print(a + b) prints the sum 5 + 2 = 7.',
        },
        {
          id: 'l1-c2-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: [],
          prompt: 'What does print("hi", "there", sep="-") output?',
          options: ['hi there', 'hi-there', 'hithere', 'hi\\nthere'],
          answerIndex: 1,
          explanation: 'sep="-" joins multiple arguments with a hyphen.',
        },
        {
          id: 'l1-c2-e3',
          type: 'fillBlank',
          stage: 'try',
          tags: [],
          prompt: 'Complete the print so it outputs exactly: Score: 42',
          code: 'score = 42\nprint(____)',
          blankLabel: 'print argument',
          options: ['f"Score: {score}"', '"Score: 42"', 'score', '"Score:", score'],
          answerIndex: 0,
          explanation: 'An f-string embeds variable values inside braces.',
        },
      ],
    },
    {
      id: 'l1-c3',
      title: 'Type conversion',
      objective: 'Use int(), float(), and str() and predict results.',
      miniNote: 'int("3.5") raises ValueError — convert to float first.',
      examples: [
        {
          id: 'l1-c3-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['typeCoercion'],
          prompt: 'Watch conversions change types.',
          code: 's = "42"\nn = int(s)\nf = float(n)\ns2 = str(f)',
          steps: [
            { line: 1, vars: { s: '"42"' } },
            { line: 2, vars: { s: '"42"', n: '42' } },
            { line: 3, vars: { s: '"42"', n: '42', f: '42.0' } },
            { line: 4, vars: { s: '"42"', n: '42', f: '42.0', s2: '"42.0"' } },
          ],
          question: 'What is s2 after execution?',
          options: ['"42.0"', '"42."', '"42.0X"', '""'],
          answerIndex: 0,
          explanation: 'str(42.0) produces the string "42.0", not "42".',
        },
        {
          id: 'l1-c3-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['typeCoercion'],
          prompt: 'What does int(3.9) return?',
          options: ['3', '4', '3.9', 'Error'],
          answerIndex: 0,
          explanation: 'int() truncates toward zero; it does not round.',
        },
        {
          id: 'l1-c3-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['typeCoercion'],
          prompt: 'Which call will raise an error?',
          options: ['int("10")', 'float("3.14")', 'int("3.14")', 'str(7)'],
          answerIndex: 2,
          explanation: 'int() cannot parse a string containing a decimal point directly.',
        },
      ],
    },
    {
      id: 'l1-c4',
      title: 'f-strings & formatting',
      objective: 'Build formatted strings with expressions inside {}.',
      examples: [
        {
          id: 'l1-c4-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: [],
          prompt: 'Trace the f-string evaluation.',
          code: 'x = 7\ny = 3\nmsg = f"{x} + {y} = {x + y}"',
          steps: [
            { line: 1, vars: { x: '7' } },
            { line: 2, vars: { x: '7', y: '3' } },
            { line: 3, vars: { x: '7', y: '3', msg: '"7 + 3 = 10"' } },
          ],
          question: 'What is msg?',
          options: ['"7 + 3 = 10"', '"7 + 3 = 1"', '"7 + 3 = 10X"', '""'],
          answerIndex: 0,
          explanation: 'Expressions inside {} are evaluated when the f-string is created.',
        },
        {
          id: 'l1-c4-e2',
          type: 'fillBlank',
          stage: 'try',
          tags: [],
          prompt: 'Fill in the f-string to show two decimal places for pi ≈ 3.14159',
          code: 'pi = 3.14159\nprint(f"{pi:____}")',
          blankLabel: 'format spec',
          options: ['.2f', '.0f', ':.2f', '2f'],
          answerIndex: 0,
          explanation: ':.2f formats a float with 2 digits after the decimal.',
        },
        {
          id: 'l1-c4-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: [],
          prompt: 'What does f"{2 + 3}" produce?',
          options: ['"2 + 3"', '"5"', '5', 'Error'],
          answerIndex: 1,
          explanation: 'The expression 2+3 is evaluated first; result is converted to string.',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l1-check-1',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['typeCoercion'],
      prompt: 'What is type(10 // 3)?',
      options: ['int', 'float', 'str', 'bool'],
      answerIndex: 0,
      explanation: '// is floor division and returns int when operands are int.',
    },
    {
      id: 'l1-check-2',
      type: 'traceSteps',
      stage: 'stretch',
      tags: ['typeCoercion'],
      prompt: 'Final check: trace this snippet.',
      code: 'a = "5"\nb = 2\nprint(int(a) * b)',
      steps: [
        { line: 1, vars: { a: '"5"' } },
        { line: 2, vars: { a: '"5"', b: '2' } },
        { line: 3, vars: { a: '"5"', b: '2' } },
      ],
      question: 'What is printed?',
      options: ['10', '11', '9', '20'],
          answerIndex: 0,
          explanation: 'int("5") is 5, times 2 is 10.',
    },
    {
      id: 'l1-check-3',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['truthiness'],
      prompt: 'Which value is falsy in Python?',
      options: ['0', '1', '"0"', '[0]'],
      answerIndex: 0,
      explanation: '0, empty containers, None, and False are falsy. Non-empty strings are truthy.',
    },
    {
      id: 'l1-check-4',
      type: 'fillBlank',
      stage: 'stretch',
      tags: [],
      prompt: 'Complete to convert user input to an integer.',
      code: 'age = ____(input("Age? "))',
      blankLabel: 'conversion',
      options: ['int', 'float', 'str', 'bool'],
          answerIndex: 0,
          explanation: 'input() always returns str; int() parses it.',
    },
  ],
};
