import type { Lesson } from '../schema';

export const lesson15: Lesson = {
  id: 'lesson15',
  title: 'Regex, JSON & CSV',
  subtitle: 'Text patterns and structured data formats every intro course covers',
  objectives: [
    'Match text with re.search and re.findall using basic patterns',
    'Parse and serialize JSON with json.loads and json.dumps',
    'Read row-oriented CSV data with the csv module',
    'Know when each format fits (config vs tables vs plain text)',
  ],
  concepts: [
    {
      id: 'l15-c1',
      title: 'Regular expressions (re)',
      objective: 'Use import re; search for patterns with ., \\d, +, and groups.',
      miniNote: 'Raw strings r"..." avoid double-escaping backslashes. re.search finds first match; re.findall returns all.',
      examples: [
        {
          id: 'l15-c1-e1',
          type: 'multipleChoice',
          stage: 'see',
          tags: ['regex'],
          prompt: 'What does re.search(r"\\d+", "Room 42") return?',
          options: [
            'Match object for "42"',
            'The list ["42"]',
            'True',
            'Index 5',
          ],
          answerIndex: 0,
          explanation: 'search returns a Match object (or None). \\d+ matches one or more digits.',
        },
        {
          id: 'l15-c1-e2',
          type: 'multipleChoice',
          stage: 'see',
          tags: ['regex'],
          prompt: 're.findall(r"\\w+", "hi there") equals?',
          options: ['["hi", "there"]', '["hi there"]', '["h", "i", "t", ...]', 'None'],
          answerIndex: 0,
          explanation: '\\w+ matches word characters; findall returns all non-overlapping matches as strings.',
        },
        {
          id: 'l15-c1-e3',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['regex'],
          prompt: 'Pattern r"^A" on string "ABC" means…',
          options: [
            'A at start of string',
            'A anywhere in string',
            'A at end of string',
            'Literal caret then A',
          ],
          answerIndex: 0,
          explanation: '^ anchors to start; $ anchors to end (common intro patterns).',
        },
        {
          id: 'l15-c1-e4',
          type: 'matchPairs',
          stage: 'stretch',
          tags: ['regex'],
          prompt: 'Match regex symbol to meaning.',
          leftItems: ['.', '\\d', '+', '[]'],
          rightItems: ['Any one character', 'One digit', 'One or more of prior', 'Character class'],
          pairs: [[0, 0], [1, 1], [2, 2], [3, 3]],
          explanation: 'Intro subset: . any char; \\d digit; + repetition; [] set of chars.',
        },
      ],
    },
    {
      id: 'l15-c2',
      title: 'JSON',
      objective: 'Exchange data with json.loads (str→Python) and json.dumps (Python→str).',
      miniNote: 'JSON objects become dicts; arrays become lists. Keys in JSON are always strings.',
      examples: [
        {
          id: 'l15-c2-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['jsonCsv'],
          prompt: 'Trace json.loads on a simple object.',
          code: 'import json\ns = \'{"name": "Ada", "score": 95}\'\ndata = json.loads(s)\nn = data["name"]',
          steps: [
            { line: 1, vars: {} },
            { line: 2, vars: { s: '\'{"name": "Ada", "score": 95}\'' } },
            { line: 3, vars: { s: '...', data: '{"name": "Ada", "score": 95}' } },
            { line: 4, vars: { data: '{"name": "Ada", "score": 95}', n: '"Ada"' } },
          ],
          question: 'What is n?',
          options: ['"Ada"', 'Ada', '95', 'Error'],
          answerIndex: 0,
          explanation: 'JSON strings become Python str values — n is the string "Ada".',
        },
        {
          id: 'l15-c2-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['jsonCsv'],
          prompt: 'json.dumps([1, 2, 3]) produces…',
          options: ['\'[1, 2, 3]\'', '[1, 2, 3]', 'A Python list', 'Error always'],
          answerIndex: 0,
          explanation: 'dumps serializes to a JSON-formatted string (quotes around the whole array).',
        },
        {
          id: 'l15-c2-e3',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['jsonCsv'],
          prompt: 'Which Python type CANNOT be JSON-serialized by default?',
          options: ['dict', 'list', 'set', 'str'],
          answerIndex: 2,
          explanation: 'JSON has objects, arrays, strings, numbers, bool, null — not sets.',
        },
        {
          id: 'l15-c2-e4',
          type: 'fixTheLine',
          stage: 'debug',
          tags: ['jsonCsv'],
          prompt: 'json.loads fails on line 2. Which line has invalid JSON?',
          code: 'import json\ns = "{name: Ada}"\ndata = json.loads(s)',
          lineOptions: [1, 2, 3],
          answerLine: 2,
          explanation: 'JSON keys and string values must use double quotes: {"name": "Ada"}.',
        },
      ],
    },
    {
      id: 'l15-c3',
      title: 'CSV files',
      objective: 'Read comma-separated rows with csv.reader and csv.DictReader.',
      miniNote: 'CSV is row/column tables. Use newline="" with open() when writing CSV on Windows (intro note).',
      examples: [
        {
          id: 'l15-c3-e1',
          type: 'multipleChoice',
          stage: 'see',
          tags: ['jsonCsv'],
          prompt: 'CSV is best for…',
          options: [
            'Spreadsheet-like tabular data',
            'Nested hierarchical documents',
            'Binary images',
            'Python source code only',
          ],
          answerIndex: 0,
          explanation: 'CSV = rows of fields; great for exports from Excel/Sheets.',
        },
        {
          id: 'l15-c3-e2',
          type: 'traceSteps',
          stage: 'see',
          tags: ['jsonCsv'],
          prompt: 'Trace csv.reader on two rows.',
          code: 'import csv\nfrom io import StringIO\ntext = "a,b\\nc,d"\nrows = list(csv.reader(StringIO(text)))',
          steps: [
            { line: 1, vars: {} },
            { line: 4, vars: { text: '"a,b\\nc,d"' } },
            { line: 5, vars: { rows: '[["a", "b"], ["c", "d"]]' } },
          ],
          question: 'What is rows[1]?',
          options: ['["c", "d"]', '["a", "b"]', '"c,d"', 'Error'],
          answerIndex: 0,
          explanation: 'Each row is a list of field strings; index 1 is second row.',
        },
        {
          id: 'l15-c3-e3',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['jsonCsv'],
          prompt: 'csv.DictReader uses first row as…',
          options: ['Column headers / field names', 'Data to discard', 'File comment', 'JSON keys'],
          answerIndex: 0,
          explanation: 'Each subsequent row becomes a dict mapping header→cell value.',
        },
        {
          id: 'l15-c3-e4',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['jsonCsv', 'fileMode'],
          prompt: 'Typical read pattern for a CSV file named data.csv?',
          options: [
            'with open("data.csv") as f: csv.reader(f)',
            'json.loads("data.csv")',
            're.findall("data.csv")',
            'data.csv.split(".")',
          ],
          answerIndex: 0,
          explanation: 'Open text file, pass file object to csv.reader or DictReader.',
        },
      ],
    },
    {
      id: 'l15-c4',
      title: 'Choosing a format',
      objective: 'Pick JSON vs CSV vs plain text for a given job.',
      examples: [
        {
          id: 'l15-c4-e1',
          type: 'matchPairs',
          stage: 'try',
          tags: ['jsonCsv', 'regex'],
          prompt: 'Match task to tool.',
          leftItems: [
            'API response with nested fields',
            'Export of spreadsheet rows',
            'Find all emails in log text',
            'Config file with nested keys',
          ],
          rightItems: ['JSON', 'CSV', 'regex (re)', 'JSON or YAML (intro: JSON)'],
          pairs: [[0, 0], [1, 1], [2, 2], [3, 3]],
          explanation: 'Structured API/config → JSON; tables → CSV; pattern in text → regex.',
        },
        {
          id: 'l15-c4-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['jsonCsv'],
          prompt: 'After json.loads, numbers in JSON become Python…',
          options: ['int or float', 'str always', 'Decimal always', 'bool only'],
          answerIndex: 0,
          explanation: 'JSON numbers map to int if whole, else float (no separate JSON int type).',
        },
        {
          id: 'l15-c4-e3',
          type: 'orderLines',
          stage: 'stretch',
          tags: ['jsonCsv', 'fileMode'],
          prompt: 'Order steps to load JSON from a file.',
          lines: [
            'import json',
            'with open("data.json") as f:',
            '    text = f.read()',
            'obj = json.loads(text)',
          ],
          correctOrder: [0, 1, 2, 3],
          explanation: 'Read file to string, then parse JSON — or use json.load(f) directly on file object.',
        },
        {
          id: 'l15-c4-e4',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['regex'],
          prompt: 'Why use raw string r"\\n" in a regex pattern?',
          options: [
            'So Python does not treat \\ as escape before passing to regex engine',
            'To match a literal letter r',
            'Required for JSON only',
            'Makes pattern case-insensitive',
          ],
          answerIndex: 0,
          explanation: 'Without r"...", \\n is newline; regex often needs literal backslash sequences.',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l15-check-1',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['regex'],
      prompt: 'Lesson check: re.search returns None when…',
      options: ['No match found', 'Empty string input', 'Pattern is invalid always', 'Always after findall'],
      answerIndex: 0,
      explanation: 'search returns None if pattern not found — check before .group().',
    },
    {
      id: 'l15-check-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['jsonCsv'],
      prompt: 'Lesson check: json.load(f) vs json.loads(s)?',
      options: ['load reads file-like; loads parses string', 'They are identical', 'loads reads files', 'load returns strings only'],
      answerIndex: 0,
      explanation: 'load(f) for file objects; loads(s) for str already in memory.',
    },
    {
      id: 'l15-check-3',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['jsonCsv'],
      prompt: 'Lesson check: CSV field "42" read via csv.reader is…',
      options: ['str "42"', 'int 42', 'float 42.0', 'bool'],
      answerIndex: 0,
      explanation: 'CSV cells are strings — convert with int() if needed.',
    },
    {
      id: 'l15-check-4',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['jsonCsv'],
      prompt: 'Lesson check: null in JSON becomes Python…',
      options: ['None', '0', '""', 'False'],
      answerIndex: 0,
      explanation: 'JSON null maps to Python None.',
    },
  ],
};
