import type { Lesson } from '../schema';

export const lesson10: Lesson = {
  id: 'lesson10',
  title: 'Files & Exceptions',
  subtitle: 'Reading/writing files, try/except, and handling errors',
  objectives: [
    'Open files with with and choose correct modes',
    'Read and write text file contents safely',
    'Handle exceptions with try/except/else/finally',
    'Recognize common exception types and raise errors',
  ],
  concepts: [
    {
      id: 'l10-c1',
      title: 'Opening & reading files',
      objective: 'Use open(), read(), readlines(), and the with statement.',
      miniNote: 'Always prefer with open(...) — it closes the file even if an error occurs.',
      examples: [
        {
          id: 'l10-c1-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['fileMode'],
          prompt: 'Trace reading a file with read().',
          code: 'with open("data.txt") as f:\n    text = f.read()\nlines = text.split("\\n")',
          steps: [
            { line: 1, vars: {} },
            { line: 2, vars: { text: '"hello\\nworld"' } },
            { line: 3, vars: { text: '"hello\\nworld"', lines: '["hello", "world"]' } },
          ],
          question: 'What is len(lines)?',
          options: ['2', '3', '1', '4'],
          answerIndex: 0,
          explanation: 'split("\\n") breaks on newline into two strings.',
        },
        {
          id: 'l10-c1-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['fileMode'],
          prompt: 'Default mode for open("file.txt")?',
          options: ['"r" (read text)', '"w" (write)', '"rb" (read bytes)', '"a" (append)'],
          answerIndex: 0,
          explanation: 'open() defaults to read mode "r" for text files.',
        },
        {
          id: 'l10-c1-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['fileMode'],
          prompt: 'What does f.readlines() return?',
          options: [
            'List of strings, each ending with \\n (usually)',
            'Single string of entire file',
            'List of bytes',
            'Generator of lines without newlines',
          ],
          answerIndex: 0,
          explanation: 'readlines() returns a list; each element typically retains the trailing newline.',
        },
      ],
    },
    {
      id: 'l10-c2',
      title: 'Writing & file modes',
      objective: 'Choose "w", "a", "r+" and predict overwrite vs append behavior.',
      examples: [
        {
          id: 'l10-c2-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['fileMode'],
          prompt: 'Trace append mode writing.',
          code: 'with open("log.txt", "a") as f:\n    f.write("ok\\n")\n# file now contains previous content plus "ok\\n"',
          steps: [
            { line: 1, vars: {} },
            { line: 2, vars: {} },
          ],
          question: 'Does mode "a" truncate the file first?',
          options: ['False', 'True', 'None', 'Error'],
          answerIndex: 0,
          explanation: '"a" append mode preserves existing content and writes at end.',
        },
        {
          id: 'l10-c2-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['fileMode'],
          prompt: 'Which mode truncates an existing file to zero length?',
          options: ['"r"', '"w"', '"a"', '"r+"'],
          answerIndex: 1,
          explanation: '"w" creates or overwrites — existing content is destroyed.',
        },
        {
          id: 'l10-c2-e3',
          type: 'fixTheLine',
          stage: 'stretch',
          tags: ['fileMode'],
          prompt: 'Which line destroys existing file content before it can be read?',
          code: 'path = "notes.txt"\nwith open(path, "w") as f:\n    f.write("new line\\n")\nwith open(path) as f:\n    text = f.read()',
          lineOptions: [1, 2, 3, 4],
          answerLine: 2,
          wrongOutput: 'Old notes.txt content is gone; read only sees "new line".',
          explanation: 'open(..., "w") truncates on open. To append without losing data use "a".',
        },
      ],
    },
    {
      id: 'l10-c3',
      title: 'try / except / else / finally',
      objective: 'Catch exceptions and run cleanup or alternate paths.',
      examples: [
        {
          id: 'l10-c3-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['exceptionType'],
          prompt: 'Trace exception handling flow.',
          code: 'try:\n    n = int("42")\n    result = "ok"\nexcept ValueError:\n    result = "bad"\nelse:\n    result = result + "!"',
          steps: [
            { line: 1, vars: {} },
            { line: 2, vars: { n: '42' } },
            { line: 3, vars: { n: '42', result: '"ok"' } },
            { line: 6, vars: { n: '42', result: '"ok!"' } },
          ],
          question: 'What is result after all lines?',
          options: ['"ok!"', '"ok"', '"ok!X"', '"OK!"'],
          answerIndex: 0,
          explanation: 'No exception → except skipped; else runs and appends "!".',
        },
        {
          id: 'l10-c3-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['exceptionType'],
          prompt: 'When does the else block of try/except run?',
          options: [
            'Only if no exception occurred in try',
            'Always after except',
            'Only if except ran',
            'Never — else is invalid with try',
          ],
          answerIndex: 0,
          explanation: 'try/else runs only when try completes without raising.',
        },
        {
          id: 'l10-c3-e3',
          type: 'fillBlank',
          stage: 'stretch',
          tags: ['exceptionType'],
          prompt: 'Fill in the except clause to catch division by zero.',
          code: 'try:\n    x = 1 / 0\nexcept ____:\n    x = None',
          blankLabel: 'exception type',
          options: ['ZeroDivisionError', 'ZeroDivisionErrorx', 'ZERODIVISIONERROR', 'pass'],
          answerIndex: 0,
          explanation: '1 / 0 raises ZeroDivisionError in Python 3.',
        },
      ],
    },
    {
      id: 'l10-c4',
      title: 'Exception types & raise',
      objective: 'Match errors to types and raise exceptions intentionally.',
      examples: [
        {
          id: 'l10-c4-e1',
          type: 'multipleChoice',
          stage: 'see',
          tags: ['exceptionType'],
          prompt: 'int("3.14") raises which exception?',
          options: ['ValueError', 'TypeError', 'SyntaxError', 'IndexError'],
          answerIndex: 0,
          explanation: 'Invalid literal for int() with base 10 → ValueError.',
        },
        {
          id: 'l10-c4-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['exceptionType'],
          prompt: 'What does `raise ValueError("bad input")` do?',
          options: [
            'Stops execution and propagates ValueError',
            'Prints a warning and continues',
            'Returns None',
            'Converts the string to ValueError type',
          ],
          answerIndex: 0,
          explanation: 'raise creates and throws an exception up the call stack.',
        },
        {
          id: 'l10-c4-e3',
          type: 'fixTheLine',
          stage: 'stretch',
          tags: ['exceptionType'],
          prompt: 'Which line catches the wrong exception for lst[99]?',
          code: 'lst = [1, 2, 3]\ntry:\n    x = lst[99]\nexcept KeyError:\n    x = -1\nexcept IndexError:\n    x = 0',
          lineOptions: [1, 2, 3, 4, 5],
          answerLine: 4,
          explanation: 'Index out of range on a list raises IndexError, not KeyError (dict key missing).',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l10-check-1',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['fileMode'],
      prompt: 'Safest way to append one line to an existing file?',
      options: [
        'open(path, "a")',
        'open(path, "w")',
        'open(path, "r")',
        'open(path, "r+") without seek',
      ],
      answerIndex: 0,
      explanation: 'Append mode "a" adds to end without truncating.',
    },
    {
      id: 'l10-check-2',
      type: 'traceSteps',
      stage: 'stretch',
      tags: ['exceptionType'],
      prompt: 'Trace exception path.',
      code: 'try:\n    val = int("x")\nexcept ValueError:\n    val = 0',
      steps: [
        { line: 1, vars: {} },
        { line: 2, vars: {} },
        { line: 3, vars: { val: '0' } },
      ],
      question: 'What is val?',
      options: ['0', '1', '-1', '2'],
          answerIndex: 0,
          explanation: 'int("x") raises ValueError; handler sets val to 0.',
    },
    {
      id: 'l10-check-3',
      type: 'fillBlank',
      stage: 'stretch',
      tags: ['fileMode'],
      prompt: 'Complete to write "done" to out.txt (overwrite if exists).',
      code: 'with open("out.txt", ____) as f:\n    f.write("done")',
      blankLabel: 'mode',
      options: ['"w"', '"r"', '"a"', '"rw"'],
          answerIndex: 0,
      explanation: '"w" opens for writing and truncates existing file.',
    },
    {
      id: 'l10-check-4',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['exceptionType'],
      prompt: 'd = {}; d["missing"] raises?',
      options: ['KeyError', 'IndexError', 'ValueError', 'AttributeError'],
      answerIndex: 0,
      explanation: 'Missing dict key → KeyError; missing list index → IndexError.',
    },
  ],
};
