import type { Lesson } from '../schema';

export const lesson13: Lesson = {
  id: 'lesson13',
  title: 'Debug & Identity',
  subtitle: 'Tracebacks, is vs ==, copies, and testing with assert',
  objectives: [
    'Read a traceback from the bottom up to find the error line',
    'Choose is vs == correctly, especially with None',
    'Distinguish alias, shallow copy, and deep copy for nested data',
    'Write simple assert checks to verify expected behavior',
  ],
  concepts: [
    {
      id: 'l13-c1',
      title: 'Reading tracebacks',
      objective: 'Find the error type, message, and your line in a stack trace.',
      miniNote: 'Read tracebacks bottom-up: last line is the exception; lines above show the call path.',
      examples: [
        {
          id: 'l13-c1-e1',
          type: 'multipleChoice',
          stage: 'see',
          tags: ['traceback'],
          prompt: 'In a traceback, which line tells you the exception type and message?',
          options: [
            'The top line (most recent call)',
            'The bottom line (last line of the traceback)',
            'The middle line always',
            'The line with "File" in it',
          ],
          answerIndex: 1,
          explanation: 'The final line shows the exception class and message, e.g. ValueError: invalid literal.',
        },
        {
          id: 'l13-c1-e2',
          type: 'orderLines',
          stage: 'see',
          tags: ['traceback'],
          prompt: 'Order these traceback reading steps.',
          lines: [
            'Find the exception type and message at the bottom',
            'Look at the "File ... line N" entries above it',
            'Find the frame in YOUR code (not library code)',
            'Read that line and fix the cause',
          ],
          correctOrder: [0, 1, 2, 3],
          explanation: 'Bottom = what failed; walk up to your code; fix that line.',
        },
        {
          id: 'l13-c1-e3',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['traceback', 'exceptionType'],
          prompt: 'Traceback ends with: TypeError: can only concatenate str (not "int") to str. What failed?',
          options: [
            'Using + between a str and an int without conversion',
            'A missing import',
            'Division by zero',
            'An invalid dictionary key',
          ],
          answerIndex: 0,
          explanation: 'TypeError on concatenation means incompatible types were combined with +.',
        },
        {
          id: 'l13-c1-e4',
          type: 'fixTheLine',
          stage: 'debug',
          tags: ['traceback', 'typeCoercion'],
          prompt: 'This raises TypeError on line 3. Which line should you fix first?',
          code: 'name = "Ada"\nage = 20\nmsg = name + age\nprint(msg)',
          lineOptions: [1, 2, 3, 4],
          answerLine: 3,
          explanation: 'Fix line 3: use str(age) or an f-string instead of str + int.',
        },
      ],
    },
    {
      id: 'l13-c2',
      title: 'is vs == and None',
      objective: 'Use == for value equality; use is for identity (same object). Always test None with is.',
      miniNote: 'if x is None — never if x == None. Two empty lists are == but not is.',
      examples: [
        {
          id: 'l13-c2-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['identity'],
          prompt: 'Step through list equality vs identity.',
          code: 'a = [1, 2]\nb = [1, 2]\nc = a\nsame_ab = a is b\nsame_ac = a is c',
          steps: [
            { line: 1, vars: { a: '[1, 2]' } },
            { line: 2, vars: { a: '[1, 2]', b: '[1, 2]' } },
            { line: 3, vars: { a: '[1, 2]', b: '[1, 2]', c: '[1, 2]' } },
            { line: 4, vars: { a: '[1, 2]', b: '[1, 2]', c: '[1, 2]', same_ab: 'False' } },
            { line: 5, vars: { a: '[1, 2]', b: '[1, 2]', c: '[1, 2]', same_ab: 'False', same_ac: 'True' } },
          ],
          question: 'What is same_ab?',
          options: ['False', 'True', 'None', 'Error'],
          answerIndex: 0,
          explanation: 'a and b are equal in value but are two separate list objects → is is False.',
        },
        {
          id: 'l13-c2-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['identity', 'truthiness'],
          prompt: 'Which is the idiomatic way to test if x is missing (None)?',
          options: ['if x == None:', 'if x is None:', 'if not x:', 'if x == "None":'],
          answerIndex: 1,
          explanation: 'PEP 8: use `is` / `is not` with None — identity check, not value equality.',
        },
        {
          id: 'l13-c2-e3',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['identity'],
          prompt: 'What is the result of [] is []?',
          options: ['True', 'False', 'None', 'Error'],
          answerIndex: 1,
          explanation: 'Each [] literal creates a new list object. == is True, is is False.',
        },
        {
          id: 'l13-c2-e4',
          type: 'matchPairs',
          stage: 'stretch',
          tags: ['identity'],
          prompt: 'Match the operator to its best use.',
          leftItems: ['x is None', 'x == y', 'x is y', 'x is True'],
          rightItems: [
            'Same object in memory',
            'Same value/content',
            'Test for None sentinel',
            'Rare — usually use `if x:` instead',
          ],
          pairs: [[0, 2], [1, 1], [2, 0], [3, 3]],
          explanation: '== compares values; is compares object identity; None always uses is.',
        },
      ],
    },
    {
      id: 'l13-c3',
      title: 'Shallow vs deep copy',
      objective: 'Know when slice/copy copies inner objects by reference.',
      miniNote: 'L[:] and list(L) are shallow — nested lists inside still alias. Use copy.deepcopy for full independence.',
      examples: [
        {
          id: 'l13-c3-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['shallowCopy', 'aliasing'],
          prompt: 'Trace shallow copy of a nested list.',
          code: 'a = [[1], [2]]\nb = a[:]\nb[0].append(99)',
          steps: [
            { line: 1, vars: { a: '[[1], [2]]' } },
            { line: 2, vars: { a: '[[1], [2]]', b: '[[1], [2]]' } },
            { line: 3, vars: { a: '[[1, 99], [2]]', b: '[[1, 99], [2]]' } },
          ],
          question: 'What is a after line 3?',
          options: ['[[1, 99], [2]]', '[[1], [2]]', '[[99], [2]]', 'Error'],
          answerIndex: 0,
          explanation: 'b = a[:] copies the outer list but inner lists are shared → mutating b[0] changes a[0].',
        },
        {
          id: 'l13-c3-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['shallowCopy'],
          prompt: 'Which creates a shallow copy of list L?',
          options: ['b = L', 'b = L[:]', 'b = L.append(x)', 'b = L is L'],
          answerIndex: 1,
          explanation: 'L[:] (or list(L) or L.copy()) copies top-level elements; assignment L aliases.',
        },
        {
          id: 'l13-c3-e3',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['shallowCopy'],
          prompt: 'When do you need copy.deepcopy() instead of L[:]?',
          options: [
            'Always — L[:] never works',
            'When L contains nested mutable objects you want fully independent',
            'Only for strings',
            'Only when L is empty',
          ],
          answerIndex: 1,
          explanation: 'deepcopy recursively copies nested mutables so no inner aliasing remains.',
        },
        {
          id: 'l13-c3-e4',
          type: 'fixTheLine',
          stage: 'debug',
          tags: ['shallowCopy', 'aliasing'],
          prompt: 'Goal: change b without affecting a. Which line causes shared mutation?',
          code: 'a = [[1], [2]]\nb = a[:]\nb[0] = [99]\nb[1].append(0)',
          lineOptions: [1, 2, 3, 4],
          answerLine: 4,
          explanation: 'Line 4 mutates the inner list shared by a and b. Line 3 rebinds b[0] to a new list (safe).',
        },
      ],
    },
    {
      id: 'l13-c4',
      title: 'Testing with assert',
      objective: 'Turn expected behavior into checks you run before trusting code.',
      miniNote: 'assert condition, "message" — if False, raises AssertionError with optional message.',
      examples: [
        {
          id: 'l13-c4-e1',
          type: 'multipleChoice',
          stage: 'see',
          tags: ['assertLogic'],
          prompt: 'What happens when assert 2 + 2 == 5 runs?',
          options: [
            'Nothing — assert is ignored',
            'AssertionError is raised',
            'SyntaxError is raised',
            'Prints False',
          ],
          answerIndex: 1,
          explanation: 'assert raises AssertionError when the condition is False.',
        },
        {
          id: 'l13-c4-e2',
          type: 'orderLines',
          stage: 'try',
          tags: ['assertLogic'],
          prompt: 'Order a test-first workflow.',
          lines: [
            'Write assert statements for expected outputs',
            'Run the code / function',
            'If assert fails, fix the code',
            'Add more asserts for edge cases',
          ],
          correctOrder: [0, 1, 2, 3],
          explanation: 'Define expected behavior first; asserts catch regressions immediately.',
        },
        {
          id: 'l13-c4-e3',
          type: 'codeChallenge',
          stage: 'build',
          tags: ['assertLogic', 'scope'],
          prompt: 'Write double(x) that returns x * 2. Tests use assert.',
          starterCode: 'def double(x):\n    pass',
          tests: ['assert double(3) == 6', 'assert double(0) == 0', 'assert double(-2) == -4'],
          explanation: 'return x * 2 satisfies all assert checks.',
        },
        {
          id: 'l13-c4-e4',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['assertLogic'],
          prompt: 'assert len(items) > 0, "need at least one item" — the string after the comma is…',
          options: [
            'A comment (ignored)',
            'The message shown if the assert fails',
            'The return value',
            'A type hint',
          ],
          answerIndex: 1,
          explanation: 'Optional message is included in AssertionError when the condition is False.',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l13-check-1',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['identity'],
      prompt: 'Lesson check: best test for "no result yet"?',
      options: ['if result == None:', 'if result is None:', 'if result == []:', 'if not result:'],
      answerIndex: 1,
      explanation: 'None is a singleton — always test with `is None`.',
    },
    {
      id: 'l13-check-2',
      type: 'traceSteps',
      stage: 'stretch',
      tags: ['shallowCopy'],
      prompt: 'Lesson check: flat list copy.',
      code: 'a = [1, 2, 3]\nb = a[:]\nb.append(4)',
      steps: [
        { line: 1, vars: { a: '[1, 2, 3]' } },
        { line: 2, vars: { a: '[1, 2, 3]', b: '[1, 2, 3]' } },
        { line: 3, vars: { a: '[1, 2, 3]', b: '[1, 2, 3, 4]' } },
      ],
      question: 'What is a after line 3?',
      options: ['[1, 2, 3]', '[1, 2, 3, 4]', '[1, 2]', 'Error'],
      answerIndex: 0,
      explanation: 'Shallow copy of flat list — append to b does not change a.',
    },
    {
      id: 'l13-check-3',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['traceback'],
      prompt: 'Lesson check: IndexError in traceback means…',
      options: [
        'Invalid index for sequence',
        'Wrong file mode',
        'Missing dictionary key',
        'Recursion too deep',
      ],
      answerIndex: 0,
      explanation: 'IndexError: sequence index out of range — bad subscript on list/str/tuple.',
    },
    {
      id: 'l13-check-4',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['assertLogic'],
      prompt: 'Lesson check: assert is best used to…',
      options: [
        'Replace all try/except blocks',
        'Document and verify expected behavior during development',
        'Speed up loops',
        'Import modules',
      ],
      answerIndex: 1,
      explanation: 'Asserts encode invariants and expected outputs; they are not a substitute for user input validation in production.',
    },
  ],
};
