import type { Lesson } from '../schema';

export const lesson03: Lesson = {
  id: 'lesson03',
  title: 'Conditionals',
  subtitle: 'if, elif, else, nesting, and boolean logic',
  objectives: [
    'Write and trace if/elif/else branches',
    'Combine conditions with and, or, not',
    'Predict nested conditional behavior',
    'Use truthiness in conditional tests',
  ],
  concepts: [
    {
      id: 'l3-c1',
      title: 'if / elif / else',
      objective: 'Follow which branch executes.',
      examples: [
        {
          id: 'l3-c1-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['truthiness'],
          prompt: 'Step through the conditional chain.',
          code: 'score = 85\nif score >= 90:\n    grade = "A"\nelif score >= 80:\n    grade = "B"\nelse:\n    grade = "C"',
          steps: [
            { line: 1, vars: { score: '85' } },
            { line: 2, vars: { score: '85' } },
            { line: 4, vars: { score: '85', grade: '"B"' } },
          ],
          question: 'What is grade?',
          options: ['"B"', '""', '"BX"', 'B'],
          answerIndex: 0,
          explanation: '85 >= 80 but not >= 90, so elif branch runs.',
        },
        {
          id: 'l3-c1-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['truthiness'],
          prompt: 'How many elif blocks can follow a single if?',
          options: ['0', '1', 'Unlimited', 'Exactly 2'],
          answerIndex: 2,
          explanation: 'You may chain any number of elif clauses before optional else.',
        },
        {
          id: 'l3-c1-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['truthiness'],
          prompt: 'If x = 0, which runs?\nif x:\n    print("A")\nelse:\n    print("B")',
          options: ['A', 'B', 'Both', 'Neither'],
          answerIndex: 1,
          explanation: '0 is falsy, so else branch executes.',
        },
      ],
    },
    {
      id: 'l3-c2',
      title: 'Compound conditions',
      objective: 'Combine comparisons with and, or, not in if headers.',
      examples: [
        {
          id: 'l3-c2-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['truthiness'],
          prompt: 'Trace compound condition.',
          code: 'age = 20\nhas_id = True\nif age >= 18 and has_id:\n    admit = True\nelse:\n    admit = False',
          steps: [
            { line: 1, vars: { age: '20' } },
            { line: 2, vars: { age: '20', has_id: 'True' } },
            { line: 3, vars: { age: '20', has_id: 'True', admit: 'True' } },
          ],
          question: 'What is admit?',
          options: ['True', 'False', 'None', 'Error'],
          answerIndex: 0,
          explanation: 'Both conditions true → and is True.',
        },
        {
          id: 'l3-c2-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['truthiness'],
          prompt: 'When is `if not x` True?',
          options: ['x is truthy', 'x is falsy', 'x is None only', 'Never'],
          answerIndex: 1,
          explanation: 'not inverts truthiness.',
        },
        {
          id: 'l3-c2-e3',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['truthiness'],
          prompt: 'Which condition checks if n is between 1 and 10 inclusive?',
          options: ['n > 1 and n < 10', 'n >= 1 and n <= 10', '1 < n < 10', 'n in range(1,10)'],
          answerIndex: 1,
          explanation: 'Use >= and <= for inclusive bounds on both ends.',
        },
      ],
    },
    {
      id: 'l3-c3',
      title: 'Nested conditionals',
      objective: 'Trace inner branches inside outer branches.',
      examples: [
        {
          id: 'l3-c3-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: [],
          prompt: 'Follow nested if structure.',
          code: 'x = 5\ny = 10\nif x < y:\n    if x > 0:\n        result = "pos"\n    else:\n        result = "non-pos"\nelse:\n    result = "big"',
          steps: [
            { line: 1, vars: { x: '5' } },
            { line: 2, vars: { x: '5', y: '10' } },
            { line: 3, vars: { x: '5', y: '10' } },
            { line: 4, vars: { x: '5', y: '10', result: '"pos"' } },
          ],
          question: 'What is result?',
          options: ['"pos"', '"po"', '"posX"', '"POS"'],
          answerIndex: 0,
          explanation: 'Outer true, inner x > 0 true → "pos".',
        },
        {
          id: 'l3-c3-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: [],
          prompt: 'Nested if x > 0: if x < 10: print("ok") — when does it print?',
          options: ['x > 0 only', '0 < x < 10', 'x < 10 only', 'Always'],
          answerIndex: 1,
          explanation: 'Both conditions must hold: x positive and less than 10.',
        },
        {
          id: 'l3-c3-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['truthiness'],
          prompt: 'What is a cleaner equivalent to:\nif x > 0:\n  if x < 10:\n    ...',
          options: ['if 0 < x < 10:', 'if x > 0 or x < 10:', 'if x in (0,10):', 'if x > 0 and x < 10:'],
          answerIndex: 3,
          explanation: 'Combine with and, or use chained comparison 0 < x < 10.',
        },
      ],
    },
    {
      id: 'l3-c4',
      title: 'Truthiness in conditionals',
      objective: 'Use empty containers and zero as natural condition tests.',
      examples: [
        {
          id: 'l3-c4-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['truthiness'],
          prompt: 'See how empty list is falsy.',
          code: 'items = []\nif items:\n    msg = "has items"\nelse:\n    msg = "empty"',
          steps: [
            { line: 1, vars: { items: '[]' } },
            { line: 2, vars: { items: '[]' } },
            { line: 4, vars: { items: '[]', msg: '"empty"' } },
          ],
          question: 'What is msg?',
          options: ['"empty"', '"empt"', '"emptyX"', '"EMPTY"'],
          answerIndex: 0,
          explanation: 'Empty list [] is falsy in boolean context.',
        },
        {
          id: 'l3-c4-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['truthiness'],
          prompt: 'Which is falsy?',
          options: ['[0]', '[False]', '""', '"False"'],
          answerIndex: 2,
          explanation: 'Empty string is falsy. Non-empty strings including "False" are truthy.',
        },
        {
          id: 'l3-c4-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['truthiness'],
          prompt: 'Preferred idiom to check non-empty list L?',
          options: ['if L != []:', 'if len(L) > 0:', 'if L:', 'if not not L:'],
          answerIndex: 2,
          explanation: 'if L: is Pythonic — tests truthiness directly.',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l3-check-1',
      type: 'traceSteps',
      stage: 'stretch',
      tags: ['truthiness'],
      prompt: 'Lesson check trace.',
      code: 'n = -1\nif n:\n    s = "yes"\nelse:\n    s = "no"',
      steps: [
        { line: 1, vars: { n: '-1' } },
        { line: 2, vars: { n: '-1', s: '"yes"' } },
      ],
      question: 'What is s?',
      options: ['"yes"', '"ye"', '"yesX"', '"YES"'],
          answerIndex: 0,
          explanation: '-1 is truthy (non-zero).',
    },
    {
      id: 'l3-check-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['truthiness'],
      prompt: 'What prints?\nx = 10\nif x > 5:\n    if x < 15:\n        print("mid")',
      options: ['mid', 'nothing', 'Error', 'True'],
      answerIndex: 0,
      explanation: 'Both nested conditions satisfied.',
    },
    {
      id: 'l3-check-3',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['truthiness'],
      prompt: 'elif runs when?',
      options: [
        'Previous if/elif was false',
        'Always after if',
        'Only if else exists',
        'When if is true',
      ],
      answerIndex: 0,
      explanation: 'elif is evaluated only if all prior branches failed.',
    },
  ],
};
