import type { Lesson } from '../schema';

export const lesson06: Lesson = {
  id: 'lesson06',
  title: 'Strings',
  subtitle: 'Indexing, slicing, and immutability',
  objectives: [
    'Index strings with positive and negative offsets',
    'Slice with [start:stop:step] and predict results',
    'Explain why strings cannot be mutated in place',
    'Use common string methods without changing the original',
  ],
  concepts: [
    {
      id: 'l6-c1',
      title: 'String indexing',
      objective: 'Access individual characters with s[i] and s[-i].',
      miniNote: 'Valid indices for length-n string: 0 through n-1, or -1 through -n.',
      examples: [
        {
          id: 'l6-c1-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: [],
          prompt: 'Step through positive and negative indexing.',
          code: 's = "Python"\nfirst = s[0]\nlast = s[-1]\nmiddle = s[2]',
          steps: [
            { line: 1, vars: { s: '"Python"' } },
            { line: 2, vars: { s: '"Python"', first: '"P"' } },
            { line: 3, vars: { s: '"Python"', first: '"P"', last: '"n"' } },
            { line: 4, vars: { s: '"Python"', first: '"P"', last: '"n"', middle: '"t"' } },
          ],
          question: 'What is middle?',
          options: ['"t"', '""', '"tX"', '"T"'],
          answerIndex: 0,
          explanation: 'Index 2 is the third character: P(0), y(1), t(2).',
        },
        {
          id: 'l6-c1-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: [],
          prompt: 'For s = "abc", what is s[-2]?',
          options: ['"a"', '"b"', '"c"', 'Error'],
          answerIndex: 1,
          explanation: '-1 is c, -2 is b, -3 is a.',
        },
        {
          id: 'l6-c1-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['offByOne'],
          prompt: 's = "hi" — which index raises IndexError?',
          options: ['s[1]', 's[-2]', 's[2]', 's[-1]'],
          answerIndex: 2,
          explanation: 'Valid indices are 0, 1 (or -1, -2). Index 2 is out of range.',
        },
      ],
    },
    {
      id: 'l6-c2',
      title: 'Slicing',
      objective: 'Extract substrings with s[start:stop] and s[start:stop:step].',
      examples: [
        {
          id: 'l6-c2-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['offByOne'],
          prompt: 'Trace slice bounds (stop is exclusive).',
          code: 'word = "ABCDEF"\na = word[1:4]\nb = word[:3]\nc = word[3:]',
          steps: [
            { line: 1, vars: { word: '"ABCDEF"' } },
            { line: 2, vars: { word: '"ABCDEF"', a: '"BCD"' } },
            { line: 3, vars: { word: '"ABCDEF"', a: '"BCD"', b: '"ABC"' } },
            { line: 4, vars: { word: '"ABCDEF"', a: '"BCD"', b: '"ABC"', c: '"DEF"' } },
          ],
          question: 'What is a?',
          options: ['"BCD"', '"BC"', '"BCDX"', '""'],
          answerIndex: 0,
          explanation: '[1:4] takes indices 1, 2, 3 — characters B, C, D.',
        },
        {
          id: 'l6-c2-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['offByOne'],
          prompt: 'What is "hello"[::-1]?',
          options: ['"hello"', '"olleh"', '"hell"', 'Error'],
          answerIndex: 1,
          explanation: 'Step -1 reverses the string.',
        },
        {
          id: 'l6-c2-e3',
          type: 'fillBlank',
          stage: 'stretch',
          tags: ['offByOne'],
          prompt: 'Fill the slice to get "Py" from "Python".',
          code: 's = "Python"\npart = s[____]',
          blankLabel: 'slice',
          options: ['0:2', '1:3', ':2', '0:3'],
          answerIndex: 0,
          explanation: '[0:2] or [:2] takes indices 0 and 1 → "Py".',
        },
      ],
    },
    {
      id: 'l6-c3',
      title: 'Immutability',
      objective: 'Strings cannot be changed in place; operations create new strings.',
      examples: [
        {
          id: 'l6-c3-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['mutation'],
          prompt: 'See reassignment vs in-place change.',
          code: 's = "cat"\ns = s + "s"\nt = s\ns = "dog"',
          steps: [
            { line: 1, vars: { s: '"cat"' } },
            { line: 2, vars: { s: '"cats"' } },
            { line: 3, vars: { s: '"cats"', t: '"cats"' } },
            { line: 4, vars: { s: '"dog"', t: '"cats"' } },
          ],
          question: 'What are s and t after line 4?',
          options: ['s="dog", t="cats"', 's="dog", t="cats"x', 'S="DOG", T="CATS"', 'pass'],
          answerIndex: 0,
          explanation: 'Rebinding s does not change t; strings are immutable objects.',
        },
        {
          id: 'l6-c3-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['mutation'],
          prompt: 'What happens?\ns = "ab"\ns[0] = "x"',
          options: ['s becomes "xb"', 's stays "ab"', 'TypeError', 'SyntaxError'],
          answerIndex: 2,
          explanation: 'str does not support item assignment — strings are immutable.',
        },
        {
          id: 'l6-c3-e3',
          type: 'fixTheLine',
          stage: 'stretch',
          tags: ['mutation'],
          prompt: 'Goal: uppercase first char of name. Which line is wrong?',
          code: 'name = "ada"\nname[0] = name[0].upper()',
          lineOptions: [1, 2],
          answerLine: 2,
          explanation: 'Cannot assign to a string index. Use name = name[0].upper() + name[1:] instead.',
        },
      ],
    },
    {
      id: 'l6-c4',
      title: 'String methods',
      objective: 'Use .upper(), .lower(), .strip(), .split() — originals unchanged.',
      examples: [
        {
          id: 'l6-c4-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['mutation'],
          prompt: 'Methods return new strings; original unchanged.',
          code: 'msg = "  Hi  "\nclean = msg.strip()\nloud = msg.upper()',
          steps: [
            { line: 1, vars: { msg: '"  Hi  "' } },
            { line: 2, vars: { msg: '"  Hi  "', clean: '"Hi"' } },
            { line: 3, vars: { msg: '"  Hi  "', clean: '"Hi"', loud: '"  HI  "' } },
          ],
          question: 'What is msg after all lines?',
          options: ['"  Hi  "', '"  Hi "', '"  Hi  X"', '"  HI  "'],
          answerIndex: 0,
          explanation: 'strip() and upper() return new strings; msg is never modified.',
        },
        {
          id: 'l6-c4-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: [],
          prompt: '"a,b,c".split(",") produces?',
          options: ['["a,b,c"]', '["a", "b", "c"]', '("a", "b", "c")', 'Error'],
          answerIndex: 1,
          explanation: 'split divides on the delimiter and returns a list of substrings.',
        },
        {
          id: 'l6-c4-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: [],
          prompt: '"hello".find("ll") returns?',
          options: ['2', 'True', '-1', 'Error'],
          answerIndex: 0,
          explanation: 'find returns starting index of substring, or -1 if not found.',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l6-check-1',
      type: 'traceSteps',
      stage: 'stretch',
      tags: ['offByOne'],
      prompt: 'Lesson check slice trace.',
      code: 's = "012345"\nmid = s[2:5]\nrev = s[::-1]',
      steps: [
        { line: 1, vars: { s: '"012345"' } },
        { line: 2, vars: { s: '"012345"', mid: '"234"' } },
        { line: 3, vars: { s: '"012345"', mid: '"234"', rev: '"543210"' } },
      ],
      question: 'What is mid?',
      options: ['"234"', '"23"', '"234X"', '""'],
          answerIndex: 0,
          explanation: 'Indices 2, 3, 4 → characters 2, 3, 4.',
    },
    {
      id: 'l6-check-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['mutation'],
      prompt: 'After x = "test"; y = x; x = x.replace("t", "T"), what is y?',
      options: ['"Test"', '"test"', '"TesT"', 'Error'],
      answerIndex: 1,
      explanation: 'replace returns a new string assigned to x; y still references "test".',
    },
    {
      id: 'l6-check-3',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: [],
      prompt: 'What is len("\\\\n")? (one backslash, one letter n)',
      options: ['1', '2', '3', 'Error'],
      answerIndex: 1,
      explanation: 'Two characters: backslash and n. Not a newline escape in this literal.',
    },
    {
      id: 'l6-check-4',
      type: 'fixTheLine',
      stage: 'stretch',
      tags: ['offByOne'],
      prompt: 'Should extract "hon" from "Python" but gets "Pyth". Which slice line is wrong?',
      code: 's = "Python"\npart = s[0:4]',
      lineOptions: [1, 2],
      answerLine: 2,
      wrongOutput: '"Pyth"',
      explanation: 's[0:4] stops before index 4 → "Pyth". Use s[3:] or s[3:6] to get "hon".',
    },
  ],
};