import type { Lesson } from '../schema';

export const lesson04: Lesson = {
  id: 'lesson04',
  title: 'Loops',
  subtitle: 'while, for, range, and off-by-one traps',
  objectives: [
    'Write and trace while and for loops',
    'Use range() with start, stop, and step',
    'Predict loop termination and iteration counts',
    'Spot off-by-one errors in bounds and counters',
  ],
  concepts: [
    {
      id: 'l4-c1',
      title: 'while loops',
      objective: 'Repeat a block while a condition stays true.',
      miniNote: 'Update the loop variable inside the body or the loop may never end.',
      examples: [
        {
          id: 'l4-c1-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['loopLogic'],
          prompt: 'Step through the while loop.',
          code: 'n = 3\nwhile n > 0:\n    n = n - 1\ncount = 3 - n',
          steps: [
            { line: 1, vars: { n: '3' } },
            { line: 2, vars: { n: '3' } },
            { line: 3, vars: { n: '2' } },
            { line: 2, vars: { n: '2' } },
            { line: 3, vars: { n: '1' } },
            { line: 2, vars: { n: '1' } },
            { line: 3, vars: { n: '0' } },
            { line: 4, vars: { n: '0', count: '3' } },
          ],
          question: 'What is count after the loop finishes?',
          options: ['3', '4', '2', '6'],
          answerIndex: 0,
          explanation: 'The loop runs 3 times (n: 3→2→1→0). count = 3 - 0 = 3.',
        },
        {
          id: 'l4-c1-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['loopLogic'],
          prompt: 'When does a while loop body execute?',
          options: [
            'Exactly once',
            'While the condition is True',
            'While the condition is False',
            'A fixed number of times always',
          ],
          answerIndex: 1,
          explanation: 'The body runs repeatedly as long as the condition evaluates to True.',
        },
        {
          id: 'l4-c1-e3',
          type: 'fixTheLine',
          stage: 'stretch',
          tags: ['loopLogic'],
          prompt: 'This loop never terminates. Which line is the bug?',
          code: 'i = 0\nwhile i < 5:\n    print(i)\n    i = i + 0',
          lineOptions: [1, 2, 3, 4],
          answerLine: 4,
          wrongOutput: 'Prints 0 forever',
          explanation: 'i = i + 0 never advances i, so i < 5 stays True forever.',
        },
      ],
    },
    {
      id: 'l4-c2',
      title: 'for loops',
      objective: 'Iterate over sequences with for ... in ....',
      examples: [
        {
          id: 'l4-c2-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['loopLogic'],
          prompt: 'Trace the for loop over a list.',
          code: 'total = 0\nfor x in [2, 4, 6]:\n    total = total + x',
          steps: [
            { line: 1, vars: { total: '0' } },
            { line: 2, vars: { total: '0', x: '2' } },
            { line: 3, vars: { total: '2', x: '2' } },
            { line: 2, vars: { total: '2', x: '4' } },
            { line: 3, vars: { total: '6', x: '4' } },
            { line: 2, vars: { total: '6', x: '6' } },
            { line: 3, vars: { total: '12', x: '6' } },
          ],
          question: 'What is total after the loop?',
          options: ['12', '13', '11', '24'],
          answerIndex: 0,
          explanation: '2 + 4 + 6 = 12.',
        },
        {
          id: 'l4-c2-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['loopLogic'],
          prompt: 'What does `for ch in "hi":` iterate over?',
          options: ['Two strings', 'Characters h and i', 'Indices 0 and 1', 'One string "hi"'],
          answerIndex: 1,
          explanation: 'for iterates over elements; a str yields one-character strings.',
        },
        {
          id: 'l4-c2-e3',
          type: 'fillBlank',
          stage: 'stretch',
          tags: ['loopLogic'],
          prompt: 'Fill in the loop header to print each item in nums.',
          code: 'nums = [10, 20, 30]\n____:\n    print(n)',
          blankLabel: 'loop header',
          options: ['for n in nums', 'for n in numsx', 'FOR N IN NUMS', 'pass'],
          answerIndex: 0,
          explanation: 'for n in nums binds each list element to n in turn.',
        },
      ],
    },
    {
      id: 'l4-c3',
      title: 'range()',
      objective: 'Generate numeric sequences with range(start, stop, step).',
      miniNote: 'range stop is exclusive — range(0, 3) yields 0, 1, 2.',
      examples: [
        {
          id: 'l4-c3-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['offByOne'],
          prompt: 'Trace values produced by range(2, 5).',
          code: 's = ""\nfor i in range(2, 5):\n    s = s + str(i)',
          steps: [
            { line: 1, vars: { s: '""' } },
            { line: 2, vars: { s: '""', i: '2' } },
            { line: 3, vars: { s: '"2"', i: '2' } },
            { line: 2, vars: { s: '"2"', i: '3' } },
            { line: 3, vars: { s: '"23"', i: '3' } },
            { line: 2, vars: { s: '"23"', i: '4' } },
            { line: 3, vars: { s: '"234"', i: '4' } },
          ],
          question: 'What is s after the loop?',
          options: ['"234"', '"23"', '"234X"', '""'],
          answerIndex: 0,
          explanation: 'range(2, 5) yields 2, 3, 4 — stop 5 is not included.',
        },
        {
          id: 'l4-c3-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['offByOne'],
          prompt: 'How many numbers does range(5) produce?',
          options: ['4', '5', '6', '0'],
          answerIndex: 1,
          explanation: 'range(5) is shorthand for range(0, 5): 0, 1, 2, 3, 4.',
        },
        {
          id: 'l4-c3-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['offByOne'],
          prompt: 'What does list(range(1, 10, 3)) produce?',
          options: ['[1, 4, 7]', '[1, 4, 7, 10]', '[3, 6, 9]', '[1, 3, 5, 7, 9]'],
          answerIndex: 0,
          explanation: 'Start 1, add step 3 each time: 1, 4, 7. Next would be 10 which equals stop, so excluded.',
        },
      ],
    },
    {
      id: 'l4-c4',
      title: 'Off-by-one errors',
      objective: 'Avoid wrong bounds when counting iterations or indexing.',
      examples: [
        {
          id: 'l4-c4-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['offByOne'],
          prompt: 'Compare range(n) vs range(1, n+1).',
          code: 'n = 4\na = 0\nfor i in range(n):\n    a = a + 1\nb = 0\nfor i in range(1, n + 1):\n    b = b + 1',
          steps: [
            { line: 1, vars: { n: '4' } },
            { line: 2, vars: { n: '4', a: '0' } },
            { line: 3, vars: { n: '4', a: '0', i: '0' } },
            { line: 4, vars: { n: '4', a: '1', i: '0' } },
            { line: 3, vars: { n: '4', a: '1', i: '1' } },
            { line: 4, vars: { n: '4', a: '2', i: '1' } },
            { line: 3, vars: { n: '4', a: '2', i: '2' } },
            { line: 4, vars: { n: '4', a: '3', i: '2' } },
            { line: 3, vars: { n: '4', a: '3', i: '3' } },
            { line: 4, vars: { n: '4', a: '4', i: '3' } },
            { line: 6, vars: { n: '4', a: '4', b: '0' } },
            { line: 7, vars: { n: '4', a: '4', b: '0', i: '1' } },
            { line: 8, vars: { n: '4', a: '4', b: '1', i: '1' } },
            { line: 7, vars: { n: '4', a: '4', b: '1', i: '2' } },
            { line: 8, vars: { n: '4', a: '4', b: '2', i: '2' } },
            { line: 7, vars: { n: '4', a: '4', b: '2', i: '3' } },
            { line: 8, vars: { n: '4', a: '4', b: '3', i: '3' } },
            { line: 7, vars: { n: '4', a: '4', b: '3', i: '4' } },
            { line: 8, vars: { n: '4', a: '4', b: '4', i: '4' } },
          ],
          question: 'What are a and b after both loops?',
          options: ['a=4, b=4', 'a=4, b=4x', 'A=4, B=4', 'pass'],
          answerIndex: 0,
          explanation: 'Both loops run 4 times here, but range(1, n) would run only 3 — a classic off-by-one trap.',
        },
        {
          id: 'l4-c4-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['offByOne'],
          prompt: 'To loop indices 0..len(items)-1 safely, which is best?',
          options: [
            'for i in range(len(items) + 1):',
            'for i in range(len(items)):',
            'for i in range(1, len(items)):',
            'for i in range(len(items) - 1):',
          ],
          answerIndex: 1,
          explanation: 'range(len(items)) gives 0 through len-1, matching valid indices.',
        },
        {
          id: 'l4-c4-e3',
          type: 'fixTheLine',
          stage: 'stretch',
          tags: ['offByOne'],
          prompt: 'This should sum 1+2+3+4+5 (=15) but gets 10. Which line is wrong?',
          code: 'total = 0\nfor i in range(1, 5):\n    total = total + i',
          lineOptions: [1, 2, 3],
          answerLine: 2,
          wrongOutput: '10',
          explanation: 'range(1, 5) stops at 4. Use range(1, 6) or range(1, 5+1) to include 5.',
        },
        {
          id: 'l4-c4-e4',
          type: 'codeChallenge',
          stage: 'build',
          tags: ['loopLogic'],
          prompt: 'Write sum_to(n) that returns 1 + 2 + … + n using a loop.',
          starterCode: 'def sum_to(n):\n    total = 0\n    # complete the function\n    return total',
          tests: ['assert sum_to(5) == 15', 'assert sum_to(1) == 1', 'assert sum_to(0) == 0'],
          explanation: 'Use range(1, n + 1) or range(n) with careful indexing to accumulate.',
          solutionHint: 'for i in range(1, n + 1): total += i',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l4-check-1',
      type: 'traceSteps',
      stage: 'stretch',
      tags: ['loopLogic'],
      prompt: 'Lesson check: trace the accumulator.',
      code: 'prod = 1\nfor n in [2, 3, 4]:\n    prod = prod * n',
      steps: [
        { line: 1, vars: { prod: '1' } },
        { line: 2, vars: { prod: '1', n: '2' } },
        { line: 3, vars: { prod: '2', n: '2' } },
        { line: 2, vars: { prod: '2', n: '3' } },
        { line: 3, vars: { prod: '6', n: '3' } },
        { line: 2, vars: { prod: '6', n: '4' } },
        { line: 3, vars: { prod: '24', n: '4' } },
      ],
      question: 'What is prod?',
      options: ['24', '25', '23', '48'],
          answerIndex: 0,
          explanation: '1 × 2 × 3 × 4 = 24.',
    },
    {
      id: 'l4-check-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['offByOne'],
      prompt: 'How many iterations does `for _ in range(10, 0, -1):` run?',
      options: ['9', '10', '11', '0'],
      answerIndex: 1,
      explanation: 'Counts down 10, 9, …, 1 — ten values. Stop 0 is excluded.',
    },
    {
      id: 'l4-check-3',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['loopLogic'],
      prompt: 'What prints?\nfor i in range(3):\n    if i == 1:\n        break\n    print(i)',
      options: ['0 then 1', '0 only', '0, 1, 2', '1 only'],
      answerIndex: 1,
      explanation: 'i=0 prints 0. i=1 hits break before print. Loop ends.',
    },
    {
      id: 'l4-check-4',
      type: 'fillBlank',
      stage: 'stretch',
      tags: ['offByOne'],
      prompt: 'Fill range args to produce 5, 4, 3, 2, 1.',
      code: 'for i in range(____, ____, ____):\n    print(i)',
      blankLabel: 'range(5, ?, ?)',
      options: ['5, 0, -1', '5, 1, 0', '4, 0, -1', '5, 0, 1'],
          answerIndex: 0,
      explanation: 'range(5, 0, -1) starts at 5, steps down, stops before 0.',
    },
  ],
};
