import type { Lesson } from '../schema';

export const lesson12: Lesson = {
  id: 'lesson12',
  title: 'Recursion & Big-O',
  subtitle: 'Base cases, call stacks, time/space complexity',
  objectives: [
    'Write recursive functions with correct base cases',
    'Trace recursive call stacks and return values',
    'Describe time complexity with Big-O notation',
    'Compare iterative vs recursive approaches',
  ],
  concepts: [
    {
      id: 'l12-c1',
      title: 'Recursion basics',
      objective: 'Identify base case and recursive step.',
      miniNote: 'Every recursive function needs a base case that stops calls — otherwise infinite recursion.',
      examples: [
        {
          id: 'l12-c1-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['recursion'],
          prompt: 'Trace factorial recursion.',
          code: 'def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\n\nresult = fact(4)',
          steps: [
            { line: 1, vars: {} },
            { line: 6, vars: { result: '24' } },
          ],
          question: 'What is result?',
          options: ['24', '25', '23', '48'],
          answerIndex: 0,
          explanation: 'fact(4) = 4×3×2×1 = 24; base case n<=1 returns 1.',
        },
        {
          id: 'l12-c1-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['recursion'],
          prompt: 'What happens if a recursive function has no base case?',
          options: [
            'RecursionError (max depth exceeded)',
            'Returns None silently',
            'Runs forever without error',
            'SyntaxError at definition',
          ],
          answerIndex: 0,
          explanation: 'Python limits call stack depth; unbounded recursion raises RecursionError.',
        },
        {
          id: 'l12-c1-e3',
          type: 'fillBlank',
          stage: 'stretch',
          tags: ['recursion'],
          prompt: 'Complete the base case for countdown(n).',
          code: 'def countdown(n):\n    if n == ____:\n        return\n    print(n)\n    countdown(n - 1)',
          blankLabel: 'base value',
          options: ['0', '1', '-1', '2'],
          answerIndex: 0,
          explanation: 'Stopping when n == 0 (or n < 1) prevents infinite recursion.',
        },
      ],
    },
    {
      id: 'l12-c2',
      title: 'Tracing recursive calls',
      objective: 'Follow call stack and unwinding of return values.',
      examples: [
        {
          id: 'l12-c2-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['recursion'],
          prompt: 'Trace sum_list recursion.',
          code: 'def sum_list(lst):\n    if not lst:\n        return 0\n    return lst[0] + sum_list(lst[1:])\n\ns = sum_list([2, 3, 5])',
          steps: [
            { line: 1, vars: {} },
            { line: 6, vars: { s: '10' } },
          ],
          question: 'What is s?',
          options: ['10', '11', '9', '20'],
          answerIndex: 0,
          explanation: '2 + sum([3,5]) → 2 + 3 + sum([5]) → 2 + 3 + 5 + 0 = 10.',
        },
        {
          id: 'l12-c2-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['recursion'],
          prompt: 'def fib(n):\n  if n <= 1: return n\n  return fib(n-1) + fib(n-2)\nWhat is fib(5)?',
          options: ['5', '8', '13', '3'],
          answerIndex: 0,
          explanation: 'Fibonacci: 0,1,1,2,3,5 — fib(5) = 5 (0-indexed definition here).',
        },
        {
          id: 'l12-c2-e3',
          type: 'fixTheLine',
          stage: 'stretch',
          tags: ['recursion'],
          prompt: 'Which line prevents progress toward the base case?',
          code: 'def bad(n):\n    if n == 0:\n        return 0\n    return bad(n)',
          lineOptions: [1, 2, 3, 4],
          answerLine: 4,
          explanation: 'bad(n) calls bad(n) with no change — infinite recursion, never reaches n == 0.',
        },
      ],
    },
    {
      id: 'l12-c3',
      title: 'Big-O time complexity',
      objective: 'Classify algorithms as O(1), O(n), O(n²), O(log n).',
      examples: [
        {
          id: 'l12-c3-e1',
          type: 'multipleChoice',
          stage: 'see',
          tags: ['loopLogic'],
          prompt: 'for i in range(n): print(i) — time complexity?',
          options: ['O(n)', 'O(1)', 'O(n²)', 'O(log n)'],
          answerIndex: 0,
          explanation: 'Single loop n times → linear O(n).',
        },
        {
          id: 'l12-c3-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['loopLogic'],
          prompt: 'Nested loops: for i in range(n): for j in range(n): ... — complexity?',
          options: ['O(n²)', 'O(n)', 'O(2n)', 'O(log n)'],
          answerIndex: 0,
          explanation: 'n × n iterations → quadratic O(n²).',
        },
        {
          id: 'l12-c3-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['loopLogic'],
          prompt: 'Binary search on sorted list of size n — average time?',
          options: ['O(log n)', 'O(n)', 'O(n log n)', 'O(1)'],
          answerIndex: 0,
          explanation: 'Each step halves search space → logarithmic O(log n).',
        },
      ],
    },
    {
      id: 'l12-c4',
      title: 'Space & recursion vs iteration',
      objective: 'Compare stack space and choose iterative alternatives.',
      examples: [
        {
          id: 'l12-c4-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['recursion'],
          prompt: 'Compare recursive vs iterative sum.',
          code: 'def rec_sum(n):\n    if n == 0:\n        return 0\n    return n + rec_sum(n - 1)\n\ndef iter_sum(n):\n    total = 0\n    for i in range(1, n + 1):\n        total += i\n    return total\n\na = rec_sum(5)\nb = iter_sum(5)',
          steps: [
            { line: 1, vars: {} },
            { line: 12, vars: { a: '15', b: '15' } },
          ],
          question: 'What is b?',
          options: ['15', '16', '14', '30'],
          answerIndex: 0,
          explanation: '1+2+3+4+5 = 15; both approaches yield same result.',
        },
        {
          id: 'l12-c4-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['recursion'],
          prompt: 'Recursive fact(n) uses O(?) extra call-stack space.',
          options: ['O(n)', 'O(1)', 'O(n²)', 'O(log n)'],
          answerIndex: 0,
          explanation: 'n nested calls before base case → O(n) stack depth.',
        },
        {
          id: 'l12-c4-e3',
          type: 'fillBlank',
          stage: 'stretch',
          tags: ['loopLogic'],
          prompt: 'A loop that halves n each iteration (while n > 1: n //= 2) is O(____).',
          code: '# loop body runs about log2(n) times',
          blankLabel: 'complexity',
          options: ['log n', 'log nx', 'LOG N', 'pass'],
          answerIndex: 0,
          explanation: 'Halving each step → logarithmic number of iterations.',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l12-check-1',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['recursion'],
      prompt: 'Which has a correct base case?\nA) def f(n): return f(n-1)\nB) def g(n): return 1 if n==0 else g(n-1)',
      options: ['B only', 'A only', 'Both', 'Neither'],
      answerIndex: 0,
      explanation: 'g stops at n==0; f never stops when n starts positive.',
    },
    {
      id: 'l12-check-2',
      type: 'traceSteps',
      stage: 'stretch',
      tags: ['recursion'],
      prompt: 'Trace recursive length.',
      code: 'def rlen(s):\n    if s == "":\n        return 0\n    return 1 + rlen(s[1:])\n\nn = rlen("cat")',
      steps: [
        { line: 1, vars: {} },
        { line: 5, vars: { n: '3' } },
      ],
      question: 'What is n?',
      options: ['3', '4', '2', '6'],
          answerIndex: 0,
          explanation: '1 + rlen("at") + ... + rlen("") → 3.',
    },
    {
      id: 'l12-check-3',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['loopLogic'],
      prompt: 'Best Big-O for checking if x in a Python list of length n?',
      options: ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'],
      answerIndex: 0,
      explanation: 'List membership scans sequentially — O(n) worst case.',
    },
    {
      id: 'l12-check-4',
      type: 'fixTheLine',
      stage: 'stretch',
      tags: ['recursion'],
      prompt: 'Which line never moves n toward the base case?',
      code: 'def repeat(n):\n    if n == 0:\n        return "done"\n    return repeat(n)',
      lineOptions: [1, 2, 3, 4],
      answerLine: 4,
      explanation: 'repeat(n) calls itself with the same n — infinite recursion until RecursionError.',
    },
  ],
};
