import type { Lesson } from '../schema';

export const lesson08: Lesson = {
  id: 'lesson08',
  title: 'Dicts & Sets',
  subtitle: 'Mappings, keys, uniqueness, and lookups',
  objectives: [
    'Create dicts and access values by key',
    'Know which objects are valid dict keys',
    'Add, update, and remove dict entries safely',
    'Use sets for uniqueness and membership tests',
  ],
  concepts: [
    {
      id: 'l8-c1',
      title: 'Dictionary basics',
      objective: 'Map keys to values with {} or dict() and bracket lookup.',
      examples: [
        {
          id: 'l8-c1-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['dictKeys'],
          prompt: 'Step through dict creation and lookup.',
          code: 'scores = {"Ada": 95, "Grace": 88}\na = scores["Ada"]\nb = scores.get("Grace")\nc = scores.get("Lin", 0)',
          steps: [
            { line: 1, vars: { scores: '{"Ada": 95, "Grace": 88}' } },
            { line: 2, vars: { scores: '{"Ada": 95, "Grace": 88}', a: '95' } },
            { line: 3, vars: { scores: '{"Ada": 95, "Grace": 88}', a: '95', b: '88' } },
            { line: 4, vars: { scores: '{"Ada": 95, "Grace": 88}', a: '95', b: '88', c: '0' } },
          ],
          question: 'What is c?',
          options: ['0', '1', '-1', '2'],
          answerIndex: 0,
          explanation: 'get("Lin", 0) returns default 0 when key "Lin" is missing.',
        },
        {
          id: 'l8-c1-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['dictKeys'],
          prompt: 'scores["Bob"] when "Bob" is not a key — what happens?',
          options: ['Returns None', 'Returns 0', 'KeyError', 'SyntaxError'],
          answerIndex: 2,
          explanation: 'Bracket lookup raises KeyError for missing keys; use .get() for safe access.',
        },
        {
          id: 'l8-c1-e3',
          type: 'fillBlank',
          stage: 'stretch',
          tags: ['dictKeys'],
          prompt: 'Fill in to add key "x" with value 10 to d.',
          code: 'd = {"a": 1}\n____',
          blankLabel: 'assignment',
          options: ['d["x"] = 10', 'd["x"] = 10x', 'D["X"] = 10', 'pass'],
          answerIndex: 0,
          explanation: 'Assigning to d[new_key] inserts or updates that entry.',
        },
      ],
    },
    {
      id: 'l8-c2',
      title: 'Keys & membership',
      objective: 'Keys must be hashable; test with in on keys not values by default.',
      miniNote: 'Lists are not valid keys; tuples of immutables are.',
      examples: [
        {
          id: 'l8-c2-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['dictKeys'],
          prompt: 'Trace key membership with in.',
          code: 'cap = {"FR": "Paris", "DE": "Berlin"}\nhas_fr = "FR" in cap\nhas_rome = "Rome" in cap',
          steps: [
            { line: 1, vars: { cap: '{"FR": "Paris", "DE": "Berlin"}' } },
            { line: 2, vars: { cap: '{"FR": "Paris", "DE": "Berlin"}', has_fr: 'True' } },
            { line: 3, vars: { cap: '{"FR": "Paris", "DE": "Berlin"}', has_fr: 'True', has_rome: 'False' } },
          ],
          question: 'What is has_rome?',
          options: ['False', 'True', 'None', 'Error'],
          answerIndex: 0,
          explanation: '"Rome" is not a key in cap (it would be a value, not tested by in on dict).',
        },
        {
          id: 'l8-c2-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['dictKeys'],
          prompt: 'Which can be a dict key?',
          options: ['[1, 2]', '(1, 2)', '{1: 2}', '[[1]]'],
          answerIndex: 1,
          explanation: 'Keys must be hashable/immutable. Tuple of ints works; lists and dicts do not.',
        },
        {
          id: 'l8-c2-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['dictKeys'],
          prompt: '"Paris" in cap (from above) tests?',
          options: ['Whether "Paris" is a key', 'Whether "Paris" is a value', 'Both', 'SyntaxError'],
          answerIndex: 0,
          explanation: 'x in dict checks keys by default, not values. Use cap.values() for value search.',
        },
      ],
    },
    {
      id: 'l8-c3',
      title: 'Mutating dicts',
      objective: 'Update entries, delete keys, and iterate items().',
      examples: [
        {
          id: 'l8-c3-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['mutation', 'dictKeys'],
          prompt: 'Trace update and del.',
          code: 'd = {"a": 1, "b": 2}\nd["a"] = 10\nd["c"] = 3\ndel d["b"]',
          steps: [
            { line: 1, vars: { d: '{"a": 1, "b": 2}' } },
            { line: 2, vars: { d: '{"a": 10, "b": 2}' } },
            { line: 3, vars: { d: '{"a": 10, "b": 2, "c": 3}' } },
            { line: 4, vars: { d: '{"a": 10, "c": 3}' } },
          ],
          question: 'What is d after all lines?',
          options: ['{"a": 10, "c": 3}', '{"a": 1, "c": 3}', '{"a": 10, "b": 2}', '{"a": 10, "b": 2, "c": 3}'],
          answerIndex: 0,
          explanation: '"a" updated, "c" added, "b" removed.',
        },
        {
          id: 'l8-c3-e2',
          type: 'traceSteps',
          stage: 'try',
          tags: ['aliasing', 'mutation'],
          prompt: 'Dict aliasing like lists.',
          code: 'm1 = {"x": 1}\nm2 = m1\nm2["x"] = 99',
          steps: [
            { line: 1, vars: { m1: '{"x": 1}' } },
            { line: 2, vars: { m1: '{"x": 1}', m2: '{"x": 1}' } },
            { line: 3, vars: { m1: '{"x": 99}', m2: '{"x": 99}' } },
          ],
          question: 'What is m1["x"] after line 3?',
          options: ['99', '100', '98', '198'],
          answerIndex: 0,
          explanation: 'm2 aliases m1; updating through either name affects the same dict.',
        },
        {
          id: 'l8-c3-e3',
          type: 'fixTheLine',
          stage: 'stretch',
          tags: ['dictKeys'],
          prompt: 'TypeError: unhashable type list. Which line is the bug?',
          code: 'pairs = {}\nkey = [1, 2]\npairs[key] = "bad"',
          lineOptions: [1, 2, 3],
          answerLine: 3,
          explanation: 'Lists cannot be dict keys. Use tuple (1, 2) instead.',
        },
      ],
    },
    {
      id: 'l8-c4',
      title: 'Sets',
      objective: 'Store unique elements; fast membership with union/intersection.',
      examples: [
        {
          id: 'l8-c4-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: [],
          prompt: 'Trace set deduplication and add.',
          code: 's = {1, 2, 2, 3}\ns.add(3)\ns.add(4)\nlen_s = len(s)',
          steps: [
            { line: 1, vars: { s: '{1, 2, 3}' } },
            { line: 2, vars: { s: '{1, 2, 3}' } },
            { line: 3, vars: { s: '{1, 2, 3, 4}' } },
            { line: 4, vars: { s: '{1, 2, 3, 4}', len_s: '4' } },
          ],
          question: 'What is len_s?',
          options: ['4', '5', '3', '8'],
          answerIndex: 0,
          explanation: 'Literals dedupe; add(3) no-op; add(4) adds new element → 4 unique items.',
        },
        {
          id: 'l8-c4-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: [],
          prompt: '{1, 2} & {2, 3} (intersection) equals?',
          options: ['{1, 2, 3}', '{2}', '{1, 3}', 'Error'],
          answerIndex: 1,
          explanation: 'Intersection contains elements in both sets → {2}.',
        },
        {
          id: 'l8-c4-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['dictKeys'],
          prompt: 'Fast way to remove duplicates from list nums preserving no order guarantee?',
          options: ['list(set(nums))', 'nums.unique()', 'unique(nums)', 'dict(nums)'],
          answerIndex: 0,
          explanation: 'set(nums) removes duplicates; list(...) converts back. Order may change.',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l8-check-1',
      type: 'traceSteps',
      stage: 'stretch',
      tags: ['dictKeys'],
      prompt: 'Lesson check: count with dict.get loop pattern.',
      code: 'counts = {}\nfor ch in "aba":\n    counts[ch] = counts.get(ch, 0) + 1',
      steps: [
        { line: 1, vars: { counts: '{}' } },
        { line: 2, vars: { counts: '{}', ch: '"a"' } },
        { line: 3, vars: { counts: '{"a": 1}', ch: '"a"' } },
        { line: 2, vars: { counts: '{"a": 1}', ch: '"b"' } },
        { line: 3, vars: { counts: '{"a": 1, "b": 1}', ch: '"b"' } },
        { line: 2, vars: { counts: '{"a": 1, "b": 1}', ch: '"a"' } },
        { line: 3, vars: { counts: '{"a": 2, "b": 1}', ch: '"a"' } },
      ],
      question: 'What is counts["a"]?',
      options: ['2', '3', '1', '4'],
          answerIndex: 0,
          explanation: '"a" appears twice in "aba"; get pattern increments correctly.',
    },
    {
      id: 'l8-check-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['dictKeys'],
      prompt: 'list(d) on a dict returns?',
      options: ['All values', 'All keys', 'Key-value pairs', 'Length'],
      answerIndex: 1,
      explanation: 'Iterating a dict yields its keys; list(d) collects them.',
    },
    {
      id: 'l8-check-3',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['mutation'],
      prompt: 'd = {}; d.pop("missing") without default raises?',
      options: ['KeyError', 'Returns None', 'Returns 0', 'IndexError'],
      answerIndex: 0,
      explanation: 'pop on missing key without default raises KeyError, like bracket lookup.',
    },
    {
      id: 'l8-check-4',
      type: 'fixTheLine',
      stage: 'stretch',
      tags: [],
      prompt: 'Empty set should be created but this makes a dict. Which line is wrong?',
      code: 'tags = {}\ntags.add("python")',
      lineOptions: [1, 2],
      answerLine: 1,
      explanation: 'Use tags = set() or tags = {"python"} for sets. {} alone is an empty dict.',
    },
  ],
};
