import type { Lesson } from '../schema';

export const lesson14: Lesson = {
  id: 'lesson14',
  title: 'Python Idioms',
  subtitle: 'enumerate, zip, sorted keys, loop patterns, and practical gotchas',
  objectives: [
    'Use enumerate and zip instead of manual indexing',
    'Sort with sorted(..., key=...) and understand custom keys',
    'Apply loop invariants, continue, and for-else correctly',
    'Iterate dicts with .items() and handle float / module basics',
  ],
  concepts: [
    {
      id: 'l14-c1',
      title: 'enumerate & zip',
      objective: 'Pair indices with values and combine sequences without range(len(...)).',
      miniNote: 'enumerate(seq) yields (index, value). zip(a, b) pairs elements until the shorter ends.',
      examples: [
        {
          id: 'l14-c1-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['loopLogic'],
          prompt: 'Trace enumerate in a for loop.',
          code: 'words = ["a", "b"]\nfirst_idx = None\nfor i, w in enumerate(words):\n    if w == "b":\n        first_idx = i',
          steps: [
            { line: 1, vars: { words: '["a", "b"]' } },
            { line: 3, vars: { words: '["a", "b"]', i: '0', w: '"a"' } },
            { line: 3, vars: { words: '["a", "b"]', i: '1', w: '"b"' } },
            { line: 4, vars: { words: '["a", "b"]', i: '1', w: '"b"', first_idx: '1' } },
          ],
          question: 'What is first_idx?',
          options: ['1', '0', '2', 'None'],
          answerIndex: 0,
          explanation: 'enumerate yields (0,"a") then (1,"b"); w=="b" on second iteration sets first_idx=1.',
        },
        {
          id: 'l14-c1-e2',
          type: 'traceSteps',
          stage: 'see',
          tags: ['loopLogic'],
          prompt: 'Trace zip on two lists.',
          code: 'names = ["Ada", "Grace"]\nscores = [95, 88]\npairs = list(zip(names, scores))',
          steps: [
            { line: 1, vars: { names: '["Ada", "Grace"]' } },
            { line: 2, vars: { names: '["Ada", "Grace"]', scores: '[95, 88]' } },
            { line: 3, vars: { names: '["Ada", "Grace"]', scores: '[95, 88]', pairs: '[("Ada", 95), ("Grace", 88)]' } },
          ],
          question: 'What is pairs?',
          options: [
            '[("Ada", 95), ("Grace", 88)]',
            '["Ada", "Grace"]',
            '[95, 88]',
            '[("Ada", "Grace"), (95, 88)]',
          ],
          answerIndex: 0,
          explanation: 'zip pairs elements position-by-position into tuples.',
        },
        {
          id: 'l14-c1-e3',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['loopLogic', 'offByOne'],
          prompt: 'Which replaces the anti-pattern for i in range(len(xs)): print(i, xs[i])?',
          options: [
            'for x in xs: print(x)',
            'for i, x in enumerate(xs): print(i, x)',
            'for i in xs: print(i)',
            'while xs: print(xs)',
          ],
          answerIndex: 1,
          explanation: 'enumerate gives index and value without manual subscripting.',
        },
        {
          id: 'l14-c1-e4',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['loopLogic'],
          prompt: 'list(zip([1,2], [10,20,30])) equals?',
          options: ['[(1, 10), (2, 20)]', '[(1, 10), (2, 20), (None, 30)]', '[(1, 2), (10, 20)]', 'Error'],
          answerIndex: 0,
          explanation: 'zip stops at the shorter iterable — two pairs only.',
        },
      ],
    },
    {
      id: 'l14-c2',
      title: 'sorted with key=',
      objective: 'Sort by a derived value using key functions.',
      miniNote: 'sorted(items, key=len) sorts by length. key=str.lower ignores case for strings.',
      examples: [
        {
          id: 'l14-c2-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['sortedKey'],
          prompt: 'Trace sorted by length.',
          code: 'words = ["hi", "a", "bye"]\nresult = sorted(words, key=len)',
          steps: [
            { line: 1, vars: { words: '["hi", "a", "bye"]' } },
            { line: 2, vars: { words: '["hi", "a", "bye"]', result: '["a", "hi", "bye"]' } },
          ],
          question: 'What is result?',
          options: ['["a", "hi", "bye"]', '["bye", "hi", "a"]', '["a", "bye", "hi"]', '["hi", "a", "bye"]'],
          answerIndex: 0,
          explanation: 'Lengths 1, 2, 3 → order "a", "hi", "bye". Original words unchanged.',
        },
        {
          id: 'l14-c2-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['sortedKey'],
          prompt: 'Sort dict items by value descending. Best approach?',
          options: [
            'sorted(d)',
            'sorted(d.items(), key=lambda kv: kv[1], reverse=True)',
            'd.sort()',
            'sorted(d.values())',
          ],
          answerIndex: 1,
          explanation: 'd.items() gives (key,value) pairs; key selects value for comparison.',
        },
        {
          id: 'l14-c2-e3',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['sortedKey', 'comprehension'],
          prompt: 'What does sorted(["Banana", "apple"], key=str.lower) produce?',
          options: ['["apple", "Banana"]', '["Banana", "apple"]', '["APPLE", "banana"]', 'Error'],
          answerIndex: 0,
          explanation: 'key=str.lower compares case-insensitively → apple before Banana.',
        },
        {
          id: 'l14-c2-e4',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['sortedKey'],
          prompt: 'sorted(L) vs L.sort() — which returns a new list?',
          options: ['sorted(L) only', 'L.sort() only', 'Both', 'Neither'],
          answerIndex: 0,
          explanation: 'sorted returns new list; .sort() mutates L in place and returns None.',
        },
      ],
    },
    {
      id: 'l14-c3',
      title: 'Loop invariants, continue & for-else',
      objective: 'Reason about what stays true each iteration; use continue and else on loops.',
      miniNote: 'Loop else runs only if the loop did NOT exit via break. Invariant: e.g. "i is always 0..len-1".',
      examples: [
        {
          id: 'l14-c3-e1',
          type: 'multipleChoice',
          stage: 'see',
          tags: ['loopInvariant'],
          prompt: 'Loop: for i in range(n): total += i. Invariant after each iteration?',
          options: [
            'total equals sum of all integers seen so far in the loop',
            'i is always equal to total',
            'total is always 0',
            'n decreases each time',
          ],
          answerIndex: 0,
          explanation: 'Invariant: total accumulates the sum of i values processed — helps verify off-by-one fixes.',
        },
        {
          id: 'l14-c3-e2',
          type: 'traceSteps',
          stage: 'see',
          tags: ['loopLogic'],
          prompt: 'Trace continue skipping an iteration.',
          code: 'out = []\nfor n in [1, 2, 3, 4]:\n    if n % 2 == 0:\n        continue\n    out.append(n)',
          steps: [
            { line: 1, vars: { out: '[]' } },
            { line: 2, vars: { out: '[]', n: '1' } },
            { line: 4, vars: { out: '[1]', n: '1' } },
            { line: 2, vars: { out: '[1]', n: '2' } },
            { line: 2, vars: { out: '[1]', n: '3' } },
            { line: 4, vars: { out: '[1, 3]', n: '3' } },
            { line: 2, vars: { out: '[1, 3]', n: '4' } },
          ],
          question: 'What is out?',
          options: ['[1, 3]', '[1, 2, 3, 4]', '[2, 4]', '[1]'],
          answerIndex: 0,
          explanation: 'continue skips append on even n — only odds 1 and 3 collected.',
        },
        {
          id: 'l14-c3-e3',
          type: 'traceSteps',
          stage: 'try',
          tags: ['loopLogic'],
          prompt: 'Trace for-else: else runs when no break.',
          code: 'nums = [2, 4, 6]\nfound = False\nfor n in nums:\n    if n % 2 == 1:\n        found = True\n        break\nelse:\n    found = True',
          steps: [
            { line: 1, vars: { nums: '[2, 4, 6]' } },
            { line: 2, vars: { nums: '[2, 4, 6]', found: 'False' } },
            { line: 3, vars: { nums: '[2, 4, 6]', found: 'False', n: '2' } },
            { line: 3, vars: { nums: '[2, 4, 6]', found: 'False', n: '4' } },
            { line: 3, vars: { nums: '[2, 4, 6]', found: 'False', n: '6' } },
            { line: 8, vars: { nums: '[2, 4, 6]', found: 'True' } },
          ],
          question: 'What is found after the loop?',
          options: ['True', 'False', 'None', 'Error'],
          answerIndex: 0,
          explanation: 'No odd number → no break → else clause runs and sets found True.',
        },
        {
          id: 'l14-c3-e4',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['loopLogic'],
          prompt: 'When does a for loop\'s else block execute?',
          options: [
            'Always after the loop body',
            'Only if the loop completed without break',
            'Only if break was used',
            'Never — for loops have no else',
          ],
          answerIndex: 1,
          explanation: 'for-else: else runs on normal completion; skipped if break exits the loop.',
        },
      ],
    },
    {
      id: 'l14-c4',
      title: 'Dict iteration & scope keywords',
      objective: 'Loop over .items(); use global/nonlocal when assignment must escape a function.',
      miniNote: 'for k, v in d.items(): — default iteration is over keys only. global/nonlocal declare which binding to assign.',
      examples: [
        {
          id: 'l14-c4-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['dictKeys'],
          prompt: 'Trace looping with .items().',
          code: 'd = {"a": 1, "b": 2}\ntotal = 0\nfor k, v in d.items():\n    total += v',
          steps: [
            { line: 1, vars: { d: '{"a": 1, "b": 2}' } },
            { line: 2, vars: { d: '{"a": 1, "b": 2}', total: '0' } },
            { line: 3, vars: { d: '{"a": 1, "b": 2}', total: '0', k: '"a"', v: '1' } },
            { line: 4, vars: { d: '{"a": 1, "b": 2}', total: '1', k: '"a"', v: '1' } },
            { line: 3, vars: { d: '{"a": 1, "b": 2}', total: '1', k: '"b"', v: '2' } },
            { line: 4, vars: { d: '{"a": 1, "b": 2}', total: '3', k: '"b"', v: '2' } },
          ],
          question: 'What is total?',
          options: ['3', '2', '1', '0'],
          answerIndex: 0,
          explanation: 'Sum of values 1 + 2 = 3.',
        },
        {
          id: 'l14-c4-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['dictKeys'],
          prompt: 'for x in d: iterates over…',
          options: ['keys of d', 'values of d', 'key-value pairs', 'sorted values'],
          answerIndex: 0,
          explanation: 'Default dict iteration yields keys. Use .values() or .items() for other views.',
        },
        {
          id: 'l14-c4-e3',
          type: 'traceSteps',
          stage: 'try',
          tags: ['scope'],
          prompt: 'Trace global assignment.',
          code: 'count = 0\ndef inc():\n    global count\n    count = count + 1\n\ninc()\ninc()',
          steps: [
            { line: 1, vars: { count: '0' } },
            { line: 2, vars: { count: '0' } },
            { line: 5, vars: { count: '0' } },
            { line: 4, vars: { count: '1' } },
            { line: 5, vars: { count: '1' } },
            { line: 4, vars: { count: '2' } },
          ],
          question: 'What is count after both calls?',
          options: ['2', '1', '0', 'Error'],
          answerIndex: 0,
          explanation: 'global count binds assignment to module-level count → increments twice.',
        },
        {
          id: 'l14-c4-e4',
          type: 'fixTheLine',
          stage: 'debug',
          tags: ['scope'],
          prompt: 'UnboundLocalError on count. Which line needs global?',
          code: 'count = 0\ndef inc():\n    count = count + 1\n\ninc()',
          lineOptions: [1, 2, 3, 4],
          answerLine: 3,
          explanation: 'Assignment makes count local; reading it before assign fails. Add global count on line 3.',
        },
      ],
    },
    {
      id: 'l14-c5',
      title: 'Floats, modules & search',
      objective: 'Know float surprises, __name__ guard, light functional patterns, binary search idea.',
      miniNote: '0.1 + 0.2 != 0.3 exactly. if __name__ == "__main__": runs only when file is executed directly.',
      examples: [
        {
          id: 'l14-c5-e1',
          type: 'multipleChoice',
          stage: 'see',
          tags: ['floatPrecision'],
          prompt: 'What is (0.1 + 0.2 == 0.3) in Python?',
          options: ['False', 'True', 'None', 'Error'],
          answerIndex: 0,
          explanation: 'Binary floating point cannot represent 0.1 exactly — sum is close but not == 0.3.',
        },
        {
          id: 'l14-c5-e2',
          type: 'multipleChoice',
          stage: 'see',
          tags: ['moduleMain'],
          prompt: 'What does if __name__ == "__main__": guard?',
          options: [
            'Code that runs only when the file is run directly (not imported)',
            'Code that runs only on import',
            'Private class methods',
            'Main memory allocation',
          ],
          answerIndex: 0,
          explanation: '__name__ is "__main__" when executed as script; module name when imported.',
        },
        {
          id: 'l14-c5-e3',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['comprehension'],
          prompt: '[x * 2 for x in range(3)] is equivalent to…',
          options: [
            'list(map(lambda x: x * 2, range(3)))',
            'map(lambda x: x * 2, range(3))',
            'filter(lambda x: x * 2, range(3))',
            'sorted(range(3), key=lambda x: x * 2)',
          ],
          answerIndex: 0,
          explanation: 'map applies function to each element; list() collects — same as comprehension here.',
        },
        {
          id: 'l14-c5-e4',
          type: 'traceSteps',
          stage: 'try',
          tags: ['loopLogic', 'recursion'],
          prompt: 'Trace binary search on sorted list (conceptual).',
          code: 'nums = [2, 5, 8, 12, 16]\ntarget = 12\nlo, hi = 0, 4\nmid = (lo + hi) // 2\n# nums[mid] == 8, target > 8\nlo = mid + 1\nmid = (lo + hi) // 2',
          steps: [
            { line: 1, vars: { nums: '[2,5,8,12,16]' } },
            { line: 2, vars: { nums: '[2,5,8,12,16]', target: '12' } },
            { line: 3, vars: { lo: '0', hi: '4' } },
            { line: 4, vars: { lo: '0', hi: '4', mid: '2' } },
            { line: 6, vars: { lo: '3', hi: '4', mid: '2' } },
            { line: 7, vars: { lo: '3', hi: '4', mid: '3' } },
          ],
          question: 'After line 7, nums[mid] equals?',
          options: ['12', '8', '16', '5'],
          answerIndex: 0,
          explanation: 'Second mid is 3; nums[3] is 12 — found target. Halving search space each step → O(log n).',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l14-check-1',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['loopLogic'],
      prompt: 'Lesson check: enumerate(["x","y"]) first tuple is?',
      options: ['(0, "x")', '(1, "x")', '("x", 0)', '(0, 1)'],
      answerIndex: 0,
      explanation: 'enumerate starts index at 0 by default.',
    },
    {
      id: 'l14-check-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['sortedKey'],
      prompt: 'Lesson check: sort words by length ascending — best call?',
      options: ['sorted(words, key=len)', 'words.sort(len)', 'sorted(len(words))', 'sort(words)'],
      answerIndex: 0,
      explanation: 'key=len compares each word by its length.',
    },
    {
      id: 'l14-check-3',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['floatPrecision'],
      prompt: 'Lesson check: safe float comparison often uses…',
      options: ['math.isclose(a, b)', 'a is b', 'str(a) == str(b)', 'int(a) == int(b)'],
      answerIndex: 0,
      explanation: 'math.isclose compares floats within a tolerance instead of exact ==.',
    },
    {
      id: 'l14-check-4',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['loopLogic'],
      prompt: 'Lesson check: binary search requires the list be…',
      options: ['sorted', 'unique', 'all integers', 'reversed'],
      answerIndex: 0,
      explanation: 'Binary search only works on ordered data where halves can be discarded.',
    },
  ],
};
