import type { Lesson } from '../schema';

export const lesson09: Lesson = {
  id: 'lesson09',
  title: 'Comprehensions & Modules',
  subtitle: 'List/dict/set comprehensions, imports, and the standard library',
  objectives: [
    'Build lists, dicts, and sets with comprehensions',
    'Add filters and nested loops in comprehension syntax',
    'Import modules with import, from, and aliases',
    'Use common stdlib modules like math and random',
  ],
  concepts: [
    {
      id: 'l9-c1',
      title: 'List comprehensions',
      objective: 'Translate loops into [expr for item in iterable] form.',
      miniNote: 'Comprehensions create a new list; they do not mutate the source iterable.',
      examples: [
        {
          id: 'l9-c1-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['comprehension'],
          prompt: 'Step through a basic list comprehension.',
          code: 'nums = [1, 2, 3, 4]\nsquares = [n ** 2 for n in nums]',
          steps: [
            { line: 1, vars: { nums: '[1, 2, 3, 4]' } },
            { line: 2, vars: { nums: '[1, 2, 3, 4]', squares: '[1, 4, 9, 16]' } },
          ],
          question: 'What is squares?',
          options: ['[1, 4, 9, 16]', '[1, 2, 3, 4]', '[0, 1, 4, 9]', '[16, 9, 4, 1]'],
          answerIndex: 0,
          explanation: 'Each element is squared: 1², 2², 3², 4².',
        },
        {
          id: 'l9-c1-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['comprehension'],
          prompt: 'What is [x * 2 for x in range(3)]?',
          options: ['[0, 2, 4]', '[2, 4, 6]', '[0, 1, 2]', '[1, 2, 3]'],
          answerIndex: 0,
          explanation: 'range(3) yields 0, 1, 2; each doubled gives [0, 2, 4].',
        },
        {
          id: 'l9-c1-e3',
          type: 'fillBlank',
          stage: 'stretch',
          tags: ['comprehension'],
          prompt: 'Complete the comprehension to keep only even numbers from nums.',
          code: 'nums = [1, 2, 3, 4, 5, 6]\nevens = [n for n in nums if ____]',
          blankLabel: 'condition',
          options: ['n % 2 == 0', 'n % 2 == 0x', 'N % 2 == 0', 'pass'],
          answerIndex: 0,
          explanation: 'The if clause filters: only values where n % 2 == 0 are included.',
        },
      ],
    },
    {
      id: 'l9-c2',
      title: 'Dict & set comprehensions',
      objective: 'Build {key: val for ...} and {expr for ...} collections.',
      examples: [
        {
          id: 'l9-c2-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['comprehension', 'dictKeys'],
          prompt: 'Trace a dict comprehension.',
          code: 'words = ["a", "bb", "ccc"]\nlengths = {w: len(w) for w in words}',
          steps: [
            { line: 1, vars: { words: '["a", "bb", "ccc"]' } },
            { line: 2, vars: { words: '["a", "bb", "ccc"]', lengths: '{"a": 1, "bb": 2, "ccc": 3}' } },
          ],
          question: 'What is lengths["bb"]?',
          options: ['2', '3', '1', '4'],
          answerIndex: 0,
          explanation: 'Dict comprehension maps each word to its length.',
        },
        {
          id: 'l9-c2-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['comprehension'],
          prompt: 'What is {n % 3 for n in range(6)}?',
          options: ['{0, 1, 2}', '[0, 1, 2, 0, 1, 2]', '{0, 1, 2, 3, 4, 5}', 'TypeError'],
          answerIndex: 0,
          explanation: 'Set comprehension deduplicates remainders: 0, 1, 2 only.',
        },
        {
          id: 'l9-c2-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['comprehension', 'dictKeys'],
          prompt: 'Which builds a dict of squares for keys 0–2?',
          options: [
            '{x: x**2 for x in range(3)}',
            '[x: x**2 for x in range(3)]',
            '{x**2 for x in range(3)}',
            'dict(x**2 for x in range(3))',
          ],
          answerIndex: 0,
          explanation: 'Dict comprehension needs key: value pairs inside curly braces.',
        },
      ],
    },
    {
      id: 'l9-c3',
      title: 'Nested & conditional comprehensions',
      objective: 'Combine nested loops and if filters in one expression.',
      examples: [
        {
          id: 'l9-c3-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['comprehension'],
          prompt: 'Trace nested loop comprehension ( Cartesian pairs ).',
          code: 'pairs = [(x, y) for x in [1, 2] for y in [10, 20]]',
          steps: [
            { line: 1, vars: { pairs: '[(1, 10), (1, 20), (2, 10), (2, 20)]' } },
          ],
          question: 'How many elements are in pairs?',
          options: ['4', '5', '3', '8'],
          answerIndex: 0,
          explanation: '2 x values × 2 y values = 4 ordered pairs.',
        },
        {
          id: 'l9-c3-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['comprehension'],
          prompt: 'What is [n for n in range(10) if n % 2 == 0 if n > 4]?',
          options: ['[6, 8]', '[0, 2, 4, 6, 8]', '[5, 7, 9]', '[4, 6, 8]'],
          answerIndex: 0,
          explanation: 'Multiple if clauses are ANDed: even AND greater than 4 → 6, 8.',
        },
        {
          id: 'l9-c3-e3',
          type: 'fixTheLine',
          stage: 'stretch',
          tags: ['comprehension'],
          prompt: 'One line has a syntax error. Which line?',
          code: 'matrix = [[1, 2], [3, 4]]\nflat = [x for row in matrix for x in row]\nwrong = [x for x in row for row in matrix]',
          lineOptions: [1, 2, 3],
          answerLine: 3,
          wrongOutput: 'Uses row before it is defined in the inner loop.',
          explanation: 'Loop order matters: outer loop (row in matrix) must come before inner (x in row).',
        },
      ],
    },
    {
      id: 'l9-c4',
      title: 'Modules & imports',
      objective: 'Import modules, names, and use qualified access.',
      examples: [
        {
          id: 'l9-c4-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['scope'],
          prompt: 'Trace import and qualified name access.',
          code: 'import math\nr = math.sqrt(16)\npi_val = math.pi',
          steps: [
            { line: 1, vars: {} },
            { line: 2, vars: { r: '4.0' } },
            { line: 3, vars: { r: '4.0', pi_val: '3.141592653589793' } },
          ],
          question: 'What is r?',
          options: ['4.0', '5', '3', '8'],
          answerIndex: 0,
          explanation: 'math.sqrt(16) returns float 4.0.',
        },
        {
          id: 'l9-c4-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['scope'],
          prompt: 'After `from random import randint`, how do you call it?',
          options: ['random.randint(1, 6)', 'randint(1, 6)', 'import randint(1, 6)', 'random(1, 6)'],
          answerIndex: 1,
          explanation: 'from ... import brings the name into the current namespace directly.',
        },
        {
          id: 'l9-c4-e3',
          type: 'fillBlank',
          stage: 'stretch',
          tags: ['scope'],
          prompt: 'Import sqrt from math so the next line works.',
          code: '____\nprint(sqrt(25))',
          blankLabel: 'import statement',
          options: ['from math import sqrt', 'from math import sqrtx', 'FROM MATH IMPORT SQRT', 'pass'],
          answerIndex: 0,
          explanation: 'from math import sqrt binds sqrt in the current module scope.',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l9-check-1',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['comprehension'],
      prompt: 'What is [c.upper() for c in "hi"]?',
      options: ['["H", "I"]', '["h", "i"]', '"HI"', '["HI"]'],
      answerIndex: 0,
      explanation: 'Iterating a string yields characters; upper() on each gives ["H", "I"].',
    },
    {
      id: 'l9-check-2',
      type: 'traceSteps',
      stage: 'stretch',
      tags: ['comprehension'],
      prompt: 'Trace filtered comprehension.',
      code: 'data = [1, -2, 3, -4]\npos = [n for n in data if n > 0]',
      steps: [
        { line: 1, vars: { data: '[1, -2, 3, -4]' } },
        { line: 2, vars: { data: '[1, -2, 3, -4]', pos: '[1, 3]' } },
      ],
      question: 'What is pos?',
      options: ['[1, 3]', '[3, 1]', '[1, 2, 3]', '[0, 1, 3]'],
          answerIndex: 0,
          explanation: 'Only positive values pass the filter.',
    },
    {
      id: 'l9-check-3',
      type: 'fixTheLine',
      stage: 'stretch',
      tags: ['scope'],
      prompt: 'Which line causes NameError when run?',
      code: 'import math\nprint(pi)\nprint(math.pi)',
      lineOptions: [1, 2, 3],
      answerLine: 2,
      explanation: 'import math does not bind pi locally; use math.pi or from math import pi.',
    },
    {
      id: 'l9-check-4',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['comprehension'],
      prompt: 'Equivalent to list(map(lambda x: x*2, [1,2,3]))?',
      options: ['[x*2 for x in [1,2,3]]', '[2*x for x in 3]', 'map(x*2, [1,2,3])', '[1,2,3]*2'],
      answerIndex: 0,
      explanation: 'List comprehension [x*2 for x in [1,2,3]] → [2, 4, 6].',
    },
  ],
};
