import type { Lesson } from '../schema';

export const lesson11: Lesson = {
  id: 'lesson11',
  title: 'Object-Oriented Python',
  subtitle: 'Classes, self, instance vs class attributes, inheritance',
  objectives: [
    'Define classes with __init__ and instance methods',
    'Use self correctly to access instance state',
    'Distinguish class attributes from instance attributes',
    'Subclass and override methods with super()',
  ],
  concepts: [
    {
      id: 'l11-c1',
      title: 'Classes & __init__',
      objective: 'Create objects and initialize instance attributes.',
      miniNote: '__init__ is the initializer, not a constructor — object exists before __init__ runs.',
      examples: [
        {
          id: 'l11-c1-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['oopAttrs'],
          prompt: 'Trace object creation and __init__.',
          code: 'class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\np = Point(3, 4)',
          steps: [
            { line: 1, vars: {} },
            { line: 5, vars: { p: 'Point(3, 4)' } },
          ],
          question: 'What is p.x?',
          options: ['3', '4', '2', '6'],
          answerIndex: 0,
          explanation: '__init__ binds self.x = 3 and self.y = 4 on the new instance.',
        },
        {
          id: 'l11-c1-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['oopAttrs'],
          prompt: 'What is self in a method definition?',
          options: [
            'Reference to the instance the method was called on',
            'A Python keyword like True',
            'The class object itself',
            'Always the first argument name but unused',
          ],
          answerIndex: 0,
          explanation: 'self is convention for the instance; Python passes it automatically.',
        },
        {
          id: 'l11-c1-e3',
          type: 'fillBlank',
          stage: 'stretch',
          tags: ['oopAttrs'],
          prompt: 'Complete the method to return the stored name.',
          code: 'class Dog:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return self.____ + "!"',
          blankLabel: 'attribute',
          options: ['name', 'namex', 'NAME', 'pass'],
          answerIndex: 0,
          explanation: 'Instance attribute set in __init__ is accessed via self.name.',
        },
      ],
    },
    {
      id: 'l11-c2',
      title: 'Instance methods & self',
      objective: 'Call methods and predict how self binds attributes.',
      examples: [
        {
          id: 'l11-c2-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['oopAttrs'],
          prompt: 'Trace method call modifying state.',
          code: 'class Counter:\n    def __init__(self):\n        self.count = 0\n    def bump(self):\n        self.count += 1\n\nc = Counter()\nc.bump()\nc.bump()',
          steps: [
            { line: 1, vars: {} },
            { line: 7, vars: { c: 'Counter()' } },
            { line: 8, vars: { c: 'Counter(), count=1' } },
            { line: 9, vars: { c: 'Counter(), count=2' } },
          ],
          question: 'What is c.count?',
          options: ['2', '3', '1', '4'],
          answerIndex: 0,
          explanation: 'Each bump() increments the instance count by 1.',
        },
        {
          id: 'l11-c2-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['oopAttrs'],
          prompt: 'Counter.bump(c) vs c.bump() — which is valid?',
          options: [
            'Both equivalent if bump defined with self',
            'Only Counter.bump(c)',
            'Only c.bump()',
            'Neither — methods cannot take self',
          ],
          answerIndex: 0,
          explanation: 'c.bump() is syntactic sugar for Counter.bump(c).',
        },
        {
          id: 'l11-c2-e3',
          type: 'fixTheLine',
          stage: 'stretch',
          tags: ['oopAttrs'],
          prompt: 'Which line causes TypeError when creating Rectangle(5, 10)?',
          code: 'class Rectangle:\n    def __init__(self, w, h):\n        self.w = w\n        self.h = h\n    def area(self):\n        return w * h',
          lineOptions: [1, 2, 3, 4, 5],
          answerLine: 5,
          explanation: 'area must use self.w and self.h — bare w and h are undefined local names.',
        },
      ],
    },
    {
      id: 'l11-c3',
      title: 'Class vs instance attributes',
      objective: 'Predict shared class state vs per-instance state.',
      examples: [
        {
          id: 'l11-c3-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['oopAttrs', 'mutation'],
          prompt: 'Trace class attribute shared across instances.',
          code: 'class Team:\n    motto = "Go!"\n\nt1 = Team()\nt2 = Team()\nt1.motto = "Win!"\nshared = t2.motto',
          steps: [
            { line: 1, vars: {} },
            { line: 4, vars: { t1: 'Team()', t2: 'Team()' } },
            { line: 5, vars: { t1: 'Team(), motto="Win!"', t2: 'Team()' } },
            { line: 6, vars: { t1: 'Team(), motto="Win!"', t2: 'Team()', shared: '"Go!"' } },
          ],
          question: 'What is shared?',
          options: ['"Go!"', '"Go"', '"Go!X"', '"GO!"'],
          answerIndex: 0,
          explanation: 't1.motto = "Win!" creates instance attr; t2 still sees class attr "Go!".',
        },
        {
          id: 'l11-c3-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['oopAttrs'],
          prompt: 'Class attribute mutated in place (e.g. list.append) affects?',
          options: [
            'All instances unless shadowed by instance attr',
            'Only the instance that called append',
            'No instances — class attrs are read-only',
            'Only future instances',
          ],
          answerIndex: 0,
          explanation: 'Mutable class attrs are shared; in-place mutation visible to all unless overridden.',
        },
        {
          id: 'l11-c3-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['oopAttrs', 'mutation'],
          prompt: 'After:\nclass A: items = []\na = A(); b = A()\na.items.append(1)\nWhat is b.items?',
          options: ['[1]', '[]', 'Error', 'None'],
          answerIndex: 0,
          explanation: 'Default mutable class attr is one shared list — classic OOP trap.',
          trapNote: 'Use instance attrs in __init__ for per-object mutable defaults.',
        },
      ],
    },
    {
      id: 'l11-c4',
      title: 'Inheritance & super()',
      objective: 'Subclass, override methods, and extend parent behavior.',
      examples: [
        {
          id: 'l11-c4-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['oopAttrs'],
          prompt: 'Trace inheritance and method override.',
          code: 'class Animal:\n    def speak(self):\n        return "..."\n\nclass Dog(Animal):\n    def speak(self):\n        return "woof"\n\nd = Dog()\ns = d.speak()',
          steps: [
            { line: 1, vars: {} },
            { line: 9, vars: { d: 'Dog()' } },
            { line: 10, vars: { d: 'Dog()', s: '"woof"' } },
          ],
          question: 'What is s?',
          options: ['"woof"', '"woo"', '"woofX"', '"WOOF"'],
          answerIndex: 0,
          explanation: 'Dog.speak overrides Animal.speak on Dog instances.',
        },
        {
          id: 'l11-c4-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['oopAttrs'],
          prompt: 'Purpose of super().__init__(...) in a subclass?',
          options: [
            'Run parent initializer on the same instance',
            'Create a separate parent object',
            'Copy parent class attributes only',
            'Required or class cannot be defined',
          ],
          answerIndex: 0,
          explanation: 'super().__init__ delegates to parent __init__ so inherited setup runs.',
        },
        {
          id: 'l11-c4-e3',
          type: 'fixTheLine',
          stage: 'stretch',
          tags: ['oopAttrs'],
          prompt: 'Which line fails to store sid on the instance?',
          code: 'class Person:\n    def __init__(self, name):\n        self.name = name\n\nclass Student(Person):\n    def __init__(self, name, sid):\n        super().__init__(name)\n        sid = sid',
          lineOptions: [1, 2, 3, 4, 5, 6, 7],
          answerLine: 7,
          explanation: 'sid = sid assigns to a local variable; use self.sid = sid to set the instance attribute.',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l11-check-1',
      type: 'traceSteps',
      stage: 'stretch',
      tags: ['oopAttrs'],
      prompt: 'Trace isinstance and inheritance.',
      code: 'class Animal:\n    pass\n\nclass Cat(Animal):\n    pass\n\nc = Cat()\nok = isinstance(c, Animal)',
      steps: [
        { line: 1, vars: {} },
        { line: 7, vars: { c: 'Cat()' } },
        { line: 8, vars: { c: 'Cat()', ok: 'True' } },
      ],
      question: 'What is ok?',
      options: ['True', 'False', 'None', 'Error'],
          answerIndex: 0,
          explanation: 'Subclass instances are isinstance of parent classes.',
    },
    {
      id: 'l11-check-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['oopAttrs'],
      prompt: 'Which finds attribute on instance then class (MRO)?',
      options: ['obj.attr lookup', 'Class.attr only', 'self only in __init__', 'import attr'],
      answerIndex: 0,
      explanation: 'Attribute lookup searches instance dict, then class hierarchy (MRO).',
    },
    {
      id: 'l11-check-3',
      type: 'fixTheLine',
      stage: 'stretch',
      tags: ['oopAttrs'],
      prompt: 'Which line is wrong for a valid instance method?',
      code: 'class BankAccount:\n    def __init__(self, balance=0):\n        self.balance = balance\n    def deposit(self, amount):\n        balance += amount\n    def get_balance(self):\n        return self.balance',
      lineOptions: [1, 2, 3, 4, 5],
      answerLine: 4,
      explanation: 'Must use self.balance += amount; balance alone creates/uses a local variable.',
    },
    {
      id: 'l11-check-4',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['oopAttrs'],
      prompt: 'class Child(Parent): pass — Child.__bases__ is?',
      options: ['(Parent,)', '(Child,)', '()', '(object, Parent)'],
      answerIndex: 0,
      explanation: '__bases__ tuple lists direct parent classes.',
    },
  ],
};
