import type { Lesson } from '../schema';

export const lesson16: Lesson = {
  id: 'lesson16',
  title: 'Modern Intro Python',
  subtitle: 'Generators, unpacking, hints, patterns, and classic algorithms',
  objectives: [
    'Explain yield, generators, and lazy iteration vs building a list',
    'Use *args, **kwargs, and unpacking in calls and definitions',
    'Apply nonlocal, docstrings, type hints, and match/case at intro depth',
    'Trace selection sort and use collections.Counter',
  ],
  concepts: [
    {
      id: 'l16-c1',
      title: 'Generators & yield',
      objective: 'Write a simple generator function; know it produces values on demand.',
      miniNote: 'yield pauses the function and produces a value; next() resumes. Generators save memory on large sequences.',
      examples: [
        {
          id: 'l16-c1-e1',
          type: 'multipleChoice',
          stage: 'see',
          tags: ['generators'],
          prompt: 'A function containing yield is called a…',
          options: ['Generator function', 'Recursive function', 'Lambda', 'Property'],
          answerIndex: 0,
          explanation: 'Calling it returns a generator object — an iterator.',
        },
        {
          id: 'l16-c1-e2',
          type: 'traceSteps',
          stage: 'see',
          tags: ['generators'],
          prompt: 'Trace a tiny generator.',
          code: 'def gen():\n    yield 1\n    yield 2\n\ng = gen()\na = next(g)\nb = next(g)',
          steps: [
            { line: 1, vars: {} },
            { line: 5, vars: { g: '<generator>' } },
            { line: 6, vars: { g: '<generator>', a: '1' } },
            { line: 7, vars: { g: '<generator>', a: '1', b: '2' } },
          ],
          question: 'What are a and b?',
          options: ['a=1, b=2', 'a=2, b=1', 'a=[1,2], b=None', 'Error on line 6'],
          answerIndex: 0,
          explanation: 'Each next() runs until the next yield and returns that value.',
        },
        {
          id: 'l16-c1-e3',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['generators', 'comprehension'],
          prompt: '(x * 2 for x in range(3)) is a…',
          options: ['Generator expression', 'Tuple', 'List', 'Set'],
          answerIndex: 0,
          explanation: 'Parentheses with comprehension syntax → generator expression (lazy).',
        },
        {
          id: 'l16-c1-e4',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['generators'],
          prompt: 'Main advantage of generator vs list(range(1_000_000))?',
          options: [
            'Produces values one at a time without storing all in memory',
            'Always faster to write',
            'Can only hold integers',
            'Cannot be used in for loops',
          ],
          answerIndex: 0,
          explanation: 'Lazy iteration — O(1) extra memory for the generator object.',
        },
      ],
    },
    {
      id: 'l16-c2',
      title: '*args, **kwargs & unpacking',
      objective: 'Pass and collect variable numbers of positional and keyword arguments.',
      miniNote: '* in a call unpacks a sequence; ** unpacks a dict of keyword args. def f(*args): collects extras as tuple.',
      examples: [
        {
          id: 'l16-c2-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['unpacking', 'scope'],
          prompt: 'Trace *args in a function.',
          code: 'def total(*args):\n    s = 0\n    for x in args:\n        s += x\n    return s\n\nr = total(1, 2, 3)',
          steps: [
            { line: 1, vars: {} },
            { line: 6, vars: { args: '(1, 2, 3)' } },
            { line: 6, vars: { r: '6' } },
          ],
          question: 'What is r?',
          options: ['6', '3', '(1, 2, 3)', 'Error'],
          answerIndex: 0,
          explanation: '*args bundles 1,2,3 into a tuple; loop sums to 6.',
        },
        {
          id: 'l16-c2-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['unpacking'],
          prompt: 'print(*["a", "b"]) is equivalent to…',
          options: ['print("a", "b")', 'print(["a", "b"])', 'print("a", "b", sep="")', 'SyntaxError always'],
          answerIndex: 0,
          explanation: 'Unpacking spreads sequence elements as separate positional arguments.',
        },
        {
          id: 'l16-c2-e3',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['unpacking'],
          prompt: 'def f(**kwargs): — kwargs inside f is a…',
          options: ['dict', 'tuple', 'list', 'set'],
          answerIndex: 0,
          explanation: '**kwargs collects keyword arguments into a dictionary.',
        },
        {
          id: 'l16-c2-e4',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['unpacking'],
          prompt: 'a, *rest, b = [1, 2, 3, 4] gives rest = ?',
          options: ['[2, 3]', '[1, 2, 3]', '[4]', '(2, 3)'],
          answerIndex: 0,
          explanation: 'Extended unpacking: rest gets middle elements as list [2, 3].',
        },
      ],
    },
    {
      id: 'l16-c3',
      title: 'nonlocal & docstrings',
      objective: 'Modify enclosing function variables; document functions with docstrings.',
      miniNote: 'nonlocal binds assignment in nested def to the enclosing function scope (not global). Docstring is first string literal in function body.',
      examples: [
        {
          id: 'l16-c3-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['scope'],
          prompt: 'Trace nonlocal in a nested function.',
          code: 'def outer():\n    n = 0\n    def inner():\n        nonlocal n\n        n += 1\n    inner()\n    inner()\n    return n\n\nx = outer()',
          steps: [
            { line: 1, vars: {} },
            { line: 9, vars: {} },
            { line: 2, vars: { n: '0' } },
            { line: 9, vars: { x: '2' } },
          ],
          question: 'What is x?',
          options: ['2', '1', '0', 'Error'],
          answerIndex: 0,
          explanation: 'nonlocal n lets inner modify outer\'s n — incremented twice.',
        },
        {
          id: 'l16-c3-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['scope'],
          prompt: 'Without nonlocal, n += 1 inside inner() when n is from outer() causes…',
          options: ['UnboundLocalError', 'SyntaxError', 'n becomes global', 'Nothing — works fine'],
          answerIndex: 0,
          explanation: 'Assignment makes n local to inner; reading before assign fails.',
        },
        {
          id: 'l16-c3-e3',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['scope'],
          prompt: 'Function docstring is accessed via…',
          options: ['help(f) or f.__doc__', 'f.doc()', 'print(f)', 'import docstring'],
          answerIndex: 0,
          explanation: 'First """...""" in function body becomes __doc__.',
        },
        {
          id: 'l16-c3-e4',
          type: 'orderLines',
          stage: 'stretch',
          tags: ['scope'],
          prompt: 'Order a documented function skeleton.',
          lines: [
            'def greet(name):',
            '    """Return a greeting for name."""',
            '    return f"Hi, {name}"',
          ],
          correctOrder: [0, 1, 2],
          explanation: 'def line, then docstring, then body — PEP 257 style.',
        },
      ],
    },
    {
      id: 'l16-c4',
      title: 'Type hints & match/case',
      objective: 'Read basic annotations and structural pattern matching (Python 3.10+).',
      miniNote: 'Hints are for humans/tools — not enforced at runtime by default. match/case is multi-branch structural dispatch.',
      examples: [
        {
          id: 'l16-c4-e1',
          type: 'multipleChoice',
          stage: 'see',
          tags: ['typeHints'],
          prompt: 'def f(x: int) -> str: — the -> str means…',
          options: ['Annotated return type', 'Generator syntax', 'String comparison', 'Import required'],
          answerIndex: 0,
          explanation: 'Return annotation; optional for learning, common in modern codebases.',
        },
        {
          id: 'l16-c4-e2',
          type: 'traceSteps',
          stage: 'see',
          tags: ['patternMatch'],
          prompt: 'Trace simple match/case.',
          code: 'def label(n):\n    match n:\n        case 0:\n            return "zero"\n        case 1:\n            return "one"\n        case _:\n            return "many"\n\nx = label(1)',
          steps: [
            { line: 1, vars: {} },
            { line: 9, vars: {} },
            { line: 5, vars: {} },
            { line: 9, vars: { x: '"one"' } },
          ],
          question: 'What is x?',
          options: ['"one"', '"zero"', '"many"', 'Error'],
          answerIndex: 0,
          explanation: 'case 1 matches n=1 → returns "one". _ is wildcard default.',
        },
        {
          id: 'l16-c4-e3',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['typeHints'],
          prompt: 'list[int] in hints (3.9+) means…',
          options: ['List whose elements are ints', 'List of length int', 'Convert to int', 'Runtime cast'],
          answerIndex: 0,
          explanation: 'Generic hint — documentation/static checking; list still accepts any at runtime.',
        },
        {
          id: 'l16-c4-e4',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['patternMatch'],
          prompt: 'match/case _ branch is like…',
          options: ['else in if/elif chain', 'break in loop', 'except clause', 'import statement'],
          answerIndex: 0,
          explanation: 'Wildcard _ catches anything not matched above.',
        },
      ],
    },
    {
      id: 'l16-c5',
      title: 'Algorithms & stdlib gems',
      objective: 'Trace selection sort; use Counter; catch specific exceptions; alternate string formats.',
      miniNote: 'Selection sort: repeatedly pick min from unsorted suffix. collections.Counter counts hashable items.',
      examples: [
        {
          id: 'l16-c5-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['loopInvariant', 'loopLogic'],
          prompt: 'Trace one pass of selection sort (find min, swap).',
          code: 'a = [3, 1, 2]\n# pass 0: min at index 1 (value 1)\na[0], a[1] = a[1], a[0]',
          steps: [
            { line: 1, vars: { a: '[3, 1, 2]' } },
            { line: 3, vars: { a: '[1, 3, 2]' } },
          ],
          question: 'What is a after the swap?',
          options: ['[1, 3, 2]', '[1, 2, 3]', '[3, 1, 2]', '[2, 3, 1]'],
          answerIndex: 0,
          explanation: 'First pass places smallest element (1) at index 0.',
        },
        {
          id: 'l16-c5-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['dictKeys', 'comprehension'],
          prompt: 'from collections import Counter; Counter("aba") equals…',
          options: ['Counter({"a": 2, "b": 1})', '{"a": 2, "b": 1}', '[2, 1]', '3'],
          answerIndex: 0,
          explanation: 'Counter is dict subclass specialized for counting — most_common() is handy.',
        },
        {
          id: 'l16-c5-e3',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['exceptionType'],
          prompt: 'Better style than bare except:?',
          options: [
            'except ValueError: (specific type)',
            'except: pass always',
            'Never use try',
            'except all:',
          ],
          answerIndex: 0,
          explanation: 'Catch expected types; let unexpected errors surface with full traceback.',
        },
        {
          id: 'l16-c5-e4',
          type: 'matchPairs',
          stage: 'stretch',
          tags: ['typeCoercion'],
          prompt: 'Match formatting style to example.',
          leftItems: ['f"{x}"', '"{}".format(x)', '"%.2f" % pi', '# comment'],
          rightItems: ['f-string (preferred)', '.format method', '% interpolation (legacy)', 'ignored by interpreter'],
          pairs: [[0, 0], [1, 1], [2, 2], [3, 3]],
          explanation: 'Intro courses still show all three string formats plus # comments.',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l16-check-1',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['generators'],
      prompt: 'Lesson check: next(g) on exhausted generator raises…',
      options: ['StopIteration', 'RecursionError', 'GeneratorError', 'None'],
      answerIndex: 0,
      explanation: 'for loops catch StopIteration to end iteration.',
    },
    {
      id: 'l16-check-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['unpacking'],
      prompt: 'Lesson check: def f(a, b, *rest): f(1, 2, 3, 4) gives rest = ?',
      options: ['(3, 4)', '(1, 2, 3, 4)', '[3, 4]', 'Error'],
      answerIndex: 0,
      explanation: 'a=1, b=2, remaining positional args → rest tuple (3, 4).',
    },
    {
      id: 'l16-check-3',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['loopLogic'],
      prompt: 'Lesson check: selection sort on n items is O(?)',
      options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(1)'],
      answerIndex: 0,
      explanation: 'Nested structure over unsorted portion → quadratic.',
    },
    {
      id: 'l16-check-4',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['patternMatch'],
      prompt: 'Lesson check: match/case requires Python…',
      options: ['3.10+', '2.7', '3.6 only', 'Only PyPy'],
      answerIndex: 0,
      explanation: 'Structural pattern matching added in Python 3.10.',
    },
  ],
};
