import type { Lesson } from '../schema';

export const lesson07: Lesson = {
  id: 'lesson07',
  title: 'Lists & Tuples',
  subtitle: 'Mutation, aliasing, and ordered sequences',
  objectives: [
    'Create and index lists; predict slice behavior',
    'Mutate lists with append, assignment, and methods',
    'Trace aliasing when two names refer to one list',
    'Contrast mutable lists with immutable tuples',
  ],
  concepts: [
    {
      id: 'l7-c1',
      title: 'List basics',
      objective: 'Build lists, index elements, and slice sublists.',
      examples: [
        {
          id: 'l7-c1-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: [],
          prompt: 'Step through list creation and indexing.',
          code: 'nums = [10, 20, 30, 40]\nfirst = nums[0]\nlast = nums[-1]\nsub = nums[1:3]',
          steps: [
            { line: 1, vars: { nums: '[10, 20, 30, 40]' } },
            { line: 2, vars: { nums: '[10, 20, 30, 40]', first: '10' } },
            { line: 3, vars: { nums: '[10, 20, 30, 40]', first: '10', last: '40' } },
            { line: 4, vars: { nums: '[10, 20, 30, 40]', first: '10', last: '40', sub: '[20, 30]' } },
          ],
          question: 'What is sub?',
          options: ['[20, 30]', '[30, 30]', '[]', '{}'],
          answerIndex: 0,
          explanation: 'Slice [1:3] takes indices 1 and 2 → 20 and 30.',
        },
        {
          id: 'l7-c1-e2',
          type: 'traceSteps',
          stage: 'try',
          tags: ['offByOne'],
          prompt: 'Trace len and valid index range.',
          code: 'data = [5, 6, 7]\nn = len(data)\nlast_idx = n - 1\nval = data[last_idx]',
          steps: [
            { line: 1, vars: { data: '[5, 6, 7]' } },
            { line: 2, vars: { data: '[5, 6, 7]', n: '3' } },
            { line: 3, vars: { data: '[5, 6, 7]', n: '3', last_idx: '2' } },
            { line: 4, vars: { data: '[5, 6, 7]', n: '3', last_idx: '2', val: '7' } },
          ],
          question: 'What is val?',
          options: ['7', '8', '6', '14'],
          answerIndex: 0,
          explanation: 'Last valid index is len-1 = 2; data[2] is 7.',
        },
        {
          id: 'l7-c1-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: [],
          prompt: 'Which creates a list of three zeros?',
          options: ['[0] * 3', '3 * [0]', 'Both A and B', 'None of these'],
          answerIndex: 2,
          explanation: '[0] * 3 and 3 * [0] both yield [0, 0, 0].',
        },
      ],
    },
    {
      id: 'l7-c2',
      title: 'List mutation',
      objective: 'Change lists in place with index assignment and append.',
      miniNote: 'Mutating a list does not create a new list object — same id, new contents.',
      examples: [
        {
          id: 'l7-c2-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['mutation'],
          prompt: 'Trace in-place index assignment.',
          code: 'items = [1, 2, 3]\nitems[1] = 99\nitems.append(4)',
          steps: [
            { line: 1, vars: { items: '[1, 2, 3]' } },
            { line: 2, vars: { items: '[1, 99, 3]' } },
            { line: 3, vars: { items: '[1, 99, 3, 4]' } },
          ],
          question: 'What is items after all lines?',
          options: ['[1, 99, 3, 4]', '[1, 9, 3, 4]', '[]', '{}'],
          answerIndex: 0,
          explanation: 'Index 1 replaced with 99; append adds 4 at the end.',
        },
        {
          id: 'l7-c2-e2',
          type: 'traceSteps',
          stage: 'try',
          tags: ['mutation'],
          prompt: 'Trace pop and its return value.',
          code: 'stack = [10, 20, 30]\nx = stack.pop()\ny = stack.pop()',
          steps: [
            { line: 1, vars: { stack: '[10, 20, 30]' } },
            { line: 2, vars: { stack: '[10, 20]', x: '30' } },
            { line: 3, vars: { stack: '[10]', x: '30', y: '20' } },
          ],
          question: 'What are stack, x, and y?',
          options: ['stack=[10], x=30, y=20', 'stack=[10,20], x=30, y=20', 'stack=[10], x=20, y=30', 'stack=[], x=30, y=20'],
          answerIndex: 0,
          explanation: 'pop() removes and returns the last element each time.',
        },
        {
          id: 'l7-c2-e3',
          type: 'fixTheLine',
          stage: 'stretch',
          tags: ['mutation'],
          prompt: 'Goal: add 5 to end of lst. Which line fails?',
          code: 'lst = [1, 2, 3]\nlst[3] = 5',
          lineOptions: [1, 2],
          answerLine: 2,
          explanation: 'Index 3 is out of range for length-3 list. Use lst.append(5) instead.',
        },
      ],
    },
    {
      id: 'l7-c3',
      title: 'Aliasing',
      objective: 'When a = b, both names refer to the same list — changes show everywhere.',
      examples: [
        {
          id: 'l7-c3-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['aliasing', 'mutation'],
          prompt: 'Classic aliasing: modify through one name, see through both.',
          code: 'a = [1, 2]\nb = a\nb.append(3)',
          steps: [
            { line: 1, vars: { a: '[1, 2]' } },
            { line: 2, vars: { a: '[1, 2]', b: '[1, 2]' } },
            { line: 3, vars: { a: '[1, 2, 3]', b: '[1, 2, 3]' } },
          ],
          question: 'What is a after line 3?',
          options: ['[1, 2, 3]', '[1, 3, 3]', '[]', '{}'],
          answerIndex: 0,
          explanation: 'b and a reference the same list object; append via b changes a too.',
        },
        {
          id: 'l7-c3-e2',
          type: 'traceSteps',
          stage: 'try',
          tags: ['aliasing', 'mutation'],
          prompt: 'Aliasing through function parameter.',
          code: 'def grow(lst):\n    lst.append(0)\n\ndata = [5]\ngrow(data)',
          steps: [
            { line: 1, vars: {} },
            { line: 4, vars: { data: '[5]' } },
            { line: 5, vars: { data: '[5]', lst: '[5]' } },
            { line: 2, vars: { data: '[5, 0]', lst: '[5, 0]' } },
          ],
          question: 'What is data after grow(data)?',
          options: ['[5, 0]', '[5]', '[0, 5]', '[5, 0, 0]'],
          answerIndex: 0,
          explanation: 'lst is an alias to the same list as data; mutation persists after the call.',
        },
        {
          id: 'l7-c3-e3',
          type: 'traceSteps',
          stage: 'stretch',
          tags: ['aliasing', 'mutation'],
          prompt: 'Rebinding vs mutating — know the difference.',
          code: 'x = [1]\ny = x\nx = [2]\ny.append(3)',
          steps: [
            { line: 1, vars: { x: '[1]' } },
            { line: 2, vars: { x: '[1]', y: '[1]' } },
            { line: 3, vars: { x: '[2]', y: '[1]' } },
            { line: 4, vars: { x: '[2]', y: '[1, 3]' } },
          ],
          question: 'What are x and y after line 4?',
          options: ['x=[2], y=[1, 3]', 'x=[1], y=[1, 3]', 'x=[2], y=[2, 3]', 'x=[2], y=[1, 2, 3]'],
          answerIndex: 0,
          explanation: 'x = [2] rebinds x to a new list; y still points at the original [1], then [1, 3].',
        },
      ],
    },
    {
      id: 'l7-c4',
      title: 'Tuples',
      objective: 'Use () for fixed sequences; no append or item assignment.',
      examples: [
        {
          id: 'l7-c4-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['mutation'],
          prompt: 'Tuple packing and unpacking.',
          code: 'pair = (3, 4)\nx, y = pair\nz = pair[0] + pair[1]',
          steps: [
            { line: 1, vars: { pair: '(3, 4)' } },
            { line: 2, vars: { pair: '(3, 4)', x: '3', y: '4' } },
            { line: 3, vars: { pair: '(3, 4)', x: '3', y: '4', z: '7' } },
          ],
          question: 'What is z?',
          options: ['7', '8', '6', '14'],
          answerIndex: 0,
          explanation: '3 + 4 = 7. Tuples support indexing like lists.',
        },
        {
          id: 'l7-c4-e2',
          type: 'traceSteps',
          stage: 'try',
          tags: ['mutation', 'aliasing'],
          prompt: 'Tuple with mutable element — subtle aliasing.',
          code: 't = ([1], [2])\nt[0].append(9)',
          steps: [
            { line: 1, vars: { t: '([1], [2])' } },
            { line: 2, vars: { t: '([1, 9], [2])' } },
          ],
          question: 'What is t[0] after line 2?',
          options: ['[1, 9]', '[9, 1]', '[1, 9, 0]', '[1]'],
          answerIndex: 0,
          explanation: 'The tuple is immutable but its list elements are mutable.',
        },
        {
          id: 'l7-c4-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['mutation'],
          prompt: 'Which raises TypeError?',
          options: [
            't = (1, 2); t[0] = 5',
            't = (1, 2); len(t)',
            't = (1, 2); t + (3,)',
            't = (1,); t[0]',
          ],
          answerIndex: 0,
          explanation: 'Tuple items cannot be reassigned. Concatenation creates a new tuple.',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l7-check-1',
      type: 'traceSteps',
      stage: 'stretch',
      tags: ['aliasing', 'mutation'],
      prompt: 'Lesson check: trace shared nested list.',
      code: 'grid = [[0], [0]]\nrow = grid[0]\nrow[0] = 1',
      steps: [
        { line: 1, vars: { grid: '[[0], [0]]' } },
        { line: 2, vars: { grid: '[[0], [0]]', row: '[0]' } },
        { line: 3, vars: { grid: '[[1], [0]]', row: '[1]' } },
      ],
      question: 'What is grid[0] after line 3?',
      options: ['[1]', '[1, 2]', '[]', '[2]'],
          answerIndex: 0,
          explanation: 'row aliases grid[0]; mutating row[0] updates grid[0].',
    },
    {
      id: 'l7-check-2',
      type: 'traceSteps',
      stage: 'stretch',
      tags: ['aliasing', 'mutation'],
      prompt: 'Copy vs alias with slice assignment.',
      code: 'a = [1, 2, 3]\nb = a[:]\nb[0] = 99',
      steps: [
        { line: 1, vars: { a: '[1, 2, 3]' } },
        { line: 2, vars: { a: '[1, 2, 3]', b: '[1, 2, 3]' } },
        { line: 3, vars: { a: '[1, 2, 3]', b: '[99, 2, 3]' } },
      ],
      question: 'What is a after line 3?',
      options: ['[1, 2, 3]', '[1, 3, 3]', '[]', '{}'],
          answerIndex: 0,
          explanation: 'a[:] creates a shallow copy; changing b does not affect a.',
    },
    {
      id: 'l7-check-3',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['mutation'],
      prompt: '[0] * 3 creates three separate ints. [[0]] * 3 creates?',
      options: [
        'Three separate [0] lists',
        'Three references to the same [0] list',
        'SyntaxError',
        'A tuple of three zeros',
      ],
      answerIndex: 1,
      explanation: 'Multiplication repeats references, not deep copies — aliasing trap.',
    },
    {
      id: 'l7-check-4',
      type: 'traceSteps',
      stage: 'stretch',
      tags: ['aliasing', 'mutation'],
      prompt: 'Sort in place vs sorted().',
      code: 'nums = [3, 1, 2]\nother = nums\nnums.sort()',
      steps: [
        { line: 1, vars: { nums: '[3, 1, 2]' } },
        { line: 2, vars: { nums: '[3, 1, 2]', other: '[3, 1, 2]' } },
        { line: 3, vars: { nums: '[1, 2, 3]', other: '[1, 2, 3]' } },
      ],
      question: 'What is other after sort?',
      options: ['[1, 2, 3]', '[1, 3, 3]', '[]', '{}'],
          answerIndex: 0,
          explanation: 'other aliases nums; sort() mutates in place, so both see sorted order.',
    },
  ],
};
