import type { Lesson } from '../schema';

export const lesson02: Lesson = {
  id: 'lesson02',
  title: 'Operators & Expressions',
  subtitle: 'Arithmetic, comparison, logic, and precedence',
  objectives: [
    'Apply arithmetic operators including // and **',
    'Compare values with == vs is where relevant',
    'Combine conditions with and, or, not',
    'Predict evaluation order with operator precedence',
  ],
  concepts: [
    {
      id: 'l2-c1',
      title: 'Arithmetic operators',
      objective: 'Use +, -, *, /, //, %, and ** correctly.',
      examples: [
        {
          id: 'l2-c1-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['typeCoercion'],
          prompt: 'Step through arithmetic operations.',
          code: 'a = 17 // 5\nb = 17 % 5\nc = 2 ** 4',
          steps: [
            { line: 1, vars: { a: '3' } },
            { line: 2, vars: { a: '3', b: '2' } },
            { line: 3, vars: { a: '3', b: '2', c: '16' } },
          ],
          question: 'What is c?',
          options: ['16', '17', '15', '32'],
          answerIndex: 0,
          explanation: '** is exponentiation: 2**4 = 16.',
        },
        {
          id: 'l2-c1-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['typeCoercion'],
          prompt: 'What is 7 / 2 in Python 3?',
          options: ['3', '3.5', '3.0', '4'],
          answerIndex: 1,
          explanation: '/ always produces float in Python 3.',
        },
        {
          id: 'l2-c1-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['typeCoercion'],
          prompt: 'What is -17 // 5?',
          options: ['-3', '-4', '-3.4', '3'],
          answerIndex: 1,
          explanation: '// rounds toward negative infinity, not toward zero.',
        },
      ],
    },
    {
      id: 'l2-c2',
      title: 'Comparison operators',
      objective: 'Read ==, !=, <, >, <=, >= and chained comparisons.',
      examples: [
        {
          id: 'l2-c2-e1',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['truthiness'],
          prompt: 'What is 3 <= 3 <= 4?',
          options: ['True', 'False', 'Error', 'None'],
          answerIndex: 0,
          explanation: 'Chained comparisons: (3 <= 3) and (3 <= 4) → True and True.',
        },
        {
          id: 'l2-c2-e2',
          type: 'traceSteps',
          stage: 'see',
          tags: [],
          prompt: 'Trace comparison results.',
          code: 'x = 5\ny = 10\nr1 = x < y\nr2 = x == y',
          steps: [
            { line: 1, vars: { x: '5' } },
            { line: 2, vars: { x: '5', y: '10' } },
            { line: 3, vars: { x: '5', y: '10', r1: 'True' } },
            { line: 4, vars: { x: '5', y: '10', r1: 'True', r2: 'False' } },
          ],
          question: 'What is r2?',
          options: ['False', 'True', 'None', 'Error'],
          answerIndex: 0,
          explanation: '5 equals 10 is false.',
        },
        {
          id: 'l2-c2-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['typeCoercion'],
          prompt: 'What is "10" > 9?',
          options: ['True', 'False', 'TypeError', 'None'],
          answerIndex: 2,
          explanation: 'Python 3 does not compare str and int with ordering operators.',
        },
      ],
    },
    {
      id: 'l2-c3',
      title: 'Boolean logic',
      objective: 'Apply and, or, not and short-circuit behavior.',
      miniNote: 'and/or return the last evaluated operand, not always True/False.',
      examples: [
        {
          id: 'l2-c3-e1',
          type: 'traceSteps',
          stage: 'see',
          tags: ['truthiness'],
          prompt: 'Watch short-circuit evaluation.',
          code: 'a = 0\nb = 5\nr = a and b\ns = a or b',
          steps: [
            { line: 1, vars: { a: '0' } },
            { line: 2, vars: { a: '0', b: '5' } },
            { line: 3, vars: { a: '0', b: '5', r: '0' } },
            { line: 4, vars: { a: '0', b: '5', r: '0', s: '5' } },
          ],
          question: 'What is s?',
          options: ['5', '6', '4', '10'],
          answerIndex: 0,
          explanation: 'a or b: a is falsy, so b is returned (5).',
        },
        {
          id: 'l2-c3-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: ['truthiness'],
          prompt: 'What is not (3 > 5)?',
          options: ['True', 'False', '0', 'None'],
          answerIndex: 0,
          explanation: '3 > 5 is False; not False is True.',
        },
        {
          id: 'l2-c3-e3',
          type: 'multipleChoice',
          stage: 'stretch',
          tags: ['truthiness'],
          prompt: 'What does (True and 0) evaluate to?',
          options: ['True', 'False', '0', 'None'],
          answerIndex: 2,
          explanation: 'and returns last operand if all truthy; 0 is falsy so and stops at 0.',
        },
      ],
    },
    {
      id: 'l2-c4',
      title: 'Operator precedence',
      objective: 'Predict order: parentheses, **, */%, +- , comparisons, not, and, or.',
      examples: [
        {
          id: 'l2-c4-e1',
          type: 'multipleChoice',
          stage: 'try',
          tags: [],
          prompt: 'What is 2 + 3 * 4?',
          options: ['20', '14', '24', '9'],
          answerIndex: 1,
          explanation: 'Multiplication before addition: 3*4=12, 2+12=14.',
        },
        {
          id: 'l2-c4-e2',
          type: 'multipleChoice',
          stage: 'try',
          tags: [],
          prompt: 'What is 2 ** 3 ** 2? (hint: ** is right-associative)',
          options: ['64', '512', '256', '16'],
          answerIndex: 1,
          explanation: '2 ** (3 ** 2) = 2 ** 9 = 512.',
        },
        {
          id: 'l2-c4-e3',
          type: 'fillBlank',
          stage: 'stretch',
          tags: [],
          prompt: 'Add parentheses so the expression equals 20: 2 + 3 * 4',
          code: 'result = ____',
          blankLabel: 'expression',
          options: ['(2 + 3) * 4', '2 + 3 * 4', '20', '10'],
          answerIndex: 0,
          explanation: 'Parentheses force addition first: 5 * 4 = 20.',
        },
      ],
    },
  ],
  lessonCheck: [
    {
      id: 'l2-check-1',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['typeCoercion'],
      prompt: 'What is 10 % 3?',
      options: ['1', '3', '0', '3.33'],
      answerIndex: 0,
      explanation: '10 % 3 is remainder 1.',
    },
    {
      id: 'l2-check-2',
      type: 'multipleChoice',
      stage: 'stretch',
      tags: ['truthiness'],
      prompt: 'Which is True?',
      options: ['[] or [1]', '"" and "hi"', '0 or ""', 'None or 0'],
      answerIndex: 0,
      explanation: '[] is falsy, so or returns [1] which is truthy.',
    },
    {
      id: 'l2-check-3',
      type: 'traceSteps',
      stage: 'stretch',
      tags: [],
      prompt: 'Trace final expression.',
      code: 'x = 1 + 2 * 3\ny = (1 + 2) * 3',
      steps: [
        { line: 1, vars: { x: '7' } },
        { line: 2, vars: { x: '7', y: '9' } },
      ],
      question: 'What is y?',
      options: ['9', '10', '8', '18'],
          answerIndex: 0,
          explanation: 'Parentheses change order: (1+2)*3 = 9.',
    },
  ],
};
